Add new command: reconfigure

diff --git a/parts/pkg/lib/commands/reconfigure b/parts/pkg/lib/commands/reconfigure
--- a/parts/pkg/lib/commands/reconfigure
+++ b/parts/pkg/lib/commands/reconfigure
@@ -2,7 +2,7 @@
 #
 # ##############################################################################
 #
-# Copyright (C) 2014 Opinsys Oy
+# Copyright (C) 2015 Opinsys Oy
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -28,7 +28,7 @@ set -eu
 usage_error()
 {
     echo "error $1" >&2
-    echo "Try 'puavo-pkg configure --help' for more information." >&2
+    echo "Try 'puavo-pkg reconfigure --help' for more information." >&2
     return 1
 }
 
@@ -36,22 +36,21 @@ while [ $# -gt 0 ]; do
     case $1 in
         -h|--help)
             shift
-            echo "Usage: puavo-pkg configure PACKAGE [PACKAGE]..."
-            echo "Usage: puavo-pkg configure --all"
-            echo "Usage: puavo-pkg configure --help"
+            echo "Usage: puavo-pkg reconfigure PACKAGE [PACKAGE]..."
+            echo "Usage: puavo-pkg reconfigure --all"
+            echo "Usage: puavo-pkg reconfigure --help"
             echo
-            echo "Configure restricted packages."
+            echo "Reconfigure installed packages."
             echo
             echo "Options:"
             echo "    -h, --help                   print help and exit"
-            echo "    --all                        configure all installed packages"
+            echo "    --all                        reconfigure all installed packages"
             echo
             exit 0
             ;;
         --all)
             shift
-            packages=$(puavo-pkg list \
-                | awk '{ if ($3 == "INSTALLED") print $1 }')
+            packages=$(puavo-pkg list)
             set -- ${packages}
             [ $# -eq 0 ] && exit 0
             break
@@ -76,10 +75,10 @@ fi
 exitval=0
 
 for package in "$@"; do
-    configure_package "${package}" || {
+    reconfigure_package "${package}" || {
         exitval=$?
-        echo "E: failed to configure package '${package}'" >&2
-        # Continue until we have tried to configure all given packages
+        echo "E: failed to reconfigure package '${package}'" >&2
+        # Continue until we have tried to reconfigure all given packages
         # and then fail.
     }
 done
