restricted-packages: add remove command

diff --git a/parts/pkg/lib/commands/remove b/parts/pkg/lib/commands/remove
--- a/parts/pkg/lib/commands/remove
+++ b/parts/pkg/lib/commands/remove
@@ -1,8 +1,8 @@
-#!/bin/sh
+#!/bin/bash
 #
 # ##############################################################################
 #
-# Copyright (C) 2014 Opinsys Oy
+# Copyright (C) 2015 Opinsys Oy
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -23,46 +23,27 @@
 
 set -eu
 
-RESTRICTED_PKG_LIBDIR=${RESTRICTED_PKG_LIBDIR:-/usr/lib/puavo-ltsp-client/restricted-packages}
-RESTRICTED_PKG_SHAREDIR=${RESTRICTED_PKG_SHAREDIR:-/usr/share/puavo-ltsp-client/restricted-packages}
-RESTRICTED_PKG_STATEDIR=${RESTRICTED_PKG_STATEDIR:-/state/restricted-packages}
-
-if [ -z "${PUAVOLTSP_IMAGE_NAME:-}" ]; then
-    read PUAVOLTSP_IMAGE_NAME </etc/ltsp/this_ltspimage_name
-fi
-
-export PUAVOLTSP_IMAGE_NAME    \
-       RESTRICTED_PKG_LIBDIR   \
-       RESTRICTED_PKG_SHAREDIR \
-       RESTRICTED_PKG_STATEDIR
+. "${RESTRICTED_PKG_LIBDIR}/common.bash"
 
 usage_error()
 {
     echo "error $1" >&2
-    echo "Try '$0 --help' for more information." >&2
+    echo "Try 'puavo-restricted-package-tool remove --help' for more information." >&2
     return 1
-}
-
-print_help_and_exit()
-{
-    echo "Usage: $0 [COMMAND] [COMMAND_OPTIONS]"
-    echo
-    echo "Package manager for Puavo packages."
-    echo
-    echo "Commands:"
-    echo "    install                      install a package"
-    echo "    list                         list installed packages"
-    echo "    remove                       remove an installed package"
-
-    echo
-    exit 0
 }
 
 while [ $# -gt 0 ]; do
     case $1 in
         -h|--help)
             shift
-            print_help_and_exit
+            echo "Usage: puavo-restricted-package-tool remove PACKAGE_NAME"
+            echo
+            echo "Remove an installed package."
+            echo
+            echo "Options:"
+            echo "    -h, --help                   print help and exit"
+            echo
+            exit 0
             ;;
         --)
             shift
@@ -78,18 +59,15 @@ while [ $# -gt 0 ]; do
 done
 
 if [ $# -lt 1 ]; then
-    print_help_and_exit
+    usage_error "invalid number of arguments ($#), expected 1"
 fi
 
-command=$1
+package_name=$1
 shift
 
-case "${command}" in
-    install|list|remove)
-        "${RESTRICTED_PKG_LIBDIR}/commands/${command}" "$@"
-        ;;
-    *)
-        usage_error "unknown command '${command}'"
-esac
+remove_package "${package_name}" || {
+    echo "E: failed to remove package '${package_name}'" >&2
+    exit 1
+}
 
 exit 0
