Do not fail in puavo-update-admins if fetching org.json fails, but if it is missing then that is bad.

diff --git a/rules/adm/files/puavo-update-admins b/rules/adm/files/puavo-update-admins
--- a/rules/adm/files/puavo-update-admins
+++ b/rules/adm/files/puavo-update-admins
@@ -119,9 +119,18 @@ else
   prr_args='--user-etc'
 fi
 
-puavo-rest-request /v3/current_organisation "$prr_args" \
-  > "${org_json_path}.tmp"
-mv "${org_json_path}.tmp" "$org_json_path"
+# it is okay if this fails
+{
+  puavo-rest-request /v3/current_organisation "$prr_args" \
+    > "${org_json_path}.tmp"
+  mv "${org_json_path}.tmp" "$org_json_path"
+} || true
+
+# but without org.json we can not continue
+if [ ! -e "$org_json_path" ]; then
+  echo "No org.json in $org_json_path" >&2
+  exit 1
+fi
 
 adm_users_json=$(get_adm_users_json "$org_json_path")
 
