Use consistent two-column indent in puavo-install-and-update-ltspimages.

diff --git a/parts/ltsp/puavo-install/puavo-install-and-update-ltspimages b/parts/ltsp/puavo-install/puavo-install-and-update-ltspimages
--- a/parts/ltsp/puavo-install/puavo-install-and-update-ltspimages
+++ b/parts/ltsp/puavo-install/puavo-install-and-update-ltspimages
@@ -244,21 +244,21 @@ cleanup_previous_runs() {
     "${puavoinstall_libdir}/ls-old-imageoverlays" "${images_dir}" \
 						  /imageoverlays)
   if [ -n "${old_imageoverlays}" ]; then
-      if ${delete_overlays}; then
-          echo -n "${old_imageoverlays}" | xargs -r -d'\n' -L1 rm -rf
-      else
-          log err "cleanup failed: old images have existing overlays and --delete-overlays was not used" >&2
-          return 1
-      fi
+    if ${delete_overlays}; then
+      echo -n "${old_imageoverlays}" | xargs -r -d'\n' -L1 rm -rf
+    else
+      log err "cleanup failed: old images have existing overlays and --delete-overlays was not used" >&2
+      return 1
+    fi
   fi
 
   # cleanup old ltsp images (and their possible temporary *.tmp files).
   # The ltsp-backup.img is going to go too...
   old_images=$("${puavoinstall_libdir}/ls-old-images" "${images_dir}")
   if [ -n "${old_images}" ]; then
-      echo -n "${old_images}" \
-        | grep -vx "${images_dir}/${preserve_filename}" \
-        | xargs -r -d'\n' -L1 rm -f
+    echo -n "${old_images}" \
+      | grep -vx "${images_dir}/${preserve_filename}" \
+      | xargs -r -d'\n' -L1 rm -f
   fi
 
   # cleanup old rdiff files, except those that we want to use right now
