In puavo-install-grub, list functions first and the main.

diff --git a/parts/ltsp/puavo-install/puavo-install-grub b/parts/ltsp/puavo-install/puavo-install-grub
--- a/parts/ltsp/puavo-install/puavo-install-grub
+++ b/parts/ltsp/puavo-install/puavo-install-grub
@@ -434,6 +434,65 @@ lookup_windows_chainloader() {
   fi
 }
 
+mount_efi_partition() {
+  local efi_devpath
+  efi_devpath=$1
+
+  mountpoint -q /boot/efi && return 0
+
+  fsck.fat -a "$efi_devpath" > /dev/null 2>&1 || true
+  mount "$efi_devpath" /boot/efi || return 1
+}
+
+install_legacy_grub() {
+  local boot_dir grubdev
+
+  boot_dir=$1
+  grubdev=$2
+
+  if ! grub_msg=$(grub-install --boot-directory="$boot_dir" \
+                    --target=i386-pc "$grubdev" 3>&- 4>&- 5>&- 2>&1); then
+    log err "Grub (MBR) installation to ${grubdev} failed: ${grub_msg}"
+    return 1
+  fi
+
+  log info "Grub (MBR) installation to ${grubdev} was OK."
+
+  return 0
+}
+
+install_efi_grub() {
+  local boot_dir efi_devpath grubdev grub_efi_arguments vgname
+
+  boot_dir=$1
+  efi_devpath=$2
+  grubdev=$3
+  vgname=$4
+
+  if ! mount_efi_partition "$efi_devpath"; then
+    log err "could not mount /boot/efi from ${efi_devpath}"
+    return 1
+  fi
+
+  # We might actually have leftover nvram dumps from previous installations
+  # that prevent a successful bootloader installation. Clean them up first.
+  rm -f /sys/firmware/efi/efivars/dump-*
+
+  grub_efi_arguments=$(get_grub_efi_arguments "$vgname")
+  if ! grub_msg=$(grub-install --boot-directory="$boot_dir" \
+                    $grub_efi_arguments "$grubdev" \
+                    3>&- 4>&- 5>&- 2>&1); then
+    log err "Grub (UEFI) installation to ${grubdev} failed: ${grub_msg}"
+    umount /boot/efi || true
+    return 1
+  fi
+  umount /boot/efi || true
+
+  log info "Grub (UEFI) installation to ${grubdev} was OK."
+
+  return 0
+}
+
 usage() {
   cat <<EOF
 $(basename $0) [optional arguments]
@@ -538,65 +597,6 @@ case "$hosttype" in
     exit 1
     ;;
 esac
-
-mount_efi_partition() {
-  local efi_devpath
-  efi_devpath=$1
-
-  mountpoint -q /boot/efi && return 0
-
-  fsck.fat -a "$efi_devpath" > /dev/null 2>&1 || true
-  mount "$efi_devpath" /boot/efi || return 1
-}
-
-install_legacy_grub() {
-  local boot_dir grubdev
-
-  boot_dir=$1
-  grubdev=$2
-
-  if ! grub_msg=$(grub-install --boot-directory="$boot_dir" \
-                    --target=i386-pc "$grubdev" 3>&- 4>&- 5>&- 2>&1); then
-    log err "Grub (MBR) installation to ${grubdev} failed: ${grub_msg}"
-    return 1
-  fi
-
-  log info "Grub (MBR) installation to ${grubdev} was OK."
-
-  return 0
-}
-
-install_efi_grub() {
-  local boot_dir efi_devpath grubdev grub_efi_arguments vgname
-
-  boot_dir=$1
-  efi_devpath=$2
-  grubdev=$3
-  vgname=$4
-
-  if ! mount_efi_partition "$efi_devpath"; then
-    log err "could not mount /boot/efi from ${efi_devpath}"
-    return 1
-  fi
-
-  # We might actually have leftover nvram dumps from previous installations
-  # that prevent a successful bootloader installation. Clean them up first.
-  rm -f /sys/firmware/efi/efivars/dump-*
-
-  grub_efi_arguments=$(get_grub_efi_arguments "$vgname")
-  if ! grub_msg=$(grub-install --boot-directory="$boot_dir" \
-                    $grub_efi_arguments "$grubdev" \
-                    3>&- 4>&- 5>&- 2>&1); then
-    log err "Grub (UEFI) installation to ${grubdev} failed: ${grub_msg}"
-    umount /boot/efi || true
-    return 1
-  fi
-  umount /boot/efi || true
-
-  log info "Grub (UEFI) installation to ${grubdev} was OK."
-
-  return 0
-}
 
 grub_install_done=false
 
