Closing lid doesn't put device to sleep when netbooted. Ask the user if they'd like for us to run the sleep command for them.

diff --git a/parts/ltsp/puavo-install/puavo-disk-erase b/parts/ltsp/puavo-install/puavo-disk-erase
--- a/parts/ltsp/puavo-install/puavo-disk-erase
+++ b/parts/ltsp/puavo-install/puavo-disk-erase
@@ -28,6 +28,28 @@ secure_erase() {
   if ! hdparm -I "${target_disk}" | grep -P "not\tfrozen" >&2; then
     echo 'Disk is in frozen state, aborting!' >&2
     echo 'Please close the lid of the device for a few seconds, reopen it and try again.' >&2
+    echo
+    echo 'If we are netbooted, we can only put the device to sleep by issuing the following command:'
+    echo 'echo -n mem > /sys/power/state'
+    echo
+    read -p "Shall I run the command for you? (y/n)[y] " gosleep
+      case $gosleep in
+        [yY]|"")
+          echo 'Going to sleep now.'
+          sleep 1
+          echo -n mem > /sys/power/state
+          ;;
+        [nN])
+          echo 'Not going to sleep. You must close the lid and reopen, or run the command by hand. Then retry.'
+          sleep 1
+          exit 1
+          ;;
+        *)
+          echo 'Invalid response, exiting.' >&2
+          sleep 1
+          exit 1
+          ;;
+      esac
     exit 1
   fi
 
