Small stylistic change in puavo-install-and-update-ltspimages.

diff --git a/parts/ltsp/puavo-install/puavo-install-and-update-ltspimages b/parts/ltsp/puavo-install/puavo-install-and-update-ltspimages
--- a/parts/ltsp/puavo-install/puavo-install-and-update-ltspimages
+++ b/parts/ltsp/puavo-install/puavo-install-and-update-ltspimages
@@ -359,11 +359,10 @@ get_next_image() {
     return 1
   fi
 
-  rdiff_filename=$(get_rdiff_filename $previous_image $next_image) || {
-      log err "failed to determine the filename of rdiff between images \
-'${previous_image}' and '${next_image}'"
-      return 1
-  }
+  if ! rdiff_filename=$(get_rdiff_filename $previous_image $next_image); then
+    log err "failed to determine the rdiff filename between '${previous_image}' and '${next_image}'"
+    return 1
+  fi
 
   mkdir -p "$rdiffs_dir"
 
