install: add preseeding capability to puavo-install

diff --git a/parts/ltsp/puavo-install/puavo-install b/parts/ltsp/puavo-install/puavo-install
--- a/parts/ltsp/puavo-install/puavo-install
+++ b/parts/ltsp/puavo-install/puavo-install
@@ -2,14 +2,58 @@
 
 set -e
 
-puavo-register --accepted-devicetypes \
-	       fatclient,laptop,ltspserver,thinclient,wirelessaccesspoint
+puavo_register_args=
+puavo_setup_filesystems_args=
+
+preseeds=$(ls -1 /usr/share/puavo-ltsp-install/preseeds | sort)
+preseed_count=$(echo "${preseeds}" | wc -l)
+
+# Ask the preferred preseed if there are some available.
+[ -n "${preseeds}" ] && while true; do
+    echo "Installer preseeds:"
+    # Print the list of preseeds.
+    echo "0\tNO PREESEDING"
+    echo "${preseeds}" | awk '{printf "%d\t%s\n", NR, $0}'
+
+    # The default preseed is the first item, number 0.
+    read -p "Select preseed number [0]: " preseed_nr
+    [ -n "${preseed_nr}" ] || preseed_nr=0
+
+    # Ensure the value is a valid integer.
+    case "${preseed_nr}" in
+        ''|*[!0-9]*)
+            echo "E: invalid preseed number" >&2
+            continue
+            ;;
+        *)
+            ;;
+    esac
+
+    # Ensure the integer has a valid value.
+    if [ 0 -gt "${preseed_nr}" -o "${preseed_nr}" -gt "${preseed_count}" ]; then
+        echo "E: invalid preseed number" >&2
+        continue
+    fi
+
+    # Preseed 0 always means no preseeding at all.
+    [ "${preseed_nr}" -eq 0 ] && break
+
+    # Apply preseeds and continue installation.
+    preseed=$(echo "${preseeds}" | sed -n "${preseed_nr}p")
+    puavo_register_args=$(cat "/usr/share/puavo-ltsp-install/preseeds/${preseed}/puavo_register_args")
+    puavo_setup_filesystems_args=$(cat "/usr/share/puavo-ltsp-install/preseeds/${preseed}/puavo_setup_filesystems_args")
+    break
+done
+
+puavo-register \
+    --accepted-devicetypes fatclient,laptop,ltspserver,thinclient,wirelessaccesspoint \
+    ${puavo_register_args}
 
 hosttype="$(cat /etc/puavo/hosttype)"
 
 case "$hosttype" in
   laptop|wirelessaccesspoint)
-    puavo-setup-filesystems
+    puavo-setup-filesystems ${puavo_setup_filesystems_args}
 
     mkdir -p /state/etc
     cp -aT /etc/puavo /state/etc/puavo
@@ -41,7 +85,7 @@ case "$hosttype" in
     read answer
     ;;
   ltspserver)
-    puavo-setup-filesystems
+    puavo-setup-filesystems ${puavo_setup_filesystems_args}
     mkdir -p /state/etc
     cp -a /etc/puavo /state/etc
 
