puavo-manage-efi: add support for installing Windows boot manager
Installation of Windows boot manager is not simple.

1. Ensure ESP has Windows boot manager and all its files (copied from Boot.wim, by puavo-reset-windows).
2. Generate Boot Configuration Data (BCD) with GPT correct partition UUIDs.
3. Create EFI Boot entry

diff --git a/parts/ltsp/puavo-install/puavo-manage-efi b/parts/ltsp/puavo-install/puavo-manage-efi
--- a/parts/ltsp/puavo-install/puavo-manage-efi
+++ b/parts/ltsp/puavo-install/puavo-manage-efi
@@ -7,7 +7,11 @@ g_exitval=1
 g_no_efi_is_ok=false
 g_cmd=
 g_esp_mount_path=
+g_esp_devpath=
+g_win_c_partition_devpath=
+g_win_disk=
 PID_FILE=/run/puavo-manage-efi.pid # Locks this file to ensure only one puavo-manage-efi is running
+ESP_WINDOWS_DIR_SUFFIX='/EFI/Microsoft'
 
 log() {
   logger -t puavo-manage-efi -p "user.${1}" "$2" || true
@@ -41,15 +45,106 @@ get_windows_boot_entries_to_change() {
   '
 }
 
+get_esp_devpaths()
+{
+  lsblk -n -l -o PATH,PARTTYPE -- "$@" | awk '$2 == "c12a7328-f81f-11d2-ba4b-00a0c93ec93b" {print $1}'
+}
+
+get_one_esp_devpath()
+{
+  local esp_devpath esp_devpath_count line
+
+  esp_devpath_count=0
+
+  while read -r line; do
+    if [ -z "${line}" ]; then
+      continue
+    fi
+    esp_devpath="${line}"
+    log notice "Found ESP at '${esp_devpath}'"
+    esp_devpath_count=$((esp_devpath_count + 1))
+  done < <(get_esp_devpaths "$@") || {
+    log err 'failed to find ESP'
+    return 1
+  }
+
+  if [ ${esp_devpath_count} -eq 0 ]; then
+    log err 'failed to find ESP'
+    return 1
+  elif [ ${esp_devpath_count} -gt 1 ]; then
+    log err 'found multiple ESPs'
+    return 1
+  fi
+
+  echo -n "${esp_devpath}"
+}
+
+get_partnum()
+{
+  local devpath partnum
+
+  devpath="$1"
+  shift
+
+  partnum=$(stat --format %Lr "${devpath}") || {
+    log err 'failed to get the partition number'
+    return 1
+  }
+
+  if [ "$partnum" -lt 1 ]; then
+    log err "file '${devpath}' is not a block device"
+    return 1
+  fi
+
+  echo -n "$partnum"
+}
+
+get_disk()
+{
+  local part_devpath disk_devpath
+
+  part_devpath=$1
+  shift
+
+  disk_devpath=$(lsblk -p -J -s "${part_devpath}" | jq -r '.blockdevices[0].children[0] | select(.type == "disk").name') || {
+    log err "failed to find disk for '${part_devpath}'"
+    return 1
+  }
+
+  if [ -z "${disk_devpath}" ]; then
+    log err 'failed to find disk (jq empty output)'
+    return 1
+  fi
+
+  echo -n "${disk_devpath}"
+}
+
+efibootmgr_windows_create() {
+  local esp_partnum
+
+  log notice 'creating a Windows boot entry'
+
+  esp_partnum=$(get_partnum "${g_esp_devpath}") || return 1
+
+  efibootmgr -q -c -L 'Windows Boot Manager' -l '\EFI\Microsoft\Boot\bootmgfw.efi' -d "${g_win_disk}" -p "${esp_partnum}" || {
+    log err 'failed to create a Windows boot entry'
+    return 1
+  }
+
+  log notice 'created a Windows boot entry'
+}
+
 efibootmgr_windows() {
   local boot_entry efibootmgr_flag enable_or_disable_msg
 
   efibootmgr_flag=$1
+  shift
   case "$efibootmgr_flag" in
     -A) enable_or_disable_msg='disabling' ;;
     -a) enable_or_disable_msg='enabling'  ;;
      *) return 1;;
   esac
+
 
   for boot_entry in $(get_windows_boot_entries_to_change "$efibootmgr_flag"); do
     log notice "${enable_or_disable_msg} Windows boot entry ${boot_entry}"
@@ -60,51 +155,47 @@ efibootmgr_windows() {
 }
 
 esp_mount() {
-  local esp_devpath esp_boot_efi_mounts
+  local esp_devpath esp_or_boot_efi_mount
 
-  esp_devpath=$(lsblk -n -l -o PATH,PARTTYPE | awk '$2 == "c12a7328-f81f-11d2-ba4b-00a0c93ec93b" {print $1}') || return 1
-  if [ -z "${esp_devpath}" ]; then
-    log err 'EFI system partition not found'
-    return 1
-  fi
+  esp_devpath="$1"
+  shift
 
-  esp_boot_efi_mounts=$(awk "-vdev=${esp_devpath}" '$1 == dev && $2 == "/boot/efi" {print $2}' /proc/mounts) || return 1
-
-  # Umount if already mounted to /boot/efi to ensure we control mount options.
-  if [ -n "${esp_boot_efi_mounts}" ]; then
-    log warning '/boot/efi was already mounted, umounting it'
-    umount /boot/efi || return 1
-  fi
+  # Umount if already mounted to ensure we control mount options.
+  while IFS= read -r -d $'\0' esp_or_boot_efi_mount; do
+    log warning "'${esp_or_boot_efi_mount}' was already mounted, umounting it"
+    umount "${esp_or_boot_efi_mount}" || return 1
+  done < <(awk "-vdev=${esp_devpath}" '$1 == dev && $2 == "/boot/efi" { printf "%s" $2 }' /proc/mounts) || return 1
 
   mkdir -p /boot/efi || return 1
   mount -onodev,nosuid "${esp_devpath}" /boot/efi || return 1
-  echo /boot/efi
+  echo -n /boot/efi
 }
 
 esp_break_windows() {
-  local defused_windows_file tmp_defused_windows_file
+  local defused_windows_file esp_windows_dir tmp_defused_windows_file
 
-  defused_windows_file='/boot/efi/EFI/Puavo-defused-Windows.tar.gz'
+  esp_windows_dir="${g_esp_mount_path}${ESP_WINDOWS_DIR_SUFFIX}"
+  defused_windows_file="${g_esp_mount_path}/EFI/Puavo-defused-Windows.tar.gz"
   tmp_defused_windows_file="${defused_windows_file}.tmp"
   rm -f "$tmp_defused_windows_file"
 
   if [ -e "$defused_windows_file" ]; then
     # nothing to do
-    if [ -d '/boot/efi/EFI/Microsoft' ]; then
-      log info "cleaning up /boot/efi/EFI/Microsoft that should not exist"
-      rm -rf '/boot/efi/EFI/Microsoft' || true
+    if [ -d "${esp_windows_dir}" ]; then
+      log info "cleaning up ${esp_windows_dir} that should not exist"
+      rm -rf "${esp_windows_dir}" || true
     fi
     return 0
   fi
 
-  if [ ! -d '/boot/efi/EFI/Microsoft' ]; then
+  if [ ! -d "${esp_windows_dir}" ]; then
     # not doing/logging anything, perhaps we do not have Windows installed
     # and that should be normal
     return 0
   fi
 
   log info 'defusing Windows...'
-  tar -C '/boot/efi/EFI' -z -c -f "$tmp_defused_windows_file" Microsoft || {
+  tar -C "${g_esp_mount_path}/EFI" -z -c -f "$tmp_defused_windows_file" Microsoft || {
     log err 'failed to defuse Windows (tar error)'
     rm -f "$tmp_defused_windows_file" || true
     return 1
@@ -114,8 +205,8 @@ esp_break_windows() {
     log err 'failed to defuse Windows (mv error)'
     return 1
   fi
-  if ! rm -rf '/boot/efi/EFI/Microsoft'; then
-    log warning "error cleaning up /boot/efi/EFI/Microsoft"
+  if ! rm -rf "${esp_windows_dir}"; then
+    log warning "error cleaning up ${esp_windows_dir}"
     return 1
   fi
 
@@ -124,10 +215,57 @@ esp_break_windows() {
   return 0
 }
 
+esp_install_windows() {
+  local defused_windows_file esp_windows_dir tmp_windows_dir
+
+  esp_windows_dir="${g_esp_mount_path}${ESP_WINDOWS_DIR_SUFFIX}"
+  defused_windows_file="${g_esp_mount_path}/EFI/Puavo-defused-Windows.tar.gz"
+  tmp_windows_dir="${esp_windows_dir}.tmp"
+  rm -rf "${tmp_windows_dir}"
+
+  if [ -e "${defused_windows_file}" ]; then
+    log err 'ESP already contains a defused Windows'
+    return 1
+  fi
+
+  if [ -e "${esp_windows_dir}" ]; then
+    log err 'ESP already contains Windows'
+    return 1
+  fi
+
+  log info 'installing Windows bootloader...'
+  mkdir -p "${tmp_windows_dir}" || {
+    log err 'failed to install Windows bootloader (mkdir)'
+    return 1
+  }
+  puavo-reset-windows --mode install-boot-dir "${g_win_c_partition_devpath}" "${tmp_windows_dir}" || {
+    log err 'failed to install Windows bootloader (puavo-reset-windows)'
+    rm -rf "${tmp_windows_dir}" || true
+    return 1
+  }
+  mv -n -T "${tmp_windows_dir}" "${esp_windows_dir}" || {
+    log err 'failed to install Windows bootloader (mv)'
+    rm -rf "${tmp_windows_dir}" || true
+    return 1
+  }
+  if [ -d "${tmp_windows_dir}" ]; then
+    # mv failed because the source dir still exists
+    log err 'failed to install Windows bootloader (mv)'
+    rm -rf "${esp_windows_dir}" || true
+    rm -rf "${tmp_windows_dir}" || true
+    return 1
+  fi
+
+  sync || true
+
+  log info 'Windows bootloader installed'
+}
+
 esp_fix_windows() {
   local defused_windows_file tmp_defused_windows_file
 
-  defused_windows_file='/boot/efi/EFI/Puavo-defused-Windows.tar.gz'
+  esp_windows_dir="${g_esp_mount_path}${ESP_WINDOWS_DIR_SUFFIX}"
+  defused_windows_file="${g_esp_mount_path}/EFI/Puavo-defused-Windows.tar.gz"
   tmp_defused_windows_file="${defused_windows_file}.tmp"
   rm -f "$tmp_defused_windows_file"
 
@@ -137,9 +275,9 @@ esp_fix_windows() {
   fi
 
   log info 'repriming Windows...'
-  tar -C '/boot/efi/EFI' -z -x -f "$defused_windows_file" || {
+  tar -C "${g_esp_mount_path}/EFI" -z -x -f "$defused_windows_file" || {
     log err 'error repriming Windows (tar error)'
-    rm -rf '/boot/efi/EFI/Microsoft' || true
+    rm -rf "${esp_windows_dir}" || true
     return 1
   }
   sync || true
@@ -162,12 +300,19 @@ efi_enable_windows() {
   efibootmgr_windows -a
 }
 
+efi_install_windows() {
+  esp_install_windows || return 1
+  efibootmgr_windows_create
+}
+
 has_efi() {
   grep -q '^efivarfs ' /proc/mounts
 }
 
 usage() {
-  echo "Usage: $0 [OPTIONS] COMMAND"
+  echo "Usage: $0 [OPTIONS] disable-windows"
+  echo "       $0 [OPTIONS] enabled-windows"
+  echo "       $0 [OPTIONS] install-windows WIN_C_PARTITION_DEVPATH"
   echo "       $0 --help"
 }
 
@@ -195,6 +340,7 @@ while [ $# -gt 0 ]; do
         echo "Commands:"
         echo "    disable-windows              disable Windows"
         echo "    enable-windows               enable Windows"
+        echo "    install-windows              install Windows boot manager to ESP, lookup Windows version from WIN_C_PARTITION_DEVPATH"
         echo
         echo "Options:"
         echo "    --no-efi-is-ok               exit with status 0 if the system does not use EFI"
@@ -220,12 +366,24 @@ while [ $# -gt 0 ]; do
   esac
 done
 
-if [ $# -ne 1 ]; then
-  usage_error "invalid number of arguments ($#), expected 1"
+if [ $# -lt 1 ]; then
+  usage_error 'COMMAND is missing'
 fi
 
 g_cmd=$1
 shift
+
+if [ "${g_cmd}" = 'install-windows' ]; then
+  if [ $# -lt 1 ]; then
+    usage_error 'WIN_C_PARTITION_DEVPATH is missing'
+  fi
+  g_win_c_partition_devpath=$1
+  shift
+fi
+
+if [ $# -ne 0 ]; then
+  usage_error 'too many arguments'
+fi
 
 if ! has_efi; then
   if ${g_no_efi_is_ok}; then
@@ -252,14 +410,22 @@ trap on_exit EXIT
 
 echo "$$" >"${PID_FILE}"
 
-g_esp_mount_path=$(esp_mount)
-
 case "${g_cmd}" in
   enable-windows)
+    g_esp_devpath=$(get_one_esp_devpath)
+    g_esp_mount_path=$(esp_mount "${g_esp_devpath}")
     efi_enable_windows
     ;;
   disable-windows)
+    g_esp_devpath=$(get_one_esp_devpath)
+    g_esp_mount_path=$(esp_mount "${g_esp_devpath}")
     efi_disable_windows
+    ;;
+  install-windows)
+    g_win_disk=$(get_disk "${g_win_c_partition_devpath}")
+    g_esp_devpath=$(get_one_esp_devpath "${g_win_disk}")
+    g_esp_mount_path=$(esp_mount "${g_esp_devpath}")
+    efi_install_windows
     ;;
   *)
     usage_error "invalid command '${g_cmd}'"
