Rename incoming *.tmp image to its non-tmp version once it has been checked.
It should not be *.tmp when it is finished and ready for use
and bittorrent seeding.

diff --git a/parts/ltsp/puavo-install/puavo-install-and-update-ltspimages b/parts/ltsp/puavo-install/puavo-install-and-update-ltspimages
--- a/parts/ltsp/puavo-install/puavo-install-and-update-ltspimages
+++ b/parts/ltsp/puavo-install/puavo-install-and-update-ltspimages
@@ -197,21 +197,44 @@ check_checksums_exist_for() {
 }
 
 check_image_and_put_it_to_use() {
-  local next_image next_image_incoming_path next_image_tmppath
+  local next_image next_image_incoming_path next_image_incoming_tmppath \
+        next_image_path next_image_tmppath
   next_image=$1
-  next_image_incoming_path=$2
+  next_image_incoming_tmppath=$2
 
-  check_checksum "$next_image" "$next_image_incoming_path" image_checksum \
+  check_checksum "$next_image" "$next_image_incoming_tmppath" image_checksum \
     || return 1
 
-  next_image_tmppath="${images_dir}/${next_image}.tmp"
-  sync                                                    || return 1
-  chown root:root "$next_image_incoming_path"             || return 1
-  ln -f "$next_image_incoming_path" "$next_image_tmppath" || return 1
-  mv "$next_image_tmppath" "${images_dir}/${next_image}"  || return 1
-  sync                                                    || return 1
+  next_image_incoming_path="${incoming_images_dir}/${next_image}"
+  next_image_path="${images_dir}/${next_image}"
+  next_image_tmppath="${next_image_path}.tmp"
 
-  log notice "new ltsp image $next_image has been put into its place"
+  if ! sync; then
+    log err 'failed to run sync before putting image into use'
+    return 1
+  fi
+  if ! chown root:root "$next_image_incoming_tmppath"; then
+    log err "failed to chown ${next_image_incoming_tmppath}"
+    return 1
+  fi
+  if ! mv "$next_image_incoming_tmppath" "$next_image_incoming_path"; then
+    log err "failed to move ${next_image_incoming_tmppath}"
+    return 1
+  fi
+  if ! ln -f "$next_image_incoming_path" "$next_image_tmppath"; then
+    log err "failed to hardlink ${next_image_incoming_path}"
+    return 1
+  fi
+  if ! mv "$next_image_tmppath" "$next_image_path"; then
+    log err "failed to movie ${next_image_tmppath} to ${next_image_path}"
+    return 1
+  fi
+  if ! sync; then
+    log err 'failed to run sync after putting image into use'
+    return 1
+  fi
+
+  log notice "new ltsp image ${next_image} has been put to use"
 }
 
 check_checksum() {
@@ -236,14 +259,14 @@ check_checksum() {
     return 1
   fi
 
-  if [ "$expected_checksum" = "$calculated_checksum" ]; then
-    log info "checksum for file $filename is okay"
-    return 0
-  else
+  if [ "$expected_checksum" != "$calculated_checksum" ]; then
     log err "file $filename failed checksum check, removing $actual_file_path"
     rm -f "$actual_file_path"
     return 1
   fi
+
+  log info "checksum for file $filename is okay"
+  return 0
 }
 
 sha512sum_with_progress() {
@@ -269,10 +292,11 @@ cleanup_previous_runs() {
                      "$images_dir" "$rdiffs_dir" "$incoming_images_dir")
   if [ -n "$old_sync_files" ]; then
     printf %s "$old_sync_files" \
-      | fgrep -vx "${images_dir}/${preserve_imagefile}"          \
-      | fgrep -vx "${incoming_images_dir}/${preserve_imagefile}" \
-      | fgrep -vx "${rdiffs_dir}/${preserve_rdifffile}"          \
-      | fgrep -vx "${rdiffs_dir}/${preserve_rdifffile}.tmp"      \
+      | fgrep -vx "${images_dir}/${preserve_imagefile}"              \
+      | fgrep -vx "${incoming_images_dir}/${preserve_imagefile}"     \
+      | fgrep -vx "${incoming_images_dir}/${preserve_imagefile}.tmp" \
+      | fgrep -vx "${rdiffs_dir}/${preserve_rdifffile}"              \
+      | fgrep -vx "${rdiffs_dir}/${preserve_rdifffile}.tmp"          \
       | xargs -r -d'\n' -L1 rm -f
   fi
 
