Startup openvpn-connection on bootserver install so that connection to ldapmaster can work even on mostly arbitrary networks.
This currently requires that either puavo-conf variable
"puavo.vpn.client.remote_servers" must be set in the image (or
boottime) to something correct, or the network must provide some
other path to ldapmaster.

diff --git a/parts/ltsp/puavo-install/puavo-install b/parts/ltsp/puavo-install/puavo-install
--- a/parts/ltsp/puavo-install/puavo-install
+++ b/parts/ltsp/puavo-install/puavo-install
@@ -98,6 +98,43 @@ ask_preseed() {
   done
 }
 
+bootserver_setup_ldapmaster_connection() {
+  echo 'Starting vpn connection'
+  service puavo-vpn-client-openvpn start || true
+  read ldapmaster < /etc/puavo/ldap/master
+  for i in $(seq 10); do
+    if host -W 5 "$ldapmaster" >/dev/null; then
+      return 0
+    fi
+    echo 'Waiting for ldapmaster to become available...'
+    sleep "$i"
+  done
+  return 1
+}
+
+bootserver_setup_state() {
+  if ! puavo-set-root-password; then
+    echo 'Could not setup root password for bootservers' >&2
+    return 1
+  fi
+
+  # this affects setup_krb5kdc and puavo-init-ds-slave
+  export PUAVO_BOOTSERVER_INSTALLATION=true
+
+  /etc/puavo-conf/scripts/setup_hostname
+  /etc/puavo-conf/scripts/setup_state_partition
+  /etc/puavo-conf/scripts/setup_slapd
+  /etc/puavo-conf/scripts/setup_krb5kdc
+
+  # puavo-init-ds-slave needs network connection to ldapmaster
+  if ! bootserver_setup_ldapmaster_connection; then
+    echo 'No connection to ldapmaster, can not initialize ldap' >&2
+    return 1
+  fi
+
+  puavo-init-ds-slave
+}
+
 do_preinstall() {
   puavo_install_hosttype=$1
   puavo_preseed_setup_filesystems_args=$2
@@ -284,19 +321,7 @@ setup_state() {
   sync
 
   if [ "$puavo_hosttype" = 'bootserver' ]; then
-    if ! puavo-set-root-password; then
-      echo 'Could not setup root password for bootservers' >&2
-      return 1
-    fi
-
-    # this affects setup_krb5kdc and puavo-init-ds-slave
-    export PUAVO_BOOTSERVER_INSTALLATION=true
-
-    /etc/puavo-conf/scripts/setup_hostname
-    /etc/puavo-conf/scripts/setup_state_partition
-    /etc/puavo-conf/scripts/setup_slapd
-    /etc/puavo-conf/scripts/setup_krb5kdc
-    puavo-init-ds-slave
+    bootserver_setup_state
   fi
 
   return 0
