puavo-reset-windows: support Finnish installers

diff --git a/parts/ltsp/puavo-install/puavo-reset-windows b/parts/ltsp/puavo-install/puavo-reset-windows
--- a/parts/ltsp/puavo-install/puavo-reset-windows
+++ b/parts/ltsp/puavo-install/puavo-reset-windows
@@ -84,6 +84,56 @@ print0_win_primary_partition_devpaths()
     }
 }
 
+print0_win_language_tag()
+{
+    local win_language_id \
+          win_language_tag \
+          win_primary_partition_devpath
+
+    win_primary_partition_devpath=$1
+    shift
+
+    ntfscat "${win_primary_partition_devpath}" 'Windows/System32/config/SYSTEM' >system_hive || {
+        logerr "Failed to get SYSTEM hive from '${win_primary_partition_devpath}'."
+        return 1
+    }
+
+    win_language_id=$(hivexget system_hive 'ControlSet001\Control\Nls\Language' \
+                          | sed -r -n 's/"InstallLanguage"="([0-9A-Fa-f]{4})"$/\1/p' \
+                          | tr '[:upper:]' '[:lower:]') || {
+        logerr "Failed to parse InstallLanguage from SYSTEM hive of '${win_primary_partition_devpath}'."
+        return 1
+    }
+
+    ## https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-LCID/%5bMS-LCID%5d.pdf
+    case "${win_language_id}" in
+        '0407')
+            win_language_tag='de-DE'
+            ;;
+        '0409')
+            win_language_tag='en-US'
+            ;;
+        '040b')
+            win_language_tag='fi-FI'
+            ;;
+        '041d')
+            win_language_tag='sv-SE'
+            ;;
+        '0419')
+            win_language_tag='ru-RU'
+            ;;
+        '0422')
+            win_language_tag='uk-UA'
+            ;;
+        *)
+            logerr "Unsupported language ID '${win_language_id}'"
+            return 1
+            ;;
+    esac
+
+    printf '%s' "${win_language_tag}"
+}
+
 print0_win_product_name()
 {
     local win_build_number \
@@ -156,17 +206,31 @@ print0_wim_image_index()
 print0_win_iso_file_name()
 {
     local win_iso_file_name \
+          win_iso_file_name_suffix \
+          win_language_tag \
           win_product_name
 
     win_product_name=$1
     shift
 
+    win_language_tag=$1
+    shift
+
+    case "${win_language_tag}" in
+        'fi-FI')
+            win_iso_file_name_suffix='_fi'
+            ;;
+        *)
+            win_iso_file_name_suffix=''
+            ;;
+    esac
+
     case "${win_product_name}" in
         'Windows 10 '*)
-            win_iso_file_name='win10x64.iso'
+            win_iso_file_name="win10x64${win_iso_file_name_suffix}.iso"
             ;;
         'Windows 11 '*)
-            win_iso_file_name='win11x64.iso'
+            win_iso_file_name="win11x64${win_iso_file_name_suffix}.iso"
             ;;
         *)
             logerr "Unexpected Windows product name '${win_product_name}'"
@@ -323,24 +387,28 @@ reset_win()
     local wim_file_path \
           win_iso_file_name \
           win_iso_mountpoint \
+          win_language_tag \
           win_primary_partition_devpath \
           win_product_name
 
     win_product_name=$1
     shift
 
+    win_language_tag=$1
+    shift
+
     win_primary_partition_devpath=$1
     shift
 
-    loginfo "Reseting '${win_product_name}' on '${win_primary_partition_devpath}'..."
+    loginfo "Reseting '${win_product_name} (${win_language_tag})' on '${win_primary_partition_devpath}'..."
 
-    win_iso_file_name=$(print0_win_iso_file_name "${win_product_name}") || {
-        logerr "Failed to get ISO file name for '${win_product_name}'"
+    win_iso_file_name=$(print0_win_iso_file_name "${win_product_name}" "${win_language_tag}") || {
+        logerr "Failed to get ISO file name for '${win_product_name} (${win_language_tag})'"
         return 1
     }
 
     fetch_win_iso "${win_iso_file_name}" || {
-        logerr "Failed to fetch ISO file for '${win_product_name}'."
+        logerr "Failed to fetch ISO file for '${win_product_name} (${win_language_tag})'."
         return 1
     }
 
@@ -390,7 +458,7 @@ reset_win()
         loginfo "Wiped all unused data from '${win_primary_partition_devpath}'."
     fi
 
-    loginfo "Reset '${win_product_name}' on '${win_primary_partition_devpath}' to factory settings successfully."
+    loginfo "Reset '${win_product_name} (${win_language_tag})' on '${win_primary_partition_devpath}' to factory settings successfully."
 
     return 0
 }
@@ -399,6 +467,7 @@ reset_win()
 reset_all_wins()
 {
     local returnval \
+          win_language_tag \
           win_product_name
 
     returnval=0
@@ -410,7 +479,13 @@ reset_all_wins()
             continue
         }
 
-        loginfo "Detected '${win_product_name}' on '${win_primary_partition_devpath}'."
+        win_language_tag=$(print0_win_language_tag "${win_primary_partition_devpath}") || {
+            logerr "Failed to get the language tag of Windows on '${win_primary_partition_devpath}'."
+            returnval=1
+            continue
+        }
+
+        loginfo "Detected '${win_product_name} (${win_language_tag})' on '${win_primary_partition_devpath}'."
 
         case "${win_product_name}" in
             'Windows 10 Home' | 'Windows 10 Pro' | 'Windows 11 Home' | 'Windows 11 Pro')
@@ -423,19 +498,19 @@ reset_all_wins()
         esac
 
         $use_force || dialog --no-lines --clear --erase-on-exit --defaultno --yesno \
-               "Reset '${win_product_name}' on '${win_primary_partition_devpath}'?" 5 100 || {
-            loginfo "Skipping '${win_product_name}' on '${win_primary_partition_devpath}'."
+               "Reset '${win_product_name} (${win_language_tag})' on '${win_primary_partition_devpath}'?" 5 100 || {
+            loginfo "Skipping '${win_product_name} (${win_language_tag})' on '${win_primary_partition_devpath}'."
             continue
         }
 
         $use_force || dialog --no-lines --clear --erase-on-exit --defaultno --yesno \
                "All data will be lost on '${win_primary_partition_devpath}'! Are you really sure you want to proceed?" 5 100 || {
-            loginfo "Skipping '${win_product_name}' on '${win_primary_partition_devpath}'."
+            loginfo "Skipping '${win_product_name} (${win_language_tag})' on '${win_primary_partition_devpath}'."
             continue
         }
 
-        reset_win "${win_product_name}" "${win_primary_partition_devpath}" || {
-            logerr "Failed to reset '${win_product_name}' on '${win_primary_partition_devpath}'."
+        reset_win "${win_product_name}" "${win_language_tag}" "${win_primary_partition_devpath}" || {
+            logerr "Failed to reset '${win_product_name} (${win_language_tag})' on '${win_primary_partition_devpath}'."
             returnval=1
             continue
         }
