puavo-boot: Replace terms "cmdline/command_line/kernel argument/kernel parameter" in UKI code to commandline
Allow command-line term in comments and program output.

diff --git a/parts/ltsp/puavo-install/puavo-install-and-update-uki-image b/parts/ltsp/puavo-install/puavo-install-and-update-uki-image
--- a/parts/ltsp/puavo-install/puavo-install-and-update-uki-image
+++ b/parts/ltsp/puavo-install/puavo-install-and-update-uki-image
@@ -104,8 +104,8 @@ install_uki_to_efi() {
     return 1
   }
 
-  puavo-update-uki-command-line "$image_mountpoint" "$images_dir" "$UKI_ROOT" "$hosttype" || {
-    echo "error: failed to update UKI command line" >&2
+  puavo-update-uki-commandline "$image_mountpoint" "$images_dir" "$UKI_ROOT" "$hosttype" || {
+    echo "error: failed to update UKI command-line" >&2
     umount /boot/efi
     return 1
   }
diff --git a/parts/ltsp/puavo-install/puavo-update-uki-commandline b/parts/ltsp/puavo-install/puavo-update-uki-commandline
--- a/parts/ltsp/puavo-install/puavo-update-uki-commandline
+++ b/parts/ltsp/puavo-install/puavo-update-uki-commandline
@@ -26,7 +26,7 @@ if [ ! -d "$uki_root" ]; then
   exit 1
 fi
 
-install_command_line() {
+install_commandline() {
   local uki="$1"
   local destination="$2"
   local image_name_no_suffix="$3"
@@ -40,9 +40,9 @@ install_command_line() {
     return 1
   fi
 
-  # Install the host type specific command line
+  # Install the host type specific command-line
   cp "${boot_directory}/addons/${hosttype}.addon.efi" \
-     "${extra_directory}/cmdline.addon.efi"
+     "${extra_directory}/commandline.addon.efi"
 
   # Install device-specific addons
   if [ -d "${addons_dir}" ]; then
@@ -59,8 +59,8 @@ fi
 image_name_no_suffix=${image_name%.img}
 
 for uki in "$boot_directory"/*.uki.efi; do
-  install_command_line "$uki" "$uki_root" "$image_name_no_suffix" || {
-    echo "error: failed to install command line for UKI '$uki'" >&2
+  install_commandline "$uki" "$uki_root" "$image_name_no_suffix" || {
+    echo "error: failed to install command-line for UKI '$uki'" >&2
     exit 1
   }
 done
