Add disk space checks to UKI install script

diff --git a/parts/ltsp/puavo-install/puavo-install-and-update-uki-image b/parts/ltsp/puavo-install/puavo-install-and-update-uki-image
--- a/parts/ltsp/puavo-install/puavo-install-and-update-uki-image
+++ b/parts/ltsp/puavo-install/puavo-install-and-update-uki-image
@@ -27,20 +27,56 @@ trap cleanup EXIT
 
 mount -o ro "$install_image" "$image_mountpoint"
 
-install_uki_to_efi() {
-  local diskdev uki_root
-  uki_root="/boot/efi/EFI/debian"
+find_efi_device_path() {
+  local diskdev="$1"
 
-  diskdev="$1"
-
-  efi_devpath=$(lsblk -n -l -o PATH,PARTTYPE "$diskdev" \
+  echo $(lsblk -n -l -o PATH,PARTTYPE "$diskdev" \
     | awk '$2 == "c12a7328-f81f-11d2-ba4b-00a0c93ec93b" { print $1; exit(0) }')
+}
+
+mount_disk_efi_partition() {
+  local diskdev="$1"
+
+  efi_devpath=$(find_efi_device_path "$diskdev")
   if [ -z "$efi_devpath" ]; then
     echo "Failed to find EFI partition in $diskdev" >&2
     return 1
   fi
 
   mount "$efi_devpath" /boot/efi
+}
+
+estimate_required_disk_space() {
+  local image_size required_disk_space safety_margin
+  required_disk_space=0
+
+  for uki in "$image_mountpoint"/boot/*.uki.efi; do
+    [ -e "$uki" ] || continue
+    image_size=$(stat -c %s "$uki")
+    required_disk_space=$((required_disk_space + image_size))
+  done
+
+  safety_margin=$((32 * 1024 * 1024)) # 32 MB
+  required_disk_space=$((required_disk_space + safety_margin))
+
+  echo "$required_disk_space"
+}
+
+has_enough_disk_space() {
+  local diskdev="$1"
+  local required_space="$2"
+
+  mount_disk_efi_partition "$diskdev" || return 1
+
+  local available_space=$(df --output=avail -B1 /boot/efi | tail -n1)
+  [ "$available_space" -ge "$required_space" ]
+}
+
+install_uki_to_efi() {
+  local diskdev uki_root
+  uki_root="/boot/efi/EFI/debian"
+
+  mount_disk_efi_partition "$diskdev" || return 1
 
   if [ ! -d "$uki_root" ]; then
     echo "Device $diskdev does not have a valid EFI partition" >&2
@@ -65,6 +101,26 @@ install_uki_to_efi() {
 
 # Identify boot disks and install UKI files to their EFI partitions
 boot_disks=$(/usr/lib/puavo-ltsp-install/puavo-get-boot-disks "$install_mountpoint")
+
+if [ -z "$boot_disks" ]; then
+  echo "Failed to find boot disks" >&2
+  exit 1
+fi
+
+# Before installing, verify that the boot partitions have enough space
+required_space=$(estimate_required_disk_space "$install_image")
+
+if [ -z "$required_space" ]; then
+  echo "Failed to estimate required disk space" >&2
+  exit 1
+fi
+
+for diskdev in $boot_disks; do
+  has_enough_disk_space "$diskdev" "$required_space" || {
+    echo "Disk $diskdev does not have enough space" >&2
+    exit 1
+  }
+done
 
 for diskdev in $boot_disks; do
   echo "installing UKI files to boot device $diskdev"
