Use more subroutines in puavo-install, and try to put some sense into it (this commit is not tested, probably broken in some ways).

diff --git a/parts/ltsp/puavo-install/puavo-install b/parts/ltsp/puavo-install/puavo-install
--- a/parts/ltsp/puavo-install/puavo-install
+++ b/parts/ltsp/puavo-install/puavo-install
@@ -19,19 +19,19 @@ ask_preseed() {
 
     # Ensure the value is a valid integer.
     case "${preseed_nr}" in
-        ''|*[!0-9]*)
-            echo "E: invalid preseed number" >&2
-            continue
-            ;;
-        *)
-            ;;
+      ''|*[!0-9]*)
+        echo "E: invalid preseed number" >&2
+        continue
+        ;;
+      *)
+        ;;
     esac
 
     # Ensure the integer has a valid value.
     if [ 0 -gt "${preseed_nr}" \
            -o "${preseed_nr}" -gt "${preseed_count}" ]; then
-        echo "E: invalid preseed number" >&2
-        continue
+      echo "E: invalid preseed number" >&2
+      continue
     fi
 
     # Preseed 0 always means no preseeding at all.
@@ -58,120 +58,210 @@ ask_preseed() {
   done
 }
 
-mkdir -p /run/puavo
-if [ ! -e /run/puavo/install_hosttype ]; then
-  cp /etc/puavo/hosttype /run/puavo/install_hosttype
-fi
+do_umounts() {
+  puavo_install_hosttype=$1
+  hosttype=$2
 
-# This might be "unregistered" or "diskinstaller" (which is unregistered in a
-# different way), so we read this now and use later.
-puavo_install_hosttype="$(cat /run/puavo/install_hosttype)"
-
-if ! [    "$puavo_install_hosttype" = 'diskinstaller' \
-       -o "$puavo_install_hosttype" = 'preinstalled'  \
-       -o "$puavo_install_hosttype" = 'unregistered' ]; then
-  echo "'$puavo_install_hosttype' is not a supported hosttype for" \
-       "installation" >&2
-  exit 1
-fi
-
-accepted_devicetypes='fatclient,laptop,ltspserver,thinclient,wirelessaccesspoint'
-
-if [ "$puavo_install_hosttype" = 'preinstalled' ]; then
-  preinstalled_hosttype=$(cat /images/puavo_preinstalled 2>/dev/null || true)
-  if [ -z "$preinstalled_hosttype" ]; then
-    echo 'Hosttype is preinstalled, but could not determine its type' >&2
-    exit 1
+  if [ "$puavo_install_hosttype" = 'preinstalled' ]; then
+    umount /state /images
+    return 0
   fi
-  accepted_devicetypes=$preinstalled_hosttype
-fi
 
-puavo_preseed_register_args=
-puavo_preseed_setup_filesystems_args=
+  case "$hosttype" in
+    laptop)              umount /state /images /imageoverlays /tmp /home ;;
+    ltspserver)          umount /state
+    wirelessaccesspoint) umount /state /images /imageoverlays /tmp       ;;
+  esac
+}
+
+get_accepted_hosttypes() {
+  puavo_install_hosttype=$1
+
+  if [ "$puavo_install_hosttype" = 'preinstalled' ]; then
+    get_preinstalled_hosttype
+    return 0
+  fi
+
+  echo 'fatclient,laptop,ltspserver,thinclient,wirelessaccesspoint'
+}
+
+get_install_hosttype() {
+  mkdir -p /run/puavo
+  if [ ! -e /run/puavo/install_hosttype ]; then
+    cp /etc/puavo/hosttype /run/puavo/install_hosttype
+  fi
+
+  puavo_install_hosttype="$(cat /run/puavo/install_hosttype)"
+
+  case "$puavo_install_hosttype" in
+    diskinstaller|preinstalled|unregistered)
+      echo "$puavo_install_hosttype"
+      ;;
+    *)
+      echo "'${puavo_install_hosttype}' is not a supported hosttype for" \
+	   "installation" >&2
+      return 1
+      ;;
+  esac
+}
+
+get_preinstalled_hosttype() {
+  preinstalled_hosttype=$(cat /images/puavo_preinstalled 2>/dev/null || true)
+  case "$preinstalled_hosttype" in
+    laptop|wirelessaccesspoint)
+      echo "$preinstalled_hosttype"
+      ;;
+    *)
+      echo 'Host is preinstalled, but does not have a supported hosttype' >&2
+      return 1
+      ;;
+  esac
+}
+
+install_grub() {
+  puavo_install_hosttype=$1
+
+  [ "$puavo_install_hosttype" = 'preinstalled' ] && return 0
+
+  echo -n 'Doing grub installation: '
+  puavo-install-grub
+  sync
+}
+
+install_image() {
+  puavo_install_hosttype=$1
+
+  [ "$puavo_install_hosttype" = 'preinstalled' ] && return 0
+
+  ltspimage_name=$(cat /etc/ltsp/this_ltspimage_name 2>/dev/null || true)
+  if [ -z "$ltspimage_name" ]; then
+    echo 'Could not determine the current ltsp image' >&2
+    return 1
+  fi
+
+  case "$puavo_install_hosttype" in
+    diskinstaller)
+      puavo-install-and-update-ltspimages                      \
+        --install-from-file "/installimages/${ltspimage_name}" \
+        "$ltspimage_name"
+      ;;
+    unregistered)
+      puavo-install-and-update-ltspimages --install-from-nbd /dev/nbd0 \
+                                          "$ltspimage_name"
+      ;;
+    *)
+      echo 'I do not know from where to install an ltsp image' >&2
+      return 1
+      ;;
+  esac
+
+  sync
+}
+
+register() {
+  puavo_install_hosttype=$1
+  accepted_hosttypes=$2
+  puavo_preseed_register_args=$3
+
+  if [ "$puavo_install_hosttype" = 'preinstalled' ]; then
+    get_preinstalled_hosttype
+    return 0
+  fi
+
+  puavo-register --accepted-devicetypes "$accepted_hosttypes" \
+                 ${puavo_preseed_register_args}
+
+  cat /etc/puavo/hosttype
+}
+
+setup_installation_filesystems() {
+  puavo_install_hosttype=$1
+  puavo_preseed_setup_filesystems_args=$2
+
+  if [ "$puavo_install_hosttype" != 'preinstalled' ]; then
+    puavo-setup-filesystems ${puavo_preseed_setup_filesystems_args}
+  else
+    mkdir -p /state
+    mount /dev/mapper/puavo-state /state
+  fi
+}
+
+setup_state_contents() {
+  mkdir -p /state/etc
+  cp -aT /etc/puavo /state/etc/puavo
+  sync
+}
+
+update_configuration() {
+  hosttype=$1
+
+  echo "Updating $hosttype configuration..."
+  if /usr/lib/puavo-ltsp-install/update-configuration; then
+    echo "  ... $hosttype configuration updated."
+    if /usr/lib/puavo-ltsp-install/update-images false false; then
+      echo "  ... image updated."
+    else
+      echo "  ... image update failed (may update it later)."
+    fi
+  else
+    echo "  ... a problem occurred (updating configuration later)."
+  fi
+
+  # XXX exactly why is this necessary here? (it is? ... but I have to explain)
+  puavo-install-grub --hosttype "$hosttype" --only-update-config
+
+  sync
+}
+
+
+# main
+
+puavo_install_hosttype=$(get_install_hosttype)
+accepted_hosttypes=$(get_accepted_hosttypes "$puavo_install_hosttype")
 
 # ask_preseed fills in $puavo_preseed_register_args and
 # $puavo_preseed_setup_filesystems_args
+puavo_preseed_register_args=
+puavo_preseed_setup_filesystems_args=
 ask_preseed
 
-puavo-register --accepted-devicetypes "$accepted_devicetypes" \
-               ${puavo_preseed_register_args}
-
-hosttype="$(cat /etc/puavo/hosttype)"
+hosttype=$(register "$puavo_install_hosttype"       \
+                    "$accepted_hosttypes"           \
+                    "$puavo_preseed_register_args")
 
 case "$hosttype" in
   laptop|wirelessaccesspoint)
-    if [ "$puavo_install_hosttype" != 'preinstalled' ]; then
-      puavo-setup-filesystems ${puavo_preseed_setup_filesystems_args}
-    else
-      mkdir -p /state
-      mount /dev/mapper/puavo-state /state
-    fi
+    setup_installation_filesystems "$puavo_install_hosttype"               \
+                                   "$puavo_preseed_setup_filesystems_args"
+    setup_state_contents
 
-    mkdir -p /state/etc
-    cp -aT /etc/puavo /state/etc/puavo
+    # Grub needs to be installed before images, because grub
+    # configuration is updated during image installation by
+    # puavo-image-preinst.
+    install_grub  "$puavo_install_hosttype"
+    install_image "$puavo_install_hosttype"
 
-    if [ "$puavo_install_hosttype" != 'preinstalled' ]; then
-      # Grub needs to be installed before images, because grub
-      # configuration is updated during image installation by
-      # puavo-image-preinst.
-      echo -n "Doing grub installation: "
-      puavo-install-grub
-      sync
+    update_configuration "$hosttype"
 
-      # install from nbd, the ltsp image must contain its name in this path
-      ltspimage_name=$(cat /etc/ltsp/this_ltspimage_name)
-
-      case "$puavo_install_hosttype" in
-	diskinstaller)
-	  puavo-install-and-update-ltspimages                      \
-	    --install-from-file "/installimages/${ltspimage_name}" \
-	    "$ltspimage_name"
-	  ;;
-	*)
-	  puavo-install-and-update-ltspimages --install-from-nbd /dev/nbd0 \
-					      "$ltspimage_name"
-	  ;;
-      esac
-      sync
-    fi
-
-    echo "Updating $hosttype configuration..."
-    if /usr/lib/puavo-ltsp-install/update-configuration; then
-      echo "  ... $hosttype configuration updated."
-      if /usr/lib/puavo-ltsp-install/update-images false false; then
-        echo "  ... image updated."
-      fi
-    else
-      echo "  ... a problem occurred (updating configuration later)."
-    fi
-    sync
+    # From now on the host will boot as a fully installed host.
 
     if [ "$puavo_install_hosttype" = 'preinstalled' ]; then
       # The grub configuration must include the new hosttype and not
-      # "preinstalled".  From now on the host will boot as a fully installed
-      # host.
-      puavo-install-grub --only-update-config
+      # "preinstalled".  Do this only after configuration update (may fail).
       rm -f /images/puavo_preinstalled
     fi
 
-    if [ "$puavo_install_hosttype" != 'preinstalled' ]; then
-      case "$hosttype" in
-        laptop)              umount /state /images /imageoverlays /tmp /home ;;
-        wirelessaccesspoint) umount /state /images /imageoverlays /tmp       ;;
-      esac
-    else
-      umount /state /images
-    fi
+    do_umounts "$puavo_install_hosttype" "$hosttype"
 
-    echo "Press ENTER to reboot"
+    # XXX how does this script know that something is going to reboot this
+    # XXX host after this?
+    echo 'Press ENTER to reboot'
     read answer
     ;;
   ltspserver)
-    puavo-setup-filesystems ${puavo_preseed_setup_filesystems_args}
-    mkdir -p /state/etc
-    cp -a /etc/puavo /state/etc
-
-    sync
-    umount /state
+    setup_installation_filesystems "$puavo_install_hosttype"               \
+                                   "$puavo_preseed_setup_filesystems_args"
+    setup_state_contents
+    do_umounts "$puavo_install_hosttype" "$hosttype"
     ;;
 esac
