puavo-manage-efi: [DRAFT] add support for installing Windows boot manager

diff --git a/parts/ltsp/puavo-install/puavo-manage-efi b/parts/ltsp/puavo-install/puavo-manage-efi
--- a/parts/ltsp/puavo-install/puavo-manage-efi
+++ b/parts/ltsp/puavo-install/puavo-manage-efi
@@ -8,6 +8,8 @@ g_no_efi_is_ok=false
 g_cmd=
 g_umount_on_exit=
 PID_FILE=/run/puavo-manage-efi.pid # Locks this file to ensure only one puavo-manage-efi is running
+ESP_WINDOWS_DIR='/boot/efi/EFI/Microsoft'
+
 
 log() {
   logger -t puavo-manage-efi -p "user.${1}" "$2" || true
@@ -41,6 +43,88 @@ get_windows_boot_entries_to_change() {
   '
 }
 
+get_esp_devpaths()
+{
+  lsblk -n -l -o PATH,PARTTYPE | awk '$2 == "c12a7328-f81f-11d2-ba4b-00a0c93ec93b" {print $1}'
+}
+
+get_one_esp_devpath()
+{
+  local esp_devpath esp_devpath_count
+
+  esp_devpath_count=0
+
+  while read -r esp_devpath; do
+    esp_devpath_count=$((esp_devpath_count + 1))
+  done < <(get_esp_devpaths) || {
+    log err 'failed to find ESP'
+    return 1
+  }
+
+  if [ ${esp_devpath_count} -eq 0 ]; then
+    log err 'failed to find ESP'
+    return 1
+  elif [ ${esp_devpath_count} -gt 1 ]; then
+    log err 'found multiple ESPs'
+    return 1
+  fi
+
+  echo -n "${esp_devpath}"
+}
+
+get_esp_partnum()
+{
+  local esp_devpath
+
+  esp_devpath="$1"
+  shift
+
+  stat --format %Lr "${esp_devpath}"
+}
+
+get_esp_disk()
+{
+  local esp_devpath disk_devpath
+
+  esp_devpath=$1
+  shift
+
+  disk_devpath=$(lsblk -p -J -s "${esp_devpath}" | jq -r '.blockdevices[0].children[0] | select(.type == "disk").name') || {
+    log err 'failed to find ESP disk'
+    return 1
+  }
+
+  if [ -z "${disk_devpath}" ]; then
+    log err 'failed to find ESP disk (jq empty output)'
+    return 1
+  fi
+
+  echo -n "${disk_devpath}"
+}
+
+efibootmgr_windows_create() {
+  local esp_devpath esp_disk esp_partnum
+
+  log notice 'creating new Windows boot entry'
+
+  esp_devpath=$(get_one_esp_devpath) || {
+    log err 'failed to find exactly one ESP'
+    return 1
+  }
+
+  esp_disk=$(get_esp_disk "${esp_devpath}") || {
+    log err 'failed to get the disk of ESP'
+    return 1
+  }
+
+  esp_partnum=$(get_esp_partnum "${esp_devpath}") || {
+    log err 'failed to get the partition number of ESP'
+    return 1
+  }
+
+  efibootmgr -c -L "Windows Boot Manager" -l "\EFI\Microsoft\Boot\bootmgfw.efi" -d "${esp_disk}" -p "${esp_partnum}"
+}
+
 efibootmgr_windows() {
   local boot_entry efibootmgr_flag enable_or_disable_msg
 
@@ -48,8 +132,16 @@ efibootmgr_windows() {
   case "$efibootmgr_flag" in
     -A) enable_or_disable_msg='disabling' ;;
     -a) enable_or_disable_msg='enabling'  ;;
+    -c)
+      efibootmgr_windows_create || {
+        log err 'failed to create Windows boot entry'
+        return 1
+      }
+      return 0
+      ;;
      *) return 1;;
   esac
+
 
   for boot_entry in $(get_windows_boot_entries_to_change "$efibootmgr_flag"); do
     log notice "${enable_or_disable_msg} Windows boot entry ${boot_entry}"
@@ -90,14 +182,14 @@ esp_break_windows() {
 
   if [ -e "$defused_windows_file" ]; then
     # nothing to do
-    if [ -d '/boot/efi/EFI/Microsoft' ]; then
-      log info "cleaning up /boot/efi/EFI/Microsoft that should not exist"
-      rm -rf '/boot/efi/EFI/Microsoft' || true
+    if [ -d "${ESP_WINDOWS_DIR}" ]; then
+      log info "cleaning up ${ESP_WINDOWS_DIR} that should not exist"
+      rm -rf "${ESP_WINDOWS_DIR}" || true
     fi
     return 0
   fi
 
-  if [ ! -d '/boot/efi/EFI/Microsoft' ]; then
+  if [ ! -d "${ESP_WINDOWS_DIR}" ]; then
     # not doing/logging anything, perhaps we do not have Windows installed
     # and that should be normal
     return 0
@@ -114,14 +206,59 @@ esp_break_windows() {
     log err 'failed to defuse Windows (mv error)'
     return 1
   fi
-  if ! rm -rf '/boot/efi/EFI/Microsoft'; then
-    log warning "error cleaning up /boot/efi/EFI/Microsoft"
+  if ! rm -rf "${ESP_WINDOWS_DIR}"; then
+    log warning "error cleaning up ${ESP_WINDOWS_DIR}"
     return 1
   fi
 
   log notice 'Windows defused'
 
   return 0
+}
+
+esp_install_windows() {
+  local defused_windows_file tmp_microsoft_dir windows_dir
+
+  defused_windows_file='/boot/efi/EFI/Puavo-defused-Windows.tar.gz'
+  tmp_windows_dir="${ESP_WINDOWS_DIR}.tmp"
+  rm -rf "${tmp_windows_dir}"
+
+  if [ -e "${defused_windows_file}" ]; then
+    log err 'ESP already contains a defused Windows'
+    return 1
+  fi
+
+  if [ -e "${ESP_WINDOWS_DIR}" ]; then
+    log err 'ESP already contains Windows'
+    return 1
+  fi
+
+  log info 'installing Windows bootloader...'
+  mkdir "${tmp_windows_dir}" || {
+    log err 'failed to install Windows bootloader (mkdir)'
+    return 1
+  }
+  puavo-reset-windows --mode install-boot-dir "${tmp_windows_dir}" || {
+    log err 'failed to install Windows bootloader (puavo-reset-windows)'
+    rm -rf "${tmp_windows_dir}" || true
+    return 1
+  }
+  mv -n -T "${tmp_windows_dir}" "${ESP_WINDOWS_DIR}" || {
+    log err 'failed to install Windows bootloader (mv)'
+    rm -rf "${tmp_windows_dir}" || true
+    return 1
+  }
+  if [ -d "${tmp_windows_dir}" ]; then
+    # mv failed because the source dir still exists
+    log err 'failed to install Windows bootloader (mv)'
+    rm -rf "${ESP_WINDOWS_DIR}" || true
+    rm -rf "${tmp_windows_dir}" || true
+    return 1
+  fi
+
+  sync || true
+
+  log info 'Windows bootloader installed'
 }
 
 esp_fix_windows() {
@@ -139,7 +276,7 @@ esp_fix_windows() {
   log info 'repriming Windows...'
   tar -C '/boot/efi/EFI' -z -x -f "$defused_windows_file" || {
     log err 'error repriming Windows (tar error)'
-    rm -rf '/boot/efi/EFI/Microsoft' || true
+    rm -rf "${ESP_WINDOWS_DIR}" || true
     return 1
   }
   sync || true
@@ -160,6 +297,11 @@ efi_disable_windows() {
 efi_enable_windows() {
   esp_fix_windows || return 1
   efibootmgr_windows -a
+}
+
+efi_install_windows() {
+  esp_install_windows || return 1
+  efibootmgr_windows -c
 }
 
 has_efi() {
@@ -195,6 +337,7 @@ while [ $# -gt 0 ]; do
         echo "Commands:"
         echo "    disable-windows              disable Windows"
         echo "    enable-windows               enable Windows"
+        echo "    install-windows              install Windows boot manager to ESP"
         echo
         echo "Options:"
         echo "    --no-efi-is-ok               exit with status 0 if the system does not use EFI"
@@ -260,6 +403,9 @@ case "${g_cmd}" in
     ;;
   disable-windows)
     efi_disable_windows
+    ;;
+  install-windows)
+    efi_install_windows
     ;;
   *)
     usage_error "invalid command '${g_cmd}'"
