Add switch --add-efi-label to puavo-install-grub.
This can be used to add an EFI label in case we know it
might be missing from host.  Previously we had code
to do this, but it was missing an argument -d so that
it worked only with /dev/sda.  As puavo-install-grub knows
about boot devices (and normally sets up the EFI label
as part of grub-install), it makes sense to do this there.

diff --git a/parts/ltsp/puavo-install/puavo-install-grub b/parts/ltsp/puavo-install/puavo-install-grub
--- a/parts/ltsp/puavo-install/puavo-install-grub
+++ b/parts/ltsp/puavo-install/puavo-install-grub
@@ -407,18 +407,20 @@ exitstatus=0
 
 hosttype=$(cat /etc/puavo/hosttype 2>/dev/null || true)
 images_dir=/images
+add_efi_label=false
 only_update_config=false
 vgname=puavo
 
-if ! args=$(getopt -n "$0" -o +                                          \
-                   -l 'hosttype:,images-dir:,only-update-config,vgname:' \
-                   -- "$@"); then
+if ! args=$(getopt -n "$0" -o + \
+              -l 'add-efi-label,hosttype:,images-dir:,only-update-config,vgname:' \
+              -- "$@"); then
   usage
 fi
 
 eval "set -- $args"
 while [ $# -ne 0 ]; do
   case "$1" in
+    --add-efi-label)      add_efi_label=true;      shift        ;;
     --hosttype)           hosttype=$2;             shift; shift ;;
     --images-dir)         images_dir=$2;           shift; shift ;;
     --only-update-config) only_update_config=true; shift        ;;
@@ -555,9 +557,7 @@ install_efi_grub() {
 
 grub_install_done=false
 
-if $only_update_config; then
-  log info 'only updating Grub configuration'
-else
+if ! $only_update_config; then
   for grubdev in $grub_target_devices; do
     log info "installing grub to ${grubdev}"
 
@@ -605,6 +605,17 @@ else
     mv "${boot_dir}/grub/version.tmp" "${boot_dir}/grub/version"
     log notice "Grub version ${new_grub_version} has been installed to: $(printf %s "$grub_target_devices")"
   fi
+fi
+
+if $add_efi_label && [ -d /sys/firmware/efi ]; then
+  for grubdev in $grub_target_devices; do
+    log notice "adding an EFI label to device ${grubdev}"
+    if ! efibootmgr -c -d "$grubdev" -L debian -l '\EFI\debian\grubx64.efi' \
+      > /dev/null; then
+        log err "error when adding an EFI label to device ${grubdev}"
+        exitstatus=1
+    fi
+  done
 fi
 
 grub_cfg_path="${boot_dir}/grub/grub.cfg"
