When resetting laptops, if imageoverlays partition exists (some very old Puavo installations did not have this), mount it and clean it up during reset.

diff --git a/parts/ltsp/puavo-install/puavo-reset-laptop-to-factory-defaults b/parts/ltsp/puavo-install/puavo-reset-laptop-to-factory-defaults
--- a/parts/ltsp/puavo-install/puavo-reset-laptop-to-factory-defaults
+++ b/parts/ltsp/puavo-install/puavo-reset-laptop-to-factory-defaults
@@ -154,6 +154,15 @@ EOF
   esac
 done
 
+if [ -b /dev/mapper/puavo-imageoverlays ]; then
+  if ! mountpoint -q /imageoverlays; then
+    if ! mount /dev/mapper/puavo-imageoverlays /imageoverlays; then
+      echo 'could not mount imageoverlays' >&2
+      exit 1
+    fi
+  fi
+fi
+
 cd /
 
 # Remove primary user (so that we will send this information
