In puavo-reset-laptop-to-factory-defaults, continue despite of errors, but return an error code in the end if errors occurred.

diff --git a/parts/ltsp/puavo-install/puavo-reset-laptop-to-factory-defaults b/parts/ltsp/puavo-install/puavo-reset-laptop-to-factory-defaults
--- a/parts/ltsp/puavo-install/puavo-reset-laptop-to-factory-defaults
+++ b/parts/ltsp/puavo-install/puavo-reset-laptop-to-factory-defaults
@@ -178,12 +178,14 @@ EOF
   esac
 done
 
+resetstatus=0
+
 if [ -b /dev/mapper/puavo-imageoverlays ]; then
   if ! mountpoint -q /imageoverlays; then
     if ! { mkdir -p /imageoverlays \
              && mount /dev/mapper/puavo-imageoverlays /imageoverlays; }; then
       echo 'Could not mount imageoverlays' >&2
-      exit 1
+      resetstatus=1
     fi
   fi
 fi
@@ -192,46 +194,54 @@ cd /
 
 # Remove primary user (so that we will send this information
 # to Puavo through update-configuration).
-cat /dev/null > /state/etc/puavo/primary_user_override
+cat /dev/null > /state/etc/puavo/primary_user_override || resetstatus=1
 
 # we can speed up secure delete by not applying it to puavo-pkgs
-destroy_in_dir --force-insecure /images/puavo-pkg/ 'Removing all puavo-pkgs'
+destroy_in_dir --force-insecure /images/puavo-pkg/ 'Removing all puavo-pkgs' \
+  || resetstatus=1
 
-destroy_in_dir /home/ 'Cleaning up home directories'
+destroy_in_dir /home/ 'Cleaning up home directories' || resetstatus=1
 destroy_in_dir /state/etc/puavo/local/ \
-               'Removing local configurations (made by user)'
-destroy_in_dir /state/var/cache/ 'Cleaning up caches'
-destroy_in_dir /state/var/lib/   'Removing some system configurations'
+               'Removing local configurations (made by user)' || resetstatus=1
+destroy_in_dir /state/var/cache/ 'Cleaning up caches' || resetstatus=1
+destroy_in_dir /state/var/lib/   'Removing some system configurations' \
+  || resetstatus=1
 
 /usr/lib/puavo-ltsp-install/update-configuration 2>&1 \
   | pv -F '>>> Updating system configuration... %t' > /dev/null
 
 destroy_in_dir --force-insecure --preserve-etc-puavo /imageoverlays/ \
-               'Cleaning up most of /imageoverlays'
+               'Cleaning up most of /imageoverlays' || resetstatus=1
 destroy_in_dir /state/etc/NetworkManager/system-connections/ \
-               'Removing network manager connections'
+               'Removing network manager connections' || resetstatus=1
 
 reset_override_path='/state/etc/puavo/reset_override'
 if ! write_reset_override "$operation" "$reset_override_path"; then
   echo
   echo 'Error in writing reset override' >&2
   echo
-  exit 1
+  resetstatus=1
 fi
 
-if ! send_state_reset_to_puavo "$reset_override_path"; then
-  {
-    echo
-    echo 'Failed to sending reset information to Puavo.'
-    echo 'You may reboot this host, it tries to update the reset information'
-    echo 'later, but you may also remove it manually from the Puavo interface.'
-    echo
-  } >&2
-  exit 1
+if [ "$resetstatus" -eq 0 ] \
+  && ! send_state_reset_to_puavo "$reset_override_path"; then
+    {
+      echo
+      echo 'Failed to sending reset information to Puavo.  You may reboot'
+      echo 'this host, it tries to update the reset information later,'
+      echo 'but you may also remove it manually from the Puavo interface.'
+      echo
+    } >&2
+    resetstatus=1
 fi
 
 destroy_in_dir --force-insecure /imageoverlays/ \
-               'Cleaning up all of /imageoverlays'
+               'Cleaning up all of /imageoverlays' || resetstatus=1
+
+if [ "$resetstatus" -ne 0 ]; then
+  echo 'Errors in device reset' >&2
+  exit $resetstatus
+fi
 
 i=5
 echo
