Verify catalogue files with GPG in image updates.

diff --git a/parts/ltsp/puavo-install/puavo-install-and-update-ltspimages b/parts/ltsp/puavo-install/puavo-install-and-update-ltspimages
--- a/parts/ltsp/puavo-install/puavo-install-and-update-ltspimages
+++ b/parts/ltsp/puavo-install/puavo-install-and-update-ltspimages
@@ -419,7 +419,8 @@ fetch_with_wget() {
 }
 
 get_meta_files() {
-  local meta_download_ok meta_file series_url series_url_list
+  local gnupg_dir image_server meta_download_ok meta_file series_url \
+        series_url_list series_url_with_gpg_suffix
 
   rate_limit=$1
 
@@ -436,13 +437,24 @@ get_meta_files() {
 
   mkdir -p "$metas_dir"
   for series_url in $series_url_list; do
+    series_url_with_gpg_suffix="${series_url}.gpg"
     meta_file="${metas_dir}/${series_url##*/}"
-    if ! fetch_with_wget as_root "$rate_limit"      \
-                                 "${meta_file}.tmp" \
-                                 "$series_url"      \
+    if ! fetch_with_wget as_root "$rate_limit"                 \
+                                 "${meta_file}.gpg.tmp"        \
+                                 "$series_url_with_gpg_suffix" \
                                  checksums_fetch; then
       log warn "failed to fetch series ${series_url}"
       continue
+    fi
+
+    image_server=${series_url_with_gpg_suffix#*://} # remove scheme
+    image_server=${image_server%%/*}                # remove path
+    gnupg_dir="/etc/puavo-conf/gpg/${image_server}/os-images"
+    if ! gpg --decrypt --homedir "$gnupg_dir" --no-permission-warning \
+      --trust-model always "${meta_file}.gpg.tmp" 2>/dev/null \
+      > "${meta_file}.tmp"; then
+        log warn "GPG verification failed for ${series_url_with_gpg_suffix}"
+        continue
     fi
 
     if ! mv "${meta_file}.tmp" "$meta_file"; then
