Create UKIs by using bsdiff files when they need to be installed.

diff --git a/parts/ltsp/puavo-install/puavo-install-uki b/parts/ltsp/puavo-install/puavo-install-uki
--- a/parts/ltsp/puavo-install/puavo-install-uki
+++ b/parts/ltsp/puavo-install/puavo-install-uki
@@ -21,14 +21,19 @@ hosttype="$3"
 
 [ -d "$image_mountpoint" ] || panic "image mountpoint '$image_mountpoint' does not exist"
 [ -d "$UKI_ROOT" ] || panic "UKI root '$UKI_ROOT' does not exist"
+tmpdir=''
 
 cleanup_temporary_files() {
   find "$UKI_ROOT" -xdev -type d -name '*.tmp' -exec rm -rf {} + 2>/dev/null || true
   find "$UKI_ROOT" -xdev -type f -name '*.tmp' -delete 2>/dev/null || true
+  test -n "$tmpdir" && rm -rf "$tmpdir"
 }
 
 cleanup_temporary_files || echo "warning: failed to remove temporary files" >&2
 trap 'cleanup_temporary_files' INT TERM EXIT
+
+tmpdir=$(mktemp -d /tmp/puavo-install-uki.XXXXXX) \
+  || panic 'could not create a temporary directory'
 
 boot_directory="${image_mountpoint}/boot"
 [ -d "$boot_directory" ] || panic "boot directory '$boot_directory' does not exist"
@@ -59,9 +64,56 @@ install_boot_entry_config() {
   mv "$temporary_environment_file" "$environment_file"
 }
 
+patch_uki() {
+  local initrd_img_path kernel_version kernel_version_with_suffix \
+        tmp_uki_destination tmp_ukibase_path uki_checksum_file \
+        uki_destination uki_dir uki_patch vmlinuz_path
+  uki_patch=$1
+  uki_checksum_file=$2
+  uki_destination=$3
+
+  # If the copy is interrupted, a temporary file prevents the partial image
+  # from being used.  Note that this is required when we are updating the
+  # UKI, because the destination directory is not a temporary directory.
+  local tmp_uki_destination="${uki_destination}.tmp"
+
+  uki_dir=$(dirname "$uki_patch")
+  kernel_version_with_suffix=${uki_patch##*/kernel-}
+  kernel_version=${kernel_version_with_suffix%.uki.efi.bsdiff}
+
+  initrd_img_path="${uki_dir}/initrd.img-${kernel_version}"
+  vmlinuz_path="${uki_dir}/vmlinuz-${kernel_version}"
+
+  tmp_ukibase_path="${tmpdir}/ukibase-${kernel_version}"
+  tmp_uki_path="${tmpdir}/kernel-${kernel_version}.uki.efi"
+  if ! cat "$vmlinuz_path" "$initrd_img_path" > "$tmp_ukibase_path"; then
+    echo 'error: could not create a base UKI to patch from' >&2
+    return 1
+  fi
+
+  if ! bspatch "$tmp_ukibase_path" "$tmp_uki_path" "$uki_patch"; then
+    echo "error: bspatch failed to patch with '${uki_patch}'" >&2
+    return 1
+  fi
+
+  if ! (cd "$tmpdir" \
+          && sha256sum -c --status "$uki_checksum_file" 2>/dev/null); then
+    echo "error: checksum check of patched UKI '${uki}' failed" >&2
+    return 1
+  fi
+
+  if ! cp "$tmp_uki_path" "$tmp_uki_destination" || \
+     ! mv "$tmp_uki_destination" "$uki_destination"; then
+    echo "error: failed to copy/move UKI '${uki}' to EFI partition" >&2
+    return 1
+  fi
+
+  return 0
+}
+
 install_ukis() {
   local destination="$1"
-  local enabled_uki="$2"
+  local enabled_uki_patch="$2"
 
   local class_file="${image_mountpoint}/etc/puavo-image/class"
   local image_name_file="${image_mountpoint}/etc/puavo-image/name"
@@ -99,31 +151,28 @@ install_ukis() {
 
   local status=0
 
-  for uki in "$boot_directory"/*.uki.efi; do
+  local uki_patch
+  for uki_patch in "$boot_directory"/*.uki.efi.bsdiff; do
     local enabled="false"
 
-    if [ "$(realpath "$uki")" = "$(realpath "$enabled_uki")" ]; then
+    if [ "$(realpath "$uki_patch")" = "$(realpath "$enabled_uki_patch")" ]; then
       enabled="true"
     fi
 
-    local uki_destination
-    uki_destination="${uki_installation_directory}/$(basename "$uki")"
+    local uki="${uki_patch%.bsdiff}"
+    local uki_checksum_file="${uki}.sha256"
+    local uki_destination="${uki_installation_directory}/$(basename "$uki")"
 
-    # If the copy is interrupted, a temporary file prevents the partial image
-    # from being used. Note that this is required when we are updating the UKI,
-    # because the destination directory is not a temporary directory.
-    local uki_temporary_destination="${uki_destination}.tmp"
-
-    if ! cmp --quiet "$uki" "$uki_destination" 2>/dev/null; then
+    if ! (cd "$UKI_ROOT" \
+            && sha256sum -c --status "$uki_checksum_file" 2>/dev/null); then
       # If the UKI already exists, it must differ from the new one
-      # (e.g. possibly broken). Remove the existing file before copying
+      # (e.g. possibly broken).  Remove the existing file before copying
       # the new one, otherwise the transfer would require double the
       # disk space.
       rm -f "$uki_destination" || true
 
-      if ! cp "$uki" "$uki_temporary_destination" || \
-         ! mv "$uki_temporary_destination" "$uki_destination"; then
-        echo "error: failed to copy UKI '$uki' to EFI partition" >&2
+      if ! patch_uki "$uki_patch" "$uki_checksum_file" "$uki_destination"; then
+        echo "error: failed to patch UKI '${uki}' to EFI partition" >&2
         status=1
         continue
       fi
@@ -166,10 +215,10 @@ install_ukis() {
 kernel_version=$(determine_selected_kernel_version)
 [ -n "$kernel_version" ] || panic "failed to determine selected kernel version"
 
-enabled_uki=$(find "$boot_directory" -type f -name "*${kernel_version}.uki.efi" | head -n 1)
-[ -n "$enabled_uki" ] || panic "failed to find UKI with kernel version ${kernel_version}"
+enabled_uki_patch=$(find "$boot_directory" -type f -name "*${kernel_version}.uki.efi.bsdiff" | head -n 1)
+[ -n "$enabled_uki_patch" ] || panic "failed to find UKI with kernel version ${kernel_version}"
 
-install_ukis "$UKI_ROOT" "$enabled_uki" || {
+install_ukis "$UKI_ROOT" "$enabled_uki_patch" || {
   echo "error: failed to install UKI files to EFI partition" >&2
   exit 1
 }
