In puavo-reset-windows, do not use language tags from Microsoft documentation but map them to human language names that are also used in ISO filenames downloaded from microsoft.com.

diff --git a/parts/ltsp/puavo-install/puavo-reset-windows b/parts/ltsp/puavo-install/puavo-reset-windows
--- a/parts/ltsp/puavo-install/puavo-reset-windows
+++ b/parts/ltsp/puavo-install/puavo-reset-windows
@@ -85,11 +85,9 @@ print0_win_primary_partition_devpaths()
     }
 }
 
-print0_win_language_tag()
+print0_win_language()
 {
-    local win_language_id \
-          win_language_tag \
-          win_primary_partition_devpath
+    local win_language_id win_language win_primary_partition_devpath
 
     win_primary_partition_devpath=$1
     shift
@@ -109,22 +107,22 @@ print0_win_language_tag()
     ## https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-LCID/%5bMS-LCID%5d.pdf
     case "${win_language_id}" in
         '0407')
-            win_language_tag='de-DE'
+            win_language='German'
             ;;
         '0409')
-            win_language_tag='en-US'
+            win_language='English'
             ;;
         '040b')
-            win_language_tag='fi-FI'
+            win_language='Finnish'
             ;;
         '041d')
-            win_language_tag='sv-SE'
+            win_language='Swedish'
             ;;
         '0419')
-            win_language_tag='ru-RU'
+            win_language='Russian'
             ;;
         '0422')
-            win_language_tag='uk-UA'
+            win_language='Ukrainian'
             ;;
         *)
             logerr "Unsupported language ID '${win_language_id}'"
@@ -132,7 +130,7 @@ print0_win_language_tag()
             ;;
     esac
 
-    printf '%s' "${win_language_tag}"
+    printf '%s' "${win_language}"
 }
 
 print0_win_product_name()
@@ -374,9 +372,9 @@ get_wim_catalogue()
 
 choose_wim_image_to_use()
 {
-    local win_language_tag win_product_name win_version
+    local win_language win_product_name win_version
 
-    win_language_tag=$1
+    win_language=$1
     win_product_name=$2
 
     case "$win_product_name" in
@@ -389,7 +387,7 @@ choose_wim_image_to_use()
     esac
 
     preferred_versions_json=$(
-      jq -r --arg language "$win_language_tag" \
+      jq -r --arg language "$win_language" \
             --arg version "$win_version" '
         .images | map_values(select(.language == $language
                                       and .version == $version))
@@ -406,13 +404,13 @@ choose_wim_image_to_use()
 
 reset_win()
 {
-    local wim_file_path win_language_tag win_primary_partition_devpath \
+    local wim_file_path win_language win_primary_partition_devpath \
           win_product_name
 
     win_product_name=$1
     shift
 
-    win_language_tag=$1
+    win_language=$1
     shift
 
     win_primary_partition_devpath=$1
@@ -420,13 +418,15 @@ reset_win()
 
     wim_image_baseurl=$(get_wim_catalogue) || return 1
 
-    wim_image_name=$(choose_wim_image_to_use "$win_language_tag" \
+    wim_image_name=$(choose_wim_image_to_use "$win_language" \
                                              "$win_product_name")
+    echo "got wim_image_name=${wim_image_name} this is the image we will use for reset"
+    exit 1
 
-    loginfo "Reseting '${win_product_name} (${win_language_tag})' on '${win_primary_partition_devpath}'..."
+    loginfo "Reseting '${win_product_name} (${win_language})' on '${win_primary_partition_devpath}'..."
 
     fetch_wim_image "$wim_image_baseurl" "$wim_image_name" || {
-        logerr "Failed to fetch WIM file for '${win_product_name} (${win_language_tag})'."
+        logerr "Failed to fetch WIM file for '${win_product_name} (${win_language})'."
         return 1
     }
 
@@ -457,7 +457,7 @@ reset_win()
         loginfo "Wiped all unused data from '${win_primary_partition_devpath}'."
     fi
 
-    loginfo "Reset '${win_product_name} (${win_language_tag})' on '${win_primary_partition_devpath}' to factory settings successfully."
+    loginfo "Reset '${win_product_name} (${win_language})' on '${win_primary_partition_devpath}' to factory settings successfully."
 
     return 0
 }
@@ -465,9 +465,7 @@ reset_win()
 
 reset_all_wins()
 {
-    local returnval \
-          win_language_tag \
-          win_product_name
+    local returnval win_language win_product_name
 
     returnval=0
 
@@ -478,13 +476,13 @@ reset_all_wins()
             continue
         }
 
-        win_language_tag=$(print0_win_language_tag "${win_primary_partition_devpath}") || {
+        win_language=$(print0_win_language "${win_primary_partition_devpath}") || {
             logerr "Failed to get the language tag of Windows on '${win_primary_partition_devpath}'."
             returnval=1
             continue
         }
 
-        loginfo "Detected '${win_product_name} (${win_language_tag})' on '${win_primary_partition_devpath}'."
+        loginfo "Detected '${win_product_name} (${win_language})' on '${win_primary_partition_devpath}'."
 
         case "${win_product_name}" in
             'Windows 10 Home' | 'Windows 10 Pro' | 'Windows 11 Home' | 'Windows 11 Pro')
@@ -497,19 +495,19 @@ reset_all_wins()
         esac
 
         $use_force || dialog --no-lines --clear --erase-on-exit --defaultno --yesno \
-               "Reset '${win_product_name} (${win_language_tag})' on '${win_primary_partition_devpath}'?" 5 100 || {
-            loginfo "Skipping '${win_product_name} (${win_language_tag})' on '${win_primary_partition_devpath}'."
+               "Reset '${win_product_name} (${win_language})' on '${win_primary_partition_devpath}'?" 5 100 || {
+            loginfo "Skipping '${win_product_name} (${win_language})' on '${win_primary_partition_devpath}'."
             continue
         }
 
         $use_force || dialog --no-lines --clear --erase-on-exit --defaultno --yesno \
                "All data will be lost on '${win_primary_partition_devpath}'! Are you really sure you want to proceed?" 5 100 || {
-            loginfo "Skipping '${win_product_name} (${win_language_tag})' on '${win_primary_partition_devpath}'."
+            loginfo "Skipping '${win_product_name} (${win_language})' on '${win_primary_partition_devpath}'."
             continue
         }
 
-        reset_win "${win_product_name}" "${win_language_tag}" "${win_primary_partition_devpath}" || {
-            logerr "Failed to reset '${win_product_name} (${win_language_tag})' on '${win_primary_partition_devpath}'."
+        reset_win "${win_product_name}" "${win_language}" "${win_primary_partition_devpath}" || {
+            logerr "Failed to reset '${win_product_name} (${win_language})' on '${win_primary_partition_devpath}'."
             returnval=1
             continue
         }
