puavo-reset-windows: do not require any specific language for a WIM image
Any language is fine, user can pick their own during Windows setup anyways.

diff --git a/parts/ltsp/puavo-install/puavo-reset-windows b/parts/ltsp/puavo-install/puavo-reset-windows
--- a/parts/ltsp/puavo-install/puavo-reset-windows
+++ b/parts/ltsp/puavo-install/puavo-reset-windows
@@ -90,61 +90,9 @@ print0_win_product_name()
     printf '%s' "${win_product_name}"
 }
 
-print0_win_language_tag()
-{
-    local win_language_id \
-          win_language_tag \
-          win_primary_partition_devpath
-
-    win_primary_partition_devpath=$1
-    shift
-
-    ntfscat "${win_primary_partition_devpath}" 'Windows/System32/config/SYSTEM' >"${tmpdir}/system_hive" || {
-        logerr "Failed to get SYSTEM hive from '${win_primary_partition_devpath}'."
-        return 1
-    }
-
-    win_language_id=$(hivexget "${tmpdir}/system_hive" 'ControlSet001\Control\Nls\Language' \
-                          | sed -r -n 's/"InstallLanguage"="([0-9A-Fa-f]{4})"$/\1/p' \
-                          | tr '[:upper:]' '[:lower:]') || {
-        logerr "Failed to parse InstallLanguage from SYSTEM hive of '${win_primary_partition_devpath}'."
-        return 1
-    }
-
-    ## https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-LCID/%5bMS-LCID%5d.pdf
-    case "${win_language_id}" in
-        '0407')
-            win_language_tag='de-DE'
-            ;;
-        '0409')
-            win_language_tag='en-US'
-            ;;
-        '040b')
-            win_language_tag='fi-FI'
-            ;;
-        '041d')
-            win_language_tag='sv-SE'
-            ;;
-        '0419')
-            win_language_tag='ru-RU'
-            ;;
-        '0422')
-            win_language_tag='uk-UA'
-            ;;
-        *)
-            logerr "Unsupported language ID '${win_language_id}'"
-            return 1
-            ;;
-    esac
-
-    printf '%s' "${win_language_tag}"
-}
-
 check_wim_file()
 {
-    local expected_win_language_tag \
-          expected_win_product_name \
-          win_language_tag \
+    local expected_win_product_name \
           win_product_name \
           wim_file_path
 
@@ -154,8 +102,8 @@ check_wim_file()
     expected_win_product_name=$1
     shift
 
-    expected_win_language_tag=$1
-    shift
+    ## TODO: add WIM file checksum check. Check against pre-verified
+    ## hard-coded checksums.
 
     wiminfo "${wim_file_path}" | grep -c '^Index:' | grep -x -q 1 || {
         logerr "WIM file '${wim_file_path}' has multiple images, expected it to have just one."
@@ -165,12 +113,6 @@ check_wim_file()
     win_product_name=$(wiminfo "${wim_file_path}" | sed -r -n 's/^Product Name:\s*(.+)$/\1/p')
     if [ "${win_product_name}" != "${expected_win_product_name}" ]; then
         logerr "WIM file '${wim_file_path}' has image for an incorrect product '${win_product_name}'."
-        return 1
-    fi
-
-    win_language_tag=$(wiminfo "${wim_file_path}" | sed -r -n 's/^Default Language:\s*(.+)$/\1/p')
-    if [ "${win_language_tag}" != "${expected_win_language_tag}" ]; then
-        logerr "WIM file '${wim_file_path}' has image for an incorrect language '${win_language_tag}'."
         return 1
     fi
 
@@ -187,35 +129,24 @@ fetch_wim_file()
     win_product_name=$1
     shift
 
-    win_language_tag=$1
     shift
 
-    loginfo "Fetching WIM file for '${win_product_name} ${win_language_tag}'..."
+    loginfo "Fetching WIM file for '${win_product_name}'..."
 
     ## TODO: Where WIM files should be fetched from?
     ##
-    ## We need 4 files per language:
-    ## - Windwos 10 Home
-    ## - Windows 10 Pro
-    ## - Windows 11 Home
-    ## - Windows 11 Pro
-    ##
-    ## So perhaps we need to support:
-    ## - cdn.opinsys.fi / cdn.puavo.org? (We probably still need to download the WIM file to /home or /images for the duration of reset)
-    ## - USB mass media? (If we decide to use a separate "Windows Reset USB stick")
-    ## - Other persistent storage? (Reserve 6G or so for the factory image)
-    ## - Live download from Microsoft website via Mido? (Microsoft does seem to IP-block some legit IP addresses, this is not reliable method at all.)
-    ##
-    ## Win10 images are ~7G (compressed).
+    ## We need 2 files:
+    ## - Windwos 10
+    ## - Windows 11
 
     ## TODO: obviously remove this once we know where to get
     ## images. This is just for development purposes.
     wim_file_path="/home/wim-files/${win_product_name}_${win_language_tag}.wim"
 
-    loginfo "Fetched WIM file '${wim_file_path}' for '${win_product_name} ${win_language_tag}'."
+    loginfo "Fetched WIM file '${wim_file_path}' for '${win_product_name}'."
 
-    check_wim_file "${wim_file_path}" "${win_product_name}" "${win_language_tag}" || {
-        logerr "Invalid WIM file '${wim_file_path}' for '${win_product_name} ${win_language_tag}'."
+    check_wim_file "${wim_file_path}" "${win_product_name}" || {
+        logerr "Invalid WIM file '${wim_file_path}' for '${win_product_name}'."
         return 1
     }
 
@@ -225,20 +156,16 @@ fetch_wim_file()
 reset_win()
 {
     local wim_file_path \
-          win_language_tag \
           win_primary_partition_devpath \
           win_product_name
 
     win_product_name=$1
     shift
 
-    win_language_tag=$1
-    shift
-
     win_primary_partition_devpath=$1
     shift
 
-    wim_file_path=$(fetch_wim_file "${win_product_name}" "${win_language_tag}") || {
+    wim_file_path=$(fetch_wim_file "${win_product_name}") || {
         logerr "Failed to fetch WIM file for '${win_product_name}'."
         return 1
     }
@@ -269,7 +196,6 @@ reset_win()
 reset_all_wins()
 {
     local returnval \
-          win_language_tag \
           win_product_name
 
     returnval=0
@@ -280,13 +206,8 @@ reset_all_wins()
             returnval=1
             continue
         }
-        win_language_tag=$(print0_win_language_tag "${win_primary_partition_devpath}") || {
-            logerr "Failed to get the language of Windows on '${win_primary_partition_devpath}'."
-            returnval=1
-            continue
-        }
 
-        loginfo "Detected '${win_product_name} ${win_language_tag}' on '${win_primary_partition_devpath}'."
+        loginfo "Detected '${win_product_name}' on '${win_primary_partition_devpath}'."
 
         ## TODO: add (and test!) Windows 11 support
         case "${win_product_name}" in
@@ -300,26 +221,26 @@ reset_all_wins()
         esac
 
         $use_force || dialog --no-lines --clear --erase-on-exit --defaultno --yesno \
-               "Reset '${win_product_name} ${win_language_tag}' on '${win_primary_partition_devpath}'?" 5 80 || {
-            logerr "Skipping '${win_product_name} ${win_language_tag}' on '${win_primary_partition_devpath}'."
+               "Reset '${win_product_name}' on '${win_primary_partition_devpath}'?" 5 80 || {
+            logerr "Skipping '${win_product_name}' on '${win_primary_partition_devpath}'."
             returnval=1
             continue
         }
 
         $use_force || dialog --no-lines --clear --erase-on-exit --defaultno --yesno \
                'All data will be lost! Are you really sure you want to proceed?' 5 80 || {
-            logerr "Skipping '${win_product_name} ${win_language_tag}' on '${win_primary_partition_devpath}'."
+            logerr "Skipping '${win_product_name}' on '${win_primary_partition_devpath}'."
             returnval=1
             continue
         }
 
-        reset_win "${win_product_name}" "${win_language_tag}" "${win_primary_partition_devpath}" || {
-            logerr "Failed to reset '${win_product_name} ${win_language_tag}' on '${win_primary_partition_devpath}'."
+        reset_win "${win_product_name}" "${win_primary_partition_devpath}" || {
+            logerr "Failed to reset '${win_product_name}' on '${win_primary_partition_devpath}'."
             returnval=1
             continue
         }
 
-        loginfo "Reset '${win_product_name} ${win_language_tag}' on '${win_primary_partition_devpath}' to factory settings successfully."
+        loginfo "Reset '${win_product_name}' on '${win_primary_partition_devpath}' to factory settings successfully."
 
     done < <(print0_win_primary_partition_devpaths) || {
         logerr "Unexpected termination of Windows reset loop"
