Removed unnecessary '-P' (perl-regexp) flag from one grep. Indent fixes and grammar changes.

diff --git a/parts/ltsp/puavo-install/puavo-disk-erase b/parts/ltsp/puavo-install/puavo-disk-erase
--- a/parts/ltsp/puavo-install/puavo-disk-erase
+++ b/parts/ltsp/puavo-install/puavo-disk-erase
@@ -20,7 +20,7 @@ secure_erase() {
   echo "Chosen << ${target_disk} >>"
   case "${target_disk}" in
     *nvme*)
-      echo 'Selected disk is an NVMe disk. Using nvme-cli utility...'
+      echo 'Selected disk is an NVMe disk. Using "nvme-cli" utility for Secure Erase.'
       nvme format -s1 "${target_disk}"
       exit 1
       ;;
@@ -30,14 +30,14 @@ secure_erase() {
         exit 1
       fi
 
-      if ! hdparm -I "${target_disk}" | grep -P "SECURITY ERASE UNIT" >&2; then
+      if ! hdparm -I "${target_disk}" | grep "SECURITY ERASE UNIT" >&2; then
         echo 'Selected disk does not support Secure Erase!' >&2
         exit 1
       fi
 
       echo 'Disk supports Secure Erase.'
-        if ! hdparm -I "${target_disk}" | grep -P "not\tfrozen" >&2; then
-        echo 'Disk is in frozen state, aborting!' >&2
+      if ! hdparm -I "${target_disk}" | grep -P "not\tfrozen" >&2; then
+        echo 'Disk is in frozen state, cannot continue!' >&2
         echo 'Please close the lid of the device for a few seconds, reopen it and try again.' >&2
         echo
         echo 'If we are netbooted, closing the lid will not put the device to sleep.'
@@ -61,20 +61,20 @@ secure_erase() {
             exit 1
             ;;
         esac
-      exit 1
-    fi
+        exit 1
+      fi
 
-    echo 'Disk is not in frozen state, we can continue.'
-    hdparm --user-master user --security-set-pass Pass "${target_disk}"
-    if ! hdparm -I "${target_disk}" | grep -P "Security level high" >&2; then
-      echo 'Failed setting user and password, exiting.' >&2
-      exit 1
-    fi
+      echo 'Disk is not in frozen state, we can continue.'
+      hdparm --user-master user --security-set-pass Pass "${target_disk}"
+      if ! hdparm -I "${target_disk}" | grep -P "Security level high" >&2; then
+        echo 'Failed setting user and password, exiting.' >&2
+        exit 1
+      fi
 
-    echo 'User and password set, ready for secure erase.'
-    hdparm --user-master user --security-erase Pass "${target_disk}"
-    echo 'Command completed. If you see no errors above, you may now reboot the device.'
-    ;;
+      echo 'User and password set, ready for secure erase.'
+      hdparm --user-master user --security-erase Pass "${target_disk}"
+      echo 'Command completed. If you see no errors above, you may now reboot the device.'
+      ;;
   esac
 }
 
