Make all UEFI-booting devices hybrid MBR/UEFI-bootable.
We still do not have any UEFI-only devices in production
(yes, in late 2020!), so we can still do this without separately
supporting the UEFI-only mode.

I do not know if this will trigger some issues, but we will see.
The main reason for this is that we want "puavo-make-install-disk"
to make removable, bootable usb disks that can be booted both
in legacy BIOS mode and in UEFI.  But then I do not see why we
could not do that with all disks, not just the removable ones.

(Some tricky issues might develop, for example system will have
UEFI-boot, then it is changed to legacy, and the UEFI-grub stops
updating, and then system is switched again to UEFI-boot,
booting with not-up-to-date Grub-version... but do these situations
really happen in the real world and does that matter, that is
another question).

diff --git a/parts/ltsp/puavo-install/puavo-install-grub b/parts/ltsp/puavo-install/puavo-install-grub
--- a/parts/ltsp/puavo-install/puavo-install-grub
+++ b/parts/ltsp/puavo-install/puavo-install-grub
@@ -351,6 +351,11 @@ handle_windows_partion_file() {
 }
 
 get_efi_devpath() {
+  if [ ! -d /sys/firmware/efi ]; then
+    # we have not booted in UEFI-mode, UEFI/Grub installation can not work
+    return 0
+  fi
+
   env LANG=C fdisk -l "$1" \
     | awk '$1 ~ "^/dev/" && /EFI System/ { print $1; exit(0) }'
 }
@@ -496,25 +501,32 @@ else
   for grubdev in $grub_target_devices; do
     log info "installing grub to ${grubdev}"
 
-    efi_devpath=$(get_efi_devpath "$grubdev")
+    # Install MBR boot first.  Even if we have booted as UEFI, even if
+    # legacy is not supported (on this host... our drive might be removable).
+    if ! grub_msg=$(grub-install --boot-directory="$boot_dir" \
+                      --target=i386-pc "$grubdev" 3>&- 4>&- 5>&- 2>&1); then
+      log err "Grub (MBR) installation to ${grubdev} failed: ${grub_msg}"
+      exit 1
+    fi
 
-    grub_efi_arguments=''
+    efi_devpath=$(get_efi_devpath "$grubdev")
     if [ -n "$efi_devpath" ]; then
       if ! mount_efi_partition "$efi_devpath"; then
         log err "could not mount /boot/efi from ${efi_devpath}"
         exit 1
       fi
       grub_efi_arguments=$(get_grub_efi_arguments "$vgname")
-    fi
-    if ! grub_msg=$(grub-install --boot-directory="$boot_dir" \
-                      $grub_efi_arguments "$grubdev" 3>&- 4>&- 5>&- 2>&1); then
-      log err "Grub installation to ${grubdev} failed: ${grub_msg}"
-      exit 1
-    fi
-    log info "Grub installation to ${grubdev} was successful"
-    if [ -n "$efi_devpath" ]; then
+      if ! grub_msg=$(grub-install --boot-directory="$boot_dir" \
+                        $grub_efi_arguments "$grubdev" \
+                        3>&- 4>&- 5>&- 2>&1); then
+        log err "Grub (UEFI) installation to ${grubdev} failed: ${grub_msg}"
+        umount /boot/efi || true
+        exit 1
+      fi
       umount /boot/efi || true
     fi
+
+    log info "Grub installation to ${grubdev} was successful"
   done
 
   grub_install_done=true
