Separate UKI installation from GRUB installation

diff --git a/parts/ltsp/puavo-install/puavo-install-and-update-ltspimages b/parts/ltsp/puavo-install/puavo-install-and-update-ltspimages
--- a/parts/ltsp/puavo-install/puavo-install-and-update-ltspimages
+++ b/parts/ltsp/puavo-install/puavo-install-and-update-ltspimages
@@ -613,7 +613,8 @@ install_image() {
     query_update_confirmation "$current_ltspimage_name" "$imagename"
   fi
 
-  install_from_file_or_nbd "$imagename" "$type_opt" "$type_arg"
+  install_from_file_or_nbd   "$imagename" "$type_opt" "$type_arg"
+  install_uki_files          "$imagename"
   run_image_preinst_hook     "$imagename"
   set_image_as_default_image "$imagename"
 
@@ -742,6 +743,30 @@ but version $new_ltspimage_name is available.
 Press ENTER to proceed to update it.
 EOF
   read answer
+}
+
+install_uki_files() {
+  local imagename="$1"
+  local imagepath="${images_dir}/${imagename}"
+
+  if [ "${UKI_MODE:-}" != "1" ]; then
+    return 0
+  fi
+
+  # use the specified host type or find out the active one
+  local install_hosttype="$hosttype"
+
+  if [ -z "$install_hosttype" ]; then
+    install_hosttype=$(cat /etc/puavo/hosttype 2>/dev/null || true)
+
+    if [ -z "$install_hosttype" ]; then
+      echo 'Failed to determine host type for UKI installation' >&2
+      return 1
+    fi
+  fi
+
+  log info "installing UKI files from $imagepath"
+  puavo-install-and-update-uki-image "$imagepath" "$install_hosttype" "$images_dir"
 }
 
 run_image_preinst_hook() {
@@ -903,6 +928,7 @@ update_image() {
     log info "the requested ltsp image is already in place"
     update_stats uptodate 100
   else
+    install_uki_files          "$next_image"
     run_image_preinst_hook     "$next_image"
     set_image_as_default_image "$next_image"
   fi
diff --git a/parts/ltsp/puavo-install/puavo-install-grub b/parts/ltsp/puavo-install/puavo-install-grub
--- a/parts/ltsp/puavo-install/puavo-install-grub
+++ b/parts/ltsp/puavo-install/puavo-install-grub
@@ -783,8 +783,7 @@ install_efi_grub() {
   if [ "${UKI_MODE:-}" = "1" ]; then
     install_puavo_grub_files_to_efi_partition "$boot_dir" && \
     copy_grub_environment && \
-    write_grub_version "${boot_dir}/grub/version" && \
-    puavo-install-uki "$boot_dir" || {
+    write_grub_version "${boot_dir}/grub/version" || {
       echo "failed to install UKI files to EFI partition" >&2
       umount /boot/efi || true
       return 1
@@ -1122,11 +1121,11 @@ install_grub_configuration() {
 if [ "${UKI_MODE:-}" = "1" ]; then
   # Install the grub config to all EFI partitions
   for grubdev in $grub_target_devices; do
-    echo "> updating the Grub configuration on ${grubdev}"
+    log info "updating the Grub configuration on ${grubdev}"
 
     efi_devpath=$(get_efi_devpath "$grubdev")
     if [ -z "$efi_devpath" ]; then
-      log err "Failed to find EFI partition path for GRUB device"
+      log err "failed to find EFI partition path for GRUB device"
       exit 1
     fi
 
@@ -1142,12 +1141,6 @@ if [ "${UKI_MODE:-}" = "1" ]; then
     efi_partition_uuid=$(get_efi_uuid "$grubdev")
     generate_grub_configuration "$efi_partition_uuid"
     install_grub_configuration
-
-    if ! puavo-update-uki-command-line "$boot_dir" "$hosttype"; then
-      log err "failed to update the command line for UKI"
-      umount /boot/efi || true
-      exit 1
-    fi
 
     umount /boot/efi || true
   done
