Do not run "puavo-cert-tool" explicitly in puavo-install, instead run it through update-configuration.  This way we get a correct value for the "puavo.admin.certs.versions" puavo-conf variable, and "puavo-cert-tool" requests the necessary certificates.
Also rearrange things in puavo-install a bit so that (hopefully)
setting up a preinstalled host is more similar to a normal installation.

diff --git a/parts/ltsp/puavo-install/puavo-install b/parts/ltsp/puavo-install/puavo-install
--- a/parts/ltsp/puavo-install/puavo-install
+++ b/parts/ltsp/puavo-install/puavo-install
@@ -281,21 +281,47 @@ install_localbootdevice() {
 
   update_configuration_retstatus=0
 
-  puavo-setup-filesystems $puavo_preseed_setup_filesystems_args
+  if is_preinstalled "$puavo_install_hosttype"; then
+    if ! [ "$puavo_hosttype" = 'bootserver' \
+             -o "$puavo_hosttype" = 'laptop' \
+             -o "$puavo_hosttype" = 'wirelessaccesspoint' ]; then
+      echo "Setting up preinstalled '$puavo_hosttype' is not supported" >&2
+      return 1
+    fi
+  else
+    puavo-setup-filesystems $puavo_preseed_setup_filesystems_args
+  fi
+
   setup_state "$puavo_hosttype"
 
-  # Grub needs to be installed before images, because grub
-  # configuration is updated during image installation by
-  # puavo-image-preinst.
-  install_grub
+  if is_preinstalled "$puavo_install_hosttype"; then
+    # If host was preinstalled, grub will boot the host as 'preinstalled' until
+    # we do this:
+    puavo-install-grub --hosttype "$puavo_hosttype" --only-update-config
+    # From now on the host will boot as a fully installed host.
+    rm -f /images/puavo_preinstalled
+  else
+    # Grub needs to be installed before images, because grub
+    # configuration is updated during image installation by
+    # puavo-image-preinst.
+    install_grub
+  fi
+
+  update_configuration || update_configuration_retstatus=1
+  # fix this as update_configuration messes this up (from the kernel cmdline):
+  puavo-conf puavo.hosttype "$puavo_hosttype"
+
+  if [ "$puavo_hosttype" = 'bootserver' ]; then
+    bootserver_setup_state
+  fi
+
   install_image "$puavo_install_hosttype"
+  update_images || update_configuration_retstatus=1
 
   if [ "$puavo_hosttype" = 'bootserver' ]; then
     /usr/local/lib/puavo-handle-image-changes \
       || update_configuration_retstatus=1
   fi
-
-  update_configuration || update_configuration_retstatus=1
 
   if [ "$puavo_hosttype" = 'laptop' \
     -a -n "$(puavo-conf puavo.abitti.version 2>/dev/null || true)" ]; then
@@ -312,80 +338,38 @@ install_localbootdevice() {
 
 is_preinstalled() { [ "$1" = 'preinstalled' ]; }
 
-setup_preinstalled_localbootdevice() {
-  puavo_hosttype=$1
-
-  update_configuration_retstatus=0
-
-  if ! [ "$puavo_hosttype" = 'bootserver' \
-           -o "$puavo_hosttype" = 'laptop' \
-           -o "$puavo_hosttype" = 'wirelessaccesspoint' ]; then
-    echo "Setting up preinstalled '$puavo_hosttype' is not supported" >&2
-    return 1
-  fi
-
-  setup_state "$puavo_hosttype"
-
-  # some failures of update_configuration are inconsequential and can be
-  # fixed after reboot
-  update_configuration || update_configuration_retstatus=1
-
-  # If host was preinstalled, grub will boot the host as 'preinstalled' until
-  # we do this:
-  puavo-install-grub --hosttype "$puavo_hosttype" --only-update-config \
-    || update_configuration_retstatus=1
-
-  # From now on the host will boot as a fully installed host.
-  rm -f /images/puavo_preinstalled || update_configuration_retstatus=1
-
-  return $update_configuration_retstatus
-}
-
 setup_state() {
-  local puavo_hosttype
-  puavo_hosttype=$1
-
   mkdir -p /state
   mountpoint -q /state || mount /dev/mapper/puavo-state /state
   mkdir -p /state/etc
   cp -aT /etc/puavo /state/etc/puavo
-  sync
-
-  puavo-cert-tool create
-  echo
-
-  if [ "$puavo_hosttype" = 'bootserver' ]; then
-    bootserver_setup_state
-  fi
-
-  return 0
 }
 
 update_configuration() {
-  update_configuration_status=0
-
   echo 'Updating configuration...'
   if /usr/lib/puavo-ltsp-install/update-configuration; then
     echo '  ... configuration updated.'
-    echo 'Trying image update...'
-    if /usr/lib/puavo-ltsp-install/update-images false false; then
-      echo '  ... image updated.'
-    else
-      echo '  ... image update failed (may update it later).'
-      update_configuration_status=1
-    fi
+    echo
+    return 0
   else
     echo '  ... a problem occurred when updating configuration.'
-    update_configuration_status=1
+    echo
+    return 1
   fi
-
-  echo
-
-  sync
-
-  return $update_configuration_status
 }
 
+update_images() {
+  echo 'Trying image update...'
+  if /usr/lib/puavo-ltsp-install/update-images false false; then
+    echo '  ... image updated.'
+    echo
+    return 0
+  else
+    echo '  ... image update failed (may update it later).'
+    echo
+    return 1
+  fi
+}
 
 # main
 
@@ -424,14 +408,6 @@ puavo-register --accepted-devicetypes "$accepted_hosttypes" \
 
 puavo_hosttype=$(cat /etc/puavo/hosttype)
 puavo-conf puavo.hosttype "$puavo_hosttype"
-
-if is_preinstalled "$puavo_install_hosttype"; then
-  setup_preinstalled_localbootdevice "$puavo_hosttype"
-  exit 0
-fi
-
-# Host is not preinstalled, so do the full install if hosttype so
-# requires (for fatclients nothing needs to be done).
 
 case "$puavo_hosttype" in
   bootserver|laptop|wirelessaccesspoint)
