Add puavo-list-install-devices.  Use it in both puavo-install-grub and puavo-update-kernels to determine where Grub and UKI kernels should go to.  In puavo-install-grub, determine if we are using UKI kernels from the error code returned by puavo-list-install-devices. UKI kernels are used in case we have an EFI partition of sufficient size.

diff --git a/parts/ltsp/puavo-install/puavo-install-grub b/parts/ltsp/puavo-install/puavo-install-grub
--- a/parts/ltsp/puavo-install/puavo-install-grub
+++ b/parts/ltsp/puavo-install/puavo-install-grub
@@ -66,11 +66,22 @@ get_grub_efi_arguments() {
 }
 
 grub_m4_template() {
-  local efi_partition_uuid vmlinuz_name with_uki_kernels
+  local grubdev grub_target_devices partuuid uki_kernel_device vmlinuz_name \
+        with_uki_kernels
   with_uki_kernels=$1
+  grub_target_devices=$2
 
   if $with_uki_kernels; then
-    if ! efi_partition_uuid=$(lookup_efi_partition_uuid "$diskdev"); then
+    uki_kernel_device=
+    for grubdev in $grub_target_devices; do
+      if [ -z "$uki_kernel_device" ]; then
+        # pick the first Grub device to boot the UKI kernel from
+        # (XXX is this okay?)
+        uki_kernel_device="$grubdev"
+      fi
+    done
+
+    if ! partuuid=$(lookup_efi_partition_uuid "$uki_kernel_device"); then
       log err 'using SecureBoot but could not lookup EFI partition UUID'
       return 1
     fi
@@ -218,7 +229,7 @@ GRUB_CFG_EOF
 
   if $with_uki_kernels; then
     cat <<GRUB_CFG_EOF
-    search --no-floppy --fs-uuid --set=root ${efi_partition_uuid}
+    search --no-floppy --fs-uuid --set=root ${partuuid}
     chainloader /EFI/PuavoOS/\${image_alias_path}/${vmlinuz_name}.unsigned.efi ro init=/sbin/init-puavo __PUAVO_KERNEL_ARGUMENTS__ \${kernelparameters}
 GRUB_CFG_EOF
   else
@@ -374,33 +385,15 @@ done
 GRUB_CFG_EOF
 }
 
-find_grub_target_devices_on_raid() {
-  local diskdev
-
-  diskdev=$1
-  mdadm --detail "$diskdev" \
-    | awk '   $1 ~ /^[0-9]+$/ \
-           && $2 ~ /^[0-9]+$/ \
-           && $3 ~ /^[0-9]+$/ {
-             split($0, a)
-             for (i in a) {
-               if (a[i] ~ /^\/dev\/[a-z]+[0-9]+$/) {
-                  sub(/[0-9]+$/, "", a[i])
-                  print a[i]
-               }
-             }
-           }'
-}
-
-# also in puavo-update-kernels
+# also in puavo-list-install-devices
 get_efi_devpath() {
-  local diskdev
+  local diskdev lsblk_output
   diskdev=$1
+  lsblk_output=$(lsblk -n -l -o PATH,PARTTYPE "$diskdev") || return 1
   # c12a7328-f81f-11d2-ba4b-00a0c93ec93b == EFI partition type
-  lsblk -n -l -o PATH,PARTTYPE "$diskdev" \
-    | awk '
-        $2 == "c12a7328-f81f-11d2-ba4b-00a0c93ec93b" { print $1; exit(0) }
-      '
+  printf "$lsblk_output" | awk '
+    $2 == "c12a7328-f81f-11d2-ba4b-00a0c93ec93b" { print $1; exit(0) }
+  '
 }
 
 has_bios_boot_partition() {
@@ -490,12 +483,11 @@ exitstatus=0
 
 hosttype=$(cat /etc/puavo/hosttype 2>/dev/null || true)
 images_dir=/images
-list_efi_partitions=false
 only_update_config=false
 vgname=puavo
 
 if ! args=$(getopt -n "$0" -o +                                                              \
-                   -l 'hosttype:,images-dir:,list-efi-partitions,only-update-config,vgname:' \
+                   -l 'hosttype:,images-dir:,only-update-config,vgname:' \
                    -- "$@"); then
   usage
 fi
@@ -503,11 +495,10 @@ fi
 eval "set -- $args"
 while [ $# -ne 0 ]; do
   case "$1" in
-    --hosttype)            hosttype=$2;              shift; shift ;;
-    --images-dir)          images_dir=$2;            shift; shift ;;
-    --list-efi-partitions) list_efi_partitions=true; shift        ;;
-    --only-update-config)  only_update_config=true;  shift        ;;
-    --vgname)              vgname=$2;                shift; shift ;;
+    --hosttype)           hosttype=$2;              shift; shift ;;
+    --images-dir)         images_dir=$2;            shift; shift ;;
+    --only-update-config) only_update_config=true;  shift        ;;
+    --vgname)             vgname=$2;                shift; shift ;;
     --) shift; break ;;
     *)  usage ;;
   esac
@@ -515,48 +506,19 @@ done
 
 [ $# -eq 0 ] || usage
 
-if ! $list_efi_partitions; then
-  log notice 'starting to update Grub'
-fi
+log notice 'starting to update Grub'
 
-# pvs and assorted utilities complain if we leak file descriptors, that is
-# why we do "3>&- 4>&- 5>&-" (same with grub-install)
-diskdev=$(pvs 3>&- 4>&- 5>&-                                            \
-            | awk -v vgname="$vgname" '$2 == vgname { print $1; exit }' \
-            | sed -E '
-                /\/dev\/loop/   { s|p[0-9]+$|| }
-                /\/dev\/mmcblk/ { s|p[0-9]+$|| }
-                /\/dev\/md/     { s|p[0-9]+$|| }
-                /\/dev\/nvme/   { s|p[0-9]+$|| }
-                /\/dev\/[sv]d/  { s|[0-9]+$||  }
-                /\/dev\/xvd/    { s|[0-9]+$||  }
-              ')
-
-if [ -z "$diskdev" ]; then
-  log err "could not find the disk device where volume group '${vgname}' is"
+if ! grub_target_devices=$(
+  /usr/lib/puavo-ltsp-install/puavo-list-install-devices \
+    --vgname "$vgname"); then
+  log err "error looking up grub target devices for '${vgname}'"
   exit 1
 fi
-
-possible_windows_disk_dev=''
-case "$diskdev" in
-  /dev/md*)
-    grub_target_devices=$(find_grub_target_devices_on_raid "$diskdev")
-    if [ -z "$grub_target_devices" ]; then
-      log err 'could not find grub target devices on RAID configuration'
-      exit 1
-    fi
-    ;;
-  *)
-    grub_target_devices="$diskdev"
-    possible_windows_disk_dev="$diskdev"
-    ;;
-esac
-
-if $list_efi_partitions; then
-  for grub_device in $grub_target_devices; do
-    printf "%s\n" "$(get_efi_devpath "$grub_device")"
-  done
-  exit 0
+if ! possible_windows_disk_dev=$(
+  /usr/lib/puavo-ltsp-install/puavo-list-install-devices \
+    --vgname "$vgname" --windows); then
+  log err 'error looking up a possible Windows device'
+  exit 1
 fi
 
 if [ ! -d "$images_dir" ]; then
@@ -654,17 +616,14 @@ install_efi_grub() {
   return 0
 }
 
-with_uki_kernels=false
-if ! mokutil_output=$(mokutil --sb-state); then
-  log err 'mokutil returned error'
-  exit 1
-fi
-if [ "$mokutil_output" = 'SecureBoot enabled' ]; then
-  with_uki_kernels=true
-  if ! puavo-update-kernels; then
-    log err 'could not update UKI kernels'
-    exit 1
+with_uki_kernels=true
+if ! puavo-update-kernels; then
+  if [ $? -eq 2 ]; then
+    # no EFI partitions big enough for UKI kernels
+    with_uki_kernels=false
   fi
+  log err 'error updating UKI kernels'
+  exit 1
 fi
 
 grub_install_done=false
@@ -724,7 +683,12 @@ fi
 grub_cfg_path="${boot_dir}/grub/grub.cfg"
 tmp_grub_cfg_path="${grub_cfg_path}.tmp"
 
-grub_m4_template "$with_uki_kernels"                          \
+if ! grub_template=$(grub_m4_template "$with_uki_kernels" \
+                       "$grub_target_devices"); then
+  log err 'error creating Grub configuration template'
+  exit 1
+fi
+printf "%s\n" "$grub_template" \
   | m4 -D__PUAVO_KERNEL_ARGUMENTS__="$puavo_kernel_arguments" \
        -D__PUAVO_LIVEBOOT_OPTION__="$puavo_liveboot_option"   \
        -D__PUAVO_LVM_PARTITION__="$puavo_lvm_partition"       \
