puavo-reset-windows: add install-re-partition mode
New usage: puavo-reset-windows --mode install-re-partition [--force] WIN_C_PARTITION_DEVPATH WIN_RE_PARTITION_DEVPATH

This causes puavo-reset-windows to install Windows Recovery
Environment (certain files from the given WIN C partition) to the
partition at WIN_RE_PARTITION_DEVPATH.

diff --git a/parts/ltsp/puavo-install/puavo-reset-windows b/parts/ltsp/puavo-install/puavo-reset-windows
--- a/parts/ltsp/puavo-install/puavo-reset-windows
+++ b/parts/ltsp/puavo-install/puavo-reset-windows
@@ -7,6 +7,7 @@ usage() {
   cat <<EOF
 $(basename "$0") [--mode reset-c-partition] [--force] [WIN_C_PARTITION_DEVPATH]
 $(basename "$0") --mode install-c-partition [--force] WIN_C_PARTITION_DEVPATH
+$(basename "$0") --mode install-re-partition [--force] WIN_C_PARTITION_DEVPATH WIN_RE_PARTITION_DEVPATH
 $(basename "$0") --mode install-boot-dir [--force] WIN_C_PARTITION_DEVPATH BOOT_DIR
 
 If --mode reset-c-partition is given, scans all block devices for
@@ -16,6 +17,9 @@ given, only it is reset, not all.
 
 If --mode install-c-partition is given, Windows Local Disk (C:)
 Partition is installed.
+
+If --mode install-re-partition is given, Windows Recovery Environment
+is installed.
 
 If --mode install-boot-dir is given, Windows bootmanager with all
 required files is installed to BOOT_DIR. Windows version is read form
@@ -34,6 +38,7 @@ g_use_force=false                       # --force sets to true
 g_lockfd=                               # Will be set when lockfile is opened
 g_mode='reset-c-partition'              # Operation mode
 g_win_c_partition_devpath=              # can be passed as arg, but if not given, all found C partitions will be reset
+g_win_re_partition_devpath=
 G_RESET_STATE_DIR=/state/windows
 G_WORK_DIR=/home/.puavo-reset-windows   # Where WIM files will be downloaded, mounted etc.
 G_WIM_CATALOGUE_PATH="${G_WORK_DIR}/wim.json"
@@ -591,6 +596,34 @@ choose_wim_image_to_use()
   printf "%s\n" "$preferred_versions"
 }
 
+erase_and_mkfs_ntfs()
+{
+  local partition_devpath
+
+  partition_devpath="$1"
+  shift
+
+  loginfo "Securely erasing '${partition_devpath}'"
+  wipefs -f -a "${partition_devpath}" || {
+    logerr "Failed to run wipefs to '${partition_devpath}'"
+    return 1
+  }
+  blkdiscard "${partition_devpath}" || {
+    logerr "Failed to run blkdiscard to '${partition_devpath}'"
+    return 1
+  }
+  loginfo "Secure erase done."
+
+  loginfo "Creating NTFS filesystem on '${partition_devpath}'..."
+  mkfs.ntfs -f "${partition_devpath}" || {
+    logerr "Failed to create NTFS filesystem on '${partition_devpath}'"
+    return 1
+  }
+  loginfo "Created NTFS filesystem on '${partition_devpath}'."
+
+  return 0
+}
+
 install_win()
 {
   local wim_image_baseurl wim_image_name win_language \
@@ -620,24 +653,7 @@ install_win()
 
   wim_image_index=$(print0_wim_image_index "$wim_image_name" "$win_product_name")
 
-  loginfo "Securely erasing '${win_c_partition_devpath}'"
-  wipefs -f -a "${win_c_partition_devpath}" || {
-    logerr "Failed to run wipefs to '${win_c_partition_devpath}'"
-    return 1
-  }
-  blkdiscard "${win_c_partition_devpath}" || {
-    logerr "Failed to run blkdiscard to '${win_c_partition_devpath}'"
-    return 1
-  }
-  loginfo "Secure erase done."
-
-  loginfo "Creating NTFS filesystem on '${win_c_partition_devpath}'..."
-  # Force needed to overwrite the existing filesystem without questions.
-  mkfs.ntfs -f "${win_c_partition_devpath}" || {
-    logerr "Failed to create NTFS filesystem on '${win_c_partition_devpath}'"
-    return 1
-  }
-  loginfo "Created NTFS filesystem on '${win_c_partition_devpath}'."
+  erase_and_mkfs_ntfs "${win_c_partition_devpath}" || return 1
 
   loginfo "Applying WIM image to '${win_c_partition_devpath}'..."
   wimapply "${wim_image_name}" "${wim_image_index}" "${win_c_partition_devpath}" || {
@@ -712,6 +728,60 @@ install_c_partition()
   }
 
   loginfo "Windows '${win_product_name} (${win_language})' on '${win_c_partition_devpath}' installed successfully."
+
+  return 0
+}
+
+install_re_partition()
+{
+  local win_c_mountpoint win_re_mountpoint
+
+  if [ -z "${g_win_c_partition_devpath}" ]; then
+    logerr 'WIN_C_PARTITION_DEVPATH cannot be empty'
+    return 1
+  fi
+
+  if [ -z "${g_win_re_partition_devpath}" ]; then
+    logerr 'WIN_RE_PARTITION_DEVPATH cannot be empty'
+    return 1
+  fi
+
+  # .mountpoint dirs are umounted automatically on_exit
+  win_c_mountpoint=$(mktemp -d -p . win_c.XXXXXXXXXX.mountpoint) || {
+    logerr 'Failed to create a mount point for Windows C partition!'
+    return 1
+  }
+  mount -o ro,nodev,nosuid "$g_win_c_partition_devpath" "$win_c_mountpoint" || {
+    logerr 'Failed to mount Windows C partition'
+    return 1
+  }
+
+  erase_and_mkfs_ntfs "${g_win_re_partition_devpath}" || return 1
+
+  # .mountpoint dirs are umounted automatically on_exit
+  win_re_mountpoint=$(mktemp -d -p . win_re.XXXXXXXXXX.mountpoint) || {
+    logerr 'Failed to create a mount point for Windows RE partition!'
+    return 1
+  }
+  mount -o nodev,nosuid "$g_win_re_partition_devpath" "$win_re_mountpoint" || {
+    logerr 'Failed to mount Windows RE partition'
+    return 1
+  }
+
+  mkdir -p "${win_re_mountpoint}/Recovery/WindowsRE" || {
+    logerr 'Failed to create WindowsRE directory'
+    return 1
+  }
+
+  cp -t "${win_re_mountpoint}/Recovery/WindowsRE" \
+     "${win_c_mountpoint}/Windows/System32/boot.sdi" \
+     "${win_c_mountpoint}/Windows/System32/Recovery/ReAgent.xml" \
+     "${win_c_mountpoint}/Windows/System32/Recovery/Winre.wim" || {
+    logerr 'Failed to copy WindowsRE files'
+    return 1
+  }
+
+  loginfo "Windows Recovery Environment on '${g_win_re_partition_devpath}' installed successfully."
 
   return 0
 }
@@ -861,6 +931,10 @@ while [ $# -ne 0 ]; do
           g_mode='install-c-partition'
           shift
           ;;
+        install-re-partition)
+          g_mode='install-re-partition'
+          shift
+          ;;
         *)
           logerr "invalid --mode value '$1'"
           usage
@@ -910,6 +984,24 @@ case "${g_mode}" in
     g_win_c_partition_devpath="$1"
     shift
     ;;
+  install-re-partition)
+    if [ $# -ne 2 ]; then
+      logerr 'positional arguments WIN_C_PARTITION_DEVPATH and WIN_RE_PARTITION_DEVPATH are required'
+      usage
+    fi
+    if [ -z "$1" ]; then
+      logerr 'WIN_C_PARTITION_DEVPATH cannot be empty'
+      usage
+    fi
+    g_win_c_partition_devpath="$1"
+    shift
+    if [ -z "$1" ]; then
+      logerr 'WIN_RE_PARTITION_DEVPATH cannot be empty'
+      usage
+    fi
+    g_win_re_partition_devpath="$1"
+    shift
+    ;;
   *)
     logerr "programming error, g_mode had invalid value '${g_mode}'"
     exit 1
@@ -946,6 +1038,9 @@ case "${g_mode}" in
     ;;
   install-c-partition)
     install_c_partition
+    ;;
+  install-re-partition)
+    install_re_partition
     ;;
   *)
     logerr "programming error, g_mode had invalid value '${g_mode}'"
