Added a check for USB thumbdrives, abort if user chooses one. USB Docks for M.2 and SATA drives seem to work no problem, as they report their bus as 'ata' just like normal internal hard drives.

diff --git a/parts/ltsp/puavo-install/puavo-disk-erase b/parts/ltsp/puavo-install/puavo-disk-erase
--- a/parts/ltsp/puavo-install/puavo-disk-erase
+++ b/parts/ltsp/puavo-install/puavo-disk-erase
@@ -16,8 +16,13 @@ secure_erase() {
     echo 'No disk selected, aborting!' >&2
     exit 1
   fi
-
+  
   echo "Chosen << ${target_disk} >>"
+  if udevadm info --query=all --name="${target_disk}" | grep 'ID_BUS=usb'; then
+    echo 'Selected disk is a USB device, I do not support them. Aborting..' >&2
+    exit 1
+  fi
+
   if ! hdparm -I "${target_disk}" | grep -P "SECURITY ERASE UNIT" >&2; then
     echo 'Selected disk does not support Secure Erase!' >&2
     exit 1
@@ -28,10 +33,10 @@ secure_erase() {
     echo 'Disk is in frozen state, aborting!' >&2
     echo 'Please close the lid of the device for a few seconds, reopen it and try again.' >&2
     echo
-    echo 'If we are netbooted, closing the lid will not put the device to sleep.'
-    echo 'We can however put it to sleep and wake it up with the usage of rtcwake.'
+    echo 'If we are netbooted, we can only put the device to sleep by running this command:'
+    echo 'echo -n mem > /sys/power/state'
     echo
-    read -p "Shall I run the command for you now? (y/n)[y] " gosleep
+    read -p "Shall I run the command for you? (y/n)[y] " gosleep
       case $gosleep in
         [yY]|"")
           echo 'Going to sleep now.'
