Changes to syntax and echo messages.
This was tested on a few disks and it seems to work without problems.

diff --git a/parts/ltsp/puavo-install/puavo-disk-erase b/parts/ltsp/puavo-install/puavo-disk-erase
--- a/parts/ltsp/puavo-install/puavo-disk-erase
+++ b/parts/ltsp/puavo-install/puavo-disk-erase
@@ -20,25 +20,27 @@ secure_erase() {
 
   echo "Chosen << ${target_disk} >>"
   if ! hdparm -I "${target_disk}" | grep -P "SECURITY ERASE UNIT" >&2; then
-    echo 'Selected disk does not support Secure Erase!'
+    echo 'Selected disk does not support Secure Erase!' >&2
     exit 1
-  else
-    echo 'Disk supports Secure Erase.'
-    if ! hdparm -I "${target_disk}" | grep -P "not\tfrozen" >&2; then
-      echo 'Disk is in frozen state, aborting. Please close the lid of the device for a few seconds.'
-    else
-      echo 'Disk is not in frozen state, we can continue.'
-      hdparm --user-master user --security-set-pass Pass "${target_disk}"
-      if hdparm -I "${target_disk}" | grep -P "Security level high" >&2; then
-        echo 'User and password set, ready for secure erase.'
-	hdparm --user-master user --security-erase Pass "${target_disk}"
-        echo 'Command completed. If you see no errors above, you may now reboot the device.'
-      else
-        echo 'Failed setting user and password, exiting.'
-	exit 1
-      fi
-    fi
   fi
+
+  echo 'Disk supports Secure Erase.'
+  if ! hdparm -I "${target_disk}" | grep -P "not\tfrozen" >&2; then
+    echo 'Disk is in frozen state, aborting!' >&2
+    echo 'Please close the lid of the device for a few seconds, reopen it and try again.' >&2
+    exit 1
+  fi
+
+  echo 'Disk is not in frozen state, we can continue.'
+  hdparm --user-master user --security-set-pass Pass "${target_disk}"
+  if ! hdparm -I "${target_disk}" | grep -P "Security level high" >&2; then
+    echo 'Failed setting user and password, exiting.' >&2
+    exit 1
+  fi
+
+  echo 'User and password set, ready for secure erase.'
+  hdparm --user-master user --security-erase Pass "${target_disk}"
+  echo 'Command completed. If you see no errors above, you may now reboot the device.'
 }
 
 secure_erase
