Replace tabs with whitespace, remove unnecessary commented stuff, some grammar changes.

diff --git a/parts/ltsp/puavo-install/puavo-disk-erase b/parts/ltsp/puavo-install/puavo-disk-erase
--- a/parts/ltsp/puavo-install/puavo-disk-erase
+++ b/parts/ltsp/puavo-install/puavo-disk-erase
@@ -5,7 +5,6 @@ set -eu
 ask_disk() {
   disks=$(awk '$4 ~ /^((md|mmcblk)[0-9]+|nvme[0-9]+n[0-9]+|[sv]d[a-z]|xvd[a-z])$/ {
                  print "/dev/"$4
-		 #print $4
                }' /proc/partitions)
   [ -n "$disks" ] || return 1
   printf %s "$disks" | fzf -1 --height=5 --layout=reverse-list
@@ -29,7 +28,7 @@ secure_erase() {
     echo 'Disk is in frozen state, aborting!' >&2
     echo 'Please close the lid of the device for a few seconds, reopen it and try again.' >&2
     echo
-    echo 'If we are netbooted, we can only put the device to sleep by issuing the following command:'
+    echo 'If we are netbooted, we can only put the device to sleep by running this command:'
     echo 'echo -n mem > /sys/power/state'
     echo
     read -p "Shall I run the command for you? (y/n)[y] " gosleep
@@ -40,12 +39,12 @@ secure_erase() {
           echo -n mem > /sys/power/state
           ;;
         [nN])
-          echo 'Not going to sleep. You must close the lid and reopen, or run the command by hand. Then retry.'
+          echo 'Not going to sleep. You must close and reopen the lid, or run the command by hand. Then retry.'
           sleep 1
           exit 1
           ;;
         *)
-          echo 'Invalid response, exiting.' >&2
+          echo 'Invalid answer, exiting.' >&2
           sleep 1
           exit 1
           ;;
