Support grub installation on mirrored RAID setup (on bootservers).

diff --git a/parts/ltsp/puavo-install/puavo-install-grub b/parts/ltsp/puavo-install/puavo-install-grub
--- a/parts/ltsp/puavo-install/puavo-install-grub
+++ b/parts/ltsp/puavo-install/puavo-install-grub
@@ -189,6 +189,23 @@ done
 EOF
 }
 
+find_grub_target_devices_on_raid() {
+  _diskdev=$1
+  mdadm --detail "$_diskdev" \
+    | awk '   $1 ~ /^[0-9]+$/ \
+           && $2 ~ /^[0-9]+$/ \
+           && $3 ~ /^[0-9]+$/ \
+           && $4 ~ /^[0-9]+$/ {
+             split($0, a)
+             for (i in a) {
+               if (a[i] ~ /^\/dev\/[a-z]+[0-9]+$/) {
+                  sub(/[0-9]+$/, "", a[i])
+                  print a[i]
+               }
+             }
+           }'
+}
+
 lookup_windows_partition_number() {
   # Presume that the first partition not containing "Linux"
   # is a Windows-partition.
@@ -259,14 +276,30 @@ diskdev=$(pvs 3>&- 4>&- 5>&-                                            \
             | awk -v vgname="$vgname" '$2 == vgname { print $1; exit }' \
             | sed -E '
                 /\/dev\/mmcblk/ { s|p[0-9]+$|| }
+                /\/dev\/md/     { s|p[0-9]+$|| }
                 /\/dev\/nvme/   { s|p[0-9]+$|| }
-                /\/dev\/[vs]d/  { s|[0-9]+$||  }
+                /\/dev\/[sv]d/  { s|[0-9]+$||  }
               ')
 
 if [ -z "$diskdev" ]; then
   echo "Could not find the disk device where volume group '${vgname}' is" >&2
   exit 1
 fi
+
+case "$diskdev" in
+  /dev/md*)
+    grub_target_devices=$(find_grub_target_devices_on_raid "$diskdev")
+    if [ -z "$grub_target_devices" ]; then
+      echo 'Could not find grub target devices on RAID configuration' >&2
+      exit 1
+    fi
+    possible_windows_disk_dev=''
+    ;;
+  *)
+    grub_target_devices="$diskdev"
+    possible_windows_disk_dev="$diskdev"
+    ;;
+esac
 
 if [ "$hosttype" = 'diskinstaller' ]; then
   puavo_lvm_partition='puavoinstaller-installimages'
@@ -295,12 +328,15 @@ if ! $only_update_config; then
   if [ -n "$grub_basedir" ]; then
     grub_install_args="--directory=${grub_basedir}/usr/lib/grub/i386-pc --locale-directory=${grub_basedir}/usr/share/locale"
   fi
-  if ! grub_msg=$(${grub_basedir}/usr/sbin/grub-install \
-    --boot-directory=${images_dir}/boot $grub_install_args "$diskdev" \
-      3>&- 4>&- 5>&- 2>&1); then
-        echo "Grub installation failed: $grub_msg" >&2
-        exit 1
-  fi
+
+  for grubdev in $grub_target_devices; do
+    if ! grub_msg=$(${grub_basedir}/usr/sbin/grub-install \
+      --boot-directory=${images_dir}/boot $grub_install_args "$grubdev" \
+        3>&- 4>&- 5>&- 2>&1); then
+          echo "Grub installation to $grubdev failed: $grub_msg" >&2
+          exit 1
+    fi
+  done
 
   "${grub_basedir}/usr/sbin/grub-install" --version \
     | awk '{ print $3 }' > "${images_dir}/boot/grub/version.tmp"
@@ -310,7 +346,7 @@ if ! $only_update_config; then
     exitstatus=1
   else
     mv "${images_dir}/boot/grub/version.tmp" "${images_dir}/boot/grub/version"
-    echo "Grub has been installed to ${diskdev}."
+    echo "Grub has been installed to ${grub_target_devices}."
   fi
 fi
 
@@ -322,10 +358,12 @@ grub_m4_template                                              \
        -D__PUAVO_LVM_PARTITION__="$puavo_lvm_partition"       \
   > "$tmp_grub_cfg_path"
 
-windows_partition_number=$(lookup_windows_partition_number "$diskdev")
+if [ -n "$possible_windows_disk_dev" ]; then
+  windows_partition_number=$(lookup_windows_partition_number \
+                               "$possible_windows_disk_dev")
 
-if [ -n "$windows_partition_number" ]; then
-  cat <<EOF >> "$tmp_grub_cfg_path"
+  if [ -n "$windows_partition_number" ]; then
+    cat <<EOF >> "$tmp_grub_cfg_path"
 
 menuentry "Windows" {
   insmod ntfs
@@ -333,6 +371,7 @@ menuentry "Windows" {
   chainloader +1
 }
 EOF
+  fi
 fi
 
 
@@ -349,12 +388,17 @@ fi
 # difficult to reproduce).
 sync
 echo 3 > /proc/sys/vm/drop_caches
-blockdev --flushbufs $diskdev
 
-case "$diskdev" in
-  /dev/[vs]d*)
-    hdparm -qF "$diskdev"
-    ;;
-esac
+for grubdev in $grub_target_devices; do
+  blockdev --flushbufs "$grubdev"
+done
+
+for grubdev in $grub_target_devices; do
+  case "$grubdev" in
+    /dev/[sv]d*)
+      hdparm -qF "$grubdev"
+      ;;
+  esac
+done
 
 exit $exitstatus
