Add logging to puavo-reset-laptop-to-factory-defaults.
Logging is often useful for admins.

diff --git a/parts/ltsp/puavo-install/puavo-reset-laptop-to-factory-defaults b/parts/ltsp/puavo-install/puavo-reset-laptop-to-factory-defaults
--- a/parts/ltsp/puavo-install/puavo-reset-laptop-to-factory-defaults
+++ b/parts/ltsp/puavo-install/puavo-reset-laptop-to-factory-defaults
@@ -6,6 +6,10 @@ set -o pipefail
 request_confirmation=true
 use_secure_delete=false
 
+logmsg() {
+  logger -t puavo-reset-laptop-to-factory-defaults -p "user.${1}" "$2" || true
+}
+
 destroy_in_dir() {
   local delete_cmd directory force_insecure message preserve_etc_puavo
 
@@ -106,6 +110,7 @@ fi
 
 for mnt in /home /images /state; do
   if ! mountpoint -q "$mnt"; then
+    logmsg err "${mnt} is not mounted, not continuing"
     echo "${mnt} is not mounted, not continuing" >&2
     exit 1
   fi
@@ -114,6 +119,7 @@ done
 puavo_hosttype=$(cat /etc/puavo/hosttype)
 
 if [ "$puavo_hosttype" != "laptop" ]; then
+  logmsg err 'unsuported hosttype'
   echo "I do not know how to wipe hosts of type '${puavo_hosttype}'" >&2
   exit 1
 fi
@@ -180,10 +186,13 @@ done
 
 resetstatus=0
 
+logmsg notice "starting reset operation (${operation})"
+
 if [ -b /dev/mapper/puavo-imageoverlays ]; then
   if ! mountpoint -q /imageoverlays; then
     if ! { mkdir -p /imageoverlays \
              && mount /dev/mapper/puavo-imageoverlays /imageoverlays; }; then
+      logmsg err 'could not mount imageoverlays'
       echo 'Could not mount imageoverlays' >&2
       resetstatus=1
     fi
@@ -194,54 +203,114 @@ cd /
 
 # Remove primary user (so that we will send this information
 # to Puavo through update-configuration).
-cat /dev/null > /state/etc/puavo/primary_user_override || resetstatus=1
-
-# we can speed up secure delete by not applying it to puavo-pkgs
-destroy_in_dir --force-insecure /images/puavo-pkg/ 'Removing all puavo-pkgs' \
-  || resetstatus=1
-
-destroy_in_dir /home/ 'Cleaning up home directories' || resetstatus=1
-destroy_in_dir /state/etc/puavo/local/ \
-               'Removing local configurations (made by user)' || resetstatus=1
-destroy_in_dir /state/var/cache/ 'Cleaning up caches' || resetstatus=1
-destroy_in_dir /state/var/lib/   'Removing some system configurations' \
-  || resetstatus=1
-
-{ /usr/lib/puavo-ltsp-install/update-configuration || true; } 2>&1 \
-  | pv -F '>>> Updating system configuration... %t' > /dev/null
-
-destroy_in_dir --force-insecure --preserve-etc-puavo /imageoverlays/ \
-               'Cleaning up most of /imageoverlays' || resetstatus=1
-destroy_in_dir /state/etc/NetworkManager/system-connections/ \
-               'Removing network manager connections' || resetstatus=1
-
-reset_override_path='/state/etc/puavo/reset_override'
-if ! write_reset_override "$operation" "$reset_override_path"; then
-  echo
-  echo 'Error in writing reset override' >&2
-  echo
+if cat /dev/null > /state/etc/puavo/primary_user_override; then
+  logmsg info 'wrote /state/etc/puavo/primary_user_override'
+else
+  logmsg err 'could not write /state/etc/puavo/primary_user_override'
   resetstatus=1
 fi
 
-if [ "$resetstatus" -eq 0 ] \
-  && ! send_state_reset_to_puavo "$reset_override_path"; then
-    {
-      echo
-      echo 'Failed to sending reset information to Puavo.  You may reboot'
-      echo 'this host, it tries to update the reset information later,'
-      echo 'but you may also remove it manually from the Puavo interface.'
-      echo
-    } >&2
-    resetstatus=1
+# we can speed up secure delete by not applying it to puavo-pkgs
+if destroy_in_dir --force-insecure /images/puavo-pkg/ \
+                    'Removing all puavo-pkgs'; then
+  logmsg info 'removed all puavo-pkgs'
+else
+  logmsg err 'error in removing all puavo-pkgs'
+  resetstatus=1
 fi
 
-destroy_in_dir --force-insecure /imageoverlays/ \
-               'Cleaning up all of /imageoverlays' || resetstatus=1
+if destroy_in_dir /home/ 'Cleaning up home directories'; then
+  logmsg notice 'cleaned up all home directories'
+else
+  logmsg err 'error in cleaning up home directories'
+  resetstatus=1
+fi
+
+if destroy_in_dir /state/etc/puavo/local/ \
+                    'Removing local configurations (made by user)'; then
+  logmsg info 'removed local configurations'
+else
+  logmsg err 'error in removing local configurations'
+  resetstatus=1
+fi
+
+if destroy_in_dir /state/var/cache/ 'Cleaning up caches'; then
+  logmsg info 'cleaned up caches'
+else
+  logmsg err 'error in cleaning up caches'
+  resetstatus=1
+fi
+
+if destroy_in_dir /state/var/lib/ 'Removing some system configurations'; then
+  logmsg info 'removed some system configurations'
+else
+  logmsg err 'error in removing some system configurations'
+  resetstatus=1
+fi
+
+{ /usr/lib/puavo-ltsp-install/update-configuration || true; } 2>&1 \
+  | pv -F '>>> Updating system configuration... %t' > /dev/null
+logmsg info 'system configuration update done'
+
+if destroy_in_dir --force-insecure --preserve-etc-puavo /imageoverlays/ \
+                    'Cleaning up most of /imageoverlays'; then
+  logmsg info 'cleaned up most of /imageoverlays'
+else
+  logmsg err 'error in cleaning up (most of) /imageoverlays'
+  resetstatus=1
+fi
+
+if destroy_in_dir /state/etc/NetworkManager/system-connections/ \
+               'Removing network manager connections'; then
+  logmsg info 'removed network manager configurations'
+else
+  logmsg err 'error in removing network manager configurations'
+  resetstatus=1
+fi
+
+reset_override_path='/state/etc/puavo/reset_override'
+if [ "$resetstatus" -eq 0 ]; then
+  if write_reset_override "$operation" "$reset_override_path"; then
+    logmsg info 'wrote reset override'
+    if send_state_reset_to_puavo "$reset_override_path"; then
+      logmsg notice 'sent reset state to puavo (with success)'
+    else
+      {
+        echo
+        echo 'Failed to sending reset information to Puavo.  You may reboot'
+        echo 'this host, it tries to update the reset information later,'
+        echo 'but you may also remove it manually from the Puavo interface.'
+        echo
+      } >&2
+      logmsg err 'failed sending reset state to puavo'
+      resetstatus=1
+    fi
+  else
+    echo
+    echo 'Error in writing reset override' >&2
+    echo
+    logmsg err 'error in writing reset override'
+    resetstatus=1
+  fi
+else
+  logmsg warning 'not sending reset state to puavo because of failures'
+fi
+
+if destroy_in_dir --force-insecure /imageoverlays/ \
+               'Cleaning up all of /imageoverlays'; then
+  logmsg info 'cleaned up all of /imageoverlays'
+else
+  logmsg warning 'error in cleaning up all of /imageoverlays'
+  resetstatus=1
+fi
 
 if [ "$resetstatus" -ne 0 ]; then
+  logmsg err 'errors occurred in device reset'
   echo 'Errors in device reset' >&2
   exit $resetstatus
 fi
+
+logmsg notice 'device reset finished with success!'
 
 i=5
 echo
