Use "puavo-check-available-space" in places where we are interested in the amount of available diskspace.

diff --git a/parts/ltsp/puavo-install/puavo-install-and-update-ltspimages b/parts/ltsp/puavo-install/puavo-install-and-update-ltspimages
--- a/parts/ltsp/puavo-install/puavo-install-and-update-ltspimages
+++ b/parts/ltsp/puavo-install/puavo-install-and-update-ltspimages
@@ -331,7 +331,11 @@ ensure_enough_available_diskspace() {
   required_diskspace=$(
     echo "${target_sizes_summed} - ${target_sizes_on_fs}" | bc -l)
 
-  diskspace=$(stat -f -c '%S * %a' "$images_dir" | bc -l | xargs printf %.0f)
+  if ! diskspace=$(/usr/lib/puavo-ltsp-client/puavo-check-available-space \
+                     "$images_dir"); then
+    log err 'could not determine available diskspace'
+    return 1
+  fi
 
   msg="checking if there is enough available diskspace:"
   msg="$msg diskspace:${diskspace} >= required_diskspace:$required_diskspace"
diff --git a/parts/pkg/puavo-pkg-wine-helper b/parts/pkg/puavo-pkg-wine-helper
--- a/parts/pkg/puavo-pkg-wine-helper
+++ b/parts/pkg/puavo-pkg-wine-helper
@@ -68,11 +68,14 @@ do_installation() {
 
   # if we have less than 2GB (2^31 bytes = 2147483648 bytes) available,
   # refuse to install
-  available_diskspace=$(stat -f -c '%S * %a' "$HOME" | bc -l) || true
-  if [ -z "$available_diskspace" \
-    -o "$available_diskspace" -lt 2147483648 ]; then
-      zenity --error --text 'not enough available diskspace for installation'
-      return 1
+  if ! available_diskspace=$(
+         /usr/lib/puavo-ltsp-client/puavo-check-available-space "$HOME"); then
+    zenity --error --text 'could not determine available diskspace'
+    return 1
+  fi
+  if [ "$available_diskspace" -lt 2147483648 ]; then
+    zenity --error --text 'not enough available diskspace for installation'
+    return 1
   fi
 
   # if a copy exists of an old version, make a base copy for the new version
diff --git a/rules/abitti2/files/puavo-update-abitti2-image b/rules/abitti2/files/puavo-update-abitti2-image
--- a/rules/abitti2/files/puavo-update-abitti2-image
+++ b/rules/abitti2/files/puavo-update-abitti2-image
@@ -259,8 +259,12 @@ ensure_enough_available_diskspace() {
   # or some such raise actual space requirements
   extra_space=262144
   required_diskspace=$(($abitti2_size + $extra_space - $tmpimage_size))
-  available_diskspace=$(stat -f -c '%S * %a' "$g_abitti2_dir" \
-                          | bc -l | xargs printf %.0f)
+  if ! available_diskspace=$(
+    /usr/lib/puavo-ltsp-client/puavo-check-available-space "$g_abitti2_dir")
+  then
+    error 'could not determine available diskspace'
+    return 1
+  fi
   if [ "$available_diskspace" -lt "$required_diskspace" ]; then
     msg="only ${available_diskspace} bytes available on ${g_abitti2_dir},"
     msg="${msg} need ${required_diskspace} bytes"
diff --git a/rules/homedir_management/files/puavo-cleanup-homedirs-to-ensure-free-space b/rules/homedir_management/files/puavo-cleanup-homedirs-to-ensure-free-space
--- a/rules/homedir_management/files/puavo-cleanup-homedirs-to-ensure-free-space
+++ b/rules/homedir_management/files/puavo-cleanup-homedirs-to-ensure-free-space
@@ -33,7 +33,7 @@ if [ -n "${PAM_USER:-}" ]; then
 fi
 
 get_freespace_amount() {
-  stat -f -c '%S * %a' /home | bc -l
+  /usr/lib/puavo-ltsp-client/puavo-check-available-space /home
 }
 
 lookup_oldest_file() {
@@ -43,7 +43,10 @@ lookup_oldest_file() {
 }
 
 while true; do
-  freespace_amount=$(get_freespace_amount)
+  if ! freespace_amount=$(get_freespace_amount); then
+    logmsg -p user.err 'could not lookup free available diskspace'
+    break
+  fi
   logmsg -p user.info \
          "/home has ${freespace_amount} bytes of free space, expecting ${freespace_min} bytes"
   if [ "$(get_freespace_amount)" -ge "$freespace_min" ]; then
