Adapt puavo-uninstall-uki-image to the new situation where the UKI kernels are under an image-specific directory.

diff --git a/parts/ltsp/puavo-install/puavo-uninstall-uki-image b/parts/ltsp/puavo-install/puavo-uninstall-uki-image
--- a/parts/ltsp/puavo-install/puavo-uninstall-uki-image
+++ b/parts/ltsp/puavo-install/puavo-uninstall-uki-image
@@ -1,4 +1,5 @@
 #!/bin/sh
+
 set -eu
 
 usage() {
@@ -16,7 +17,7 @@ if [ ! -f "$install_image" ]; then
   exit 1
 fi
 
-image_mountpoint="/images/mnt"
+image_mountpoint='/images/mnt'
 mkdir -p "$image_mountpoint"
 
 cleanup() {
@@ -28,22 +29,18 @@ trap cleanup EXIT
 # Mount the image read-only
 mount -o ro "$install_image" "$image_mountpoint"
 
-boot_directory="${image_mountpoint}/boot"
-if [ ! -d "$boot_directory" ]; then
-  echo "error: boot directory '$boot_directory' does not exist in image" >&2
-  exit 1
+if ! image_name=$(cat "${image_mountpoint}/etc/puavo-image/name") \
+  || [ -z "$image_name" ]; then
+    echo 'error: could not lookup image name' >&2
+    exit 1
 fi
-
-# If the mounted image does not contain UKIs, return fast
-uki_files=$(find "$boot_directory" -maxdepth 1 -name '*.uki.efi' -type f)
-
-if [ -z "$uki_files" ]; then
-  exit 0
-fi
+image_name_no_suffix=${image_name%.img}
 
 # Identify boot disks and remove UKI files from their EFI partitions
 PUAVO_INSTALL_LIBDIR="/usr/lib/puavo-ltsp-install"
 boot_disks=$("$PUAVO_INSTALL_LIBDIR"/puavo-get-boot-disks "$install_mountpoint")
+
+status=0
 
 for diskdev in $boot_disks; do
   efi_devpath=$(lsblk -n -l -o PATH,PARTTYPE "$diskdev" \
@@ -52,21 +49,22 @@ for diskdev in $boot_disks; do
 
   echo "removing old UKI files from boot device ${diskdev}"
 
-  efi_mount="/boot/efi"
+  efi_mount='/boot/efi'
   mkdir -p "$efi_mount"
-  mount "$efi_devpath" "$efi_mount" || true
+  if ! mount "$efi_devpath" "$efi_mount"; then
+    echo "could not mount ${efi_devpath} to ${efi_mount}" >&2
+    status=1
+    continue
+  fi
 
   uki_root="${efi_mount}/EFI/debian"
-
-  if [ -d "$uki_root" ]; then
-    for uki in "$boot_directory"/*.uki.efi; do
-      name=$(basename "$uki")
-      rm -f "${uki_root}/${name}" 2>/dev/null || true
-      rm -rf "${uki_root}/${name}.extra.d" 2>/dev/null || true
-    done
+  uki_kernels_dir="${uki_root}/${image_name_no_suffix}"
+  if ! rm --one-file-system -rf "$uki_kernels_dir"; then
+    echo "error in removing ${uki_kernels_dir}" >&2
+    status=1
   fi
 
   umount "$efi_mount" || true
 done
 
-exit 0
+exit $status
