Adapt puavo-update-uki-command-line to the new UKI naming convention.

diff --git a/parts/ltsp/puavo-install/puavo-update-uki-command-line b/parts/ltsp/puavo-install/puavo-update-uki-command-line
--- a/parts/ltsp/puavo-install/puavo-update-uki-command-line
+++ b/parts/ltsp/puavo-install/puavo-update-uki-command-line
@@ -2,18 +2,18 @@
 set -eu
 
 usage() {
-  echo "Usage: $0 <boot-directory> <uki-root> <host-type>" >&2
+  echo "Usage: $0 <image-mountpoint> <uki-root> <host-type>" >&2
   exit 1
 }
 
 [ $# -eq 3 ] || usage
 
-boot_directory="$1"
+image_mountpoint="$1"
 uki_root="$2"
 hosttype="$3"
 
-if [ ! -d "$boot_directory" ]; then
-  echo "error: boot directory '$boot_directory' does not exist" >&2
+if [ ! -d "$image_mountpoint" ]; then
+  echo "error: image mountpoint '$image_mountpoint' does not exist" >&2
   exit 1
 fi
 
@@ -25,20 +25,29 @@ fi
 install_command_line() {
   local uki="$1"
   local destination="$2"
-  local name
-  name=$(basename "$uki")
+  local image_name_no_suffix="$3"
 
-  local extra_directory="${destination}/${name}.extra.d"
+  local uki_name
+  uki_name=$(basename "$uki")
+
+  local extra_directory="${destination}/${image_name_no_suffix}/${uki_name}.extra.d"
   if ! mkdir -p "$extra_directory"; then
     echo "error: failed to create the extra directory for UKI in EFI partition" >&2
     return 1
   fi
 
   # Install the host type specific command line
-  cp "${boot_directory}/addons/${hosttype}.addon.efi" \
-     "${extra_directory}/cmdline.addon.efi" || true
+  cp -p "${image_mountpoint}/boot/addons/${hosttype}.addon.efi" \
+        "${extra_directory}/cmdline.addon.efi" || true
 }
 
-for uki in "$boot_directory"/*.uki.efi; do
-  install_command_line "$uki" "$uki_root"
+if ! image_name="$(cat "${image_mountpoint}/etc/puavo-image/name")" \
+  || [ -z "$image_name" ]; then
+    echo 'could not determine image name' >&2
+    exit 1
+fi
+image_name_no_suffix=${image_name%.img}
+
+for uki in "${image_mountpoint}/boot"/*.uki.efi; do
+  install_command_line "$uki" "$uki_root" "$image_name_no_suffix"
 done
