Introduce "--noconfirm" flag to puavo-disk-erase. This enables running it without (much) user interaction.

diff --git a/parts/ltsp/puavo-install/puavo-disk-erase b/parts/ltsp/puavo-install/puavo-disk-erase
--- a/parts/ltsp/puavo-install/puavo-disk-erase
+++ b/parts/ltsp/puavo-install/puavo-disk-erase
@@ -50,30 +50,36 @@ secure_erase() {
 
       echo 'Disk supports Secure Erase.'
       if ! hdparm -I "${target_disk}" | grep -P "not\tfrozen" >&2; then
-        echo 'Disk is in frozen state, cannot continue!' >&2
-        echo 'Please close the lid of the device for a few seconds, reopen it and try again.' >&2
-        echo
-        echo 'If we are netbooted, closing the lid will not put the device to sleep.'
-        echo 'We can however put it to sleep and wake it up with the usage of rtcwake.'
-        echo
-        read -p "Shall I run the command for you now? (y/n)[y] " gosleep
-        case $gosleep in
-          [yY]|"")
-            echo 'Going to sleep now.'
-            sleep 1
-            rtcwake -m mem -s 5
-            ;;
-          [nN])
-            echo 'Not going to sleep. You must close and reopen the lid, or run the command by hand. Then retry.'
-            sleep 1
-            exit 1
-            ;;
-          *)
-            echo 'Invalid answer, exiting.' >&2
-            sleep 1
-            exit 1
-            ;;
-        esac
+        if [ "$1" = "--noconfirm" ]; then
+          echo '"Flag "--noconfirm" was given.'
+          echo 'Disk is in frozen state! Going to sleep now.'
+          rtcwake -m mem -s 5
+        else
+          echo 'Disk is in frozen state, cannot continue!' >&2
+          echo 'Please close the lid of the device for a few seconds, reopen it and try again.' >&2
+          echo
+          echo 'If we are netbooted, closing the lid will not put the device to sleep.'
+          echo 'We can however put it to sleep and wake it up with the usage of rtcwake.'
+          echo
+          read -p "Shall I run the command for you now? (y/n)[y] " gosleep
+          case $gosleep in
+            [yY]|"")
+              echo 'Going to sleep now.'
+              sleep 1
+              rtcwake -m mem -s 5
+              ;;
+            [nN])
+              echo 'Not going to sleep. You must close and reopen the lid, or run the command by hand. Then retry.'
+              sleep 1
+              exit 1
+              ;;
+            *)
+              echo 'Invalid answer, exiting.' >&2
+              sleep 1
+              exit 1
+              ;;
+          esac
+        fi
       fi
 
       echo 'Disk is not in frozen state, we can continue.'
@@ -103,4 +109,4 @@ secure_erase() {
   esac
 }
 
-secure_erase
+secure_erase "${1:+$1}"
