puavo-manage-efi: use existing ESP mount point or /boot/efi if not mounted

diff --git a/parts/ltsp/puavo-install/puavo-manage-efi b/parts/ltsp/puavo-install/puavo-manage-efi
--- a/parts/ltsp/puavo-install/puavo-manage-efi
+++ b/parts/ltsp/puavo-install/puavo-manage-efi
@@ -45,13 +45,20 @@ efibootmgr_windows() {
 }
 
 mount_efi_system_partition() {
-  efi_system_partition_devpath=$(lsblk -n -l -o PATH,PARTTYPE | awk '$2 == "c12a7328-f81f-11d2-ba4b-00a0c93ec93b" {print $1}')
-
-  efi_system_partition_mountpath=$(mktemp -d -p / EFI_SYSTEM_PARTITION.XXXXXXXXXXXX)
-  mount -onodev,nosuid "${efi_system_partition_devpath}" "${efi_system_partition_mountpath}" || {
-    rm -rf "${efi_system_partition_mountpath}"
+  efi_system_partition_devpath=$(lsblk -n -l -o PATH,PARTTYPE | awk '$2 == "c12a7328-f81f-11d2-ba4b-00a0c93ec93b" {print $1}') || return 1
+  if [ -z "${efi_system_partition_devpath}" ]; then
+    logerr 'EFI system partition not found'
     return 1
-  }
+  fi
+
+  efi_system_partition_mountpath=$(awk "-vdev=${efi_system_partition_devpath}" '$1 == dev {print $2}' /proc/mounts) || return 1
+
+  # Mount only if not already mounted.
+  if [ -z "${efi_system_partition_mountpath}" ]; then
+    efi_system_partition_mountpath=/boot/efi
+    mkdir -p "${efi_system_partition_mountpath}" || return 1
+    mount -onodev,nosuid "${efi_system_partition_devpath}" "${efi_system_partition_mountpath}" || return 1
+  fi
 
   echo "${efi_system_partition_mountpath}"
 }
@@ -69,14 +76,12 @@ efi_break_windows() {
     defused_windows_tmpfile=$(mktemp -p "${efi_mount_path}/EFI" 'Puavo-defused-Windows.tar.gz.tmp.XXXXXXXX')
     tar -C "${efi_mount_path}/EFI" -z -c -f "${defused_windows_tmpfile}" Microsoft || {
       rm -rf "${defused_windows_tmpfile}" || true
-      umount "${efi_mount_path}" || return 1
-      rm -rf "${efi_mount_path}"
+      umount "${efi_mount_path}"
       return 1
     }
     mv "${defused_windows_tmpfile}" "${efi_mount_path}/EFI/Puavo-defused-Windows.tar.gz"
     rm -rf "${efi_mount_path}/EFI/Microsoft" || {
-      umount "${efi_mount_path}" || return 1
-      rm -rf "${efi_mount_path}"
+      umount "${efi_mount_path}"
       return 1
     }
     loginfo 'Windows defused.'
@@ -84,8 +89,7 @@ efi_break_windows() {
     loginfo 'Nothing to do.'
   fi
 
-  umount "${efi_mount_path}" || return 1
-  rm -rf "${efi_mount_path}"
+  umount "${efi_mount_path}"
 }
 
 efi_fix_windows() {
@@ -99,13 +103,11 @@ efi_fix_windows() {
     fi
     tar -C "${efi_mount_path}/EFI" -z -x -f "${efi_mount_path}/EFI/Puavo-defused-Windows.tar.gz" || {
       rm -rf "${efi_mount_path}/EFI/Microsoft" || true
-      umount "${efi_mount_path}" || return 1
-      rm -rf "${efi_mount_path}"
+      umount "${efi_mount_path}"
       return 1
     }
     rm -f "${efi_mount_path}/EFI/Puavo-defused-Windows.tar.gz" || {
-      umount "${efi_mount_path}" || return 1
-      rm -rf "${efi_mount_path}"
+      umount "${efi_mount_path}"
       return 1
     }
     loginfo 'Windows reprimed.'
@@ -113,8 +115,7 @@ efi_fix_windows() {
     loginfo 'Nothing to do.'
   fi
 
-  umount "${efi_mount_path}" || return 1
-  rm -rf "${efi_mount_path}"
+  umount "${efi_mount_path}"
 }
 
 efi_disable_windows() {
