bootserver: add --network option to filter client queries

diff --git a/parts/ltsp/bootserver/bin/puavo-bootserver-list-clients b/parts/ltsp/bootserver/bin/puavo-bootserver-list-clients
--- a/parts/ltsp/bootserver/bin/puavo-bootserver-list-clients
+++ b/parts/ltsp/bootserver/bin/puavo-bootserver-list-clients
@@ -4,19 +4,64 @@
 
 set -eu
 
+usage_error()
+{
+    echo "ERROR: $1" >&2
+    echo "Try '$0 --help' for more information". >&2
+    return 1
+}
+
+network=255.255.255.255/0
+
+print_help()
+{
+    echo "Usage: $0 [OPTIONS]"
+    echo
+    echo 'List NFS/NBD/SMB clients.'
+    echo
+    echo 'Options:'
+    echo '    -n, --network CIDR      limit listing to network'
+    echo '    -h, --help              print help and exit'
+    echo
+}
+
+while [ $# -gt 0 ]; do
+    case $1 in
+	-h|--help)
+	    shift
+	    print_help
+	    exit 0
+	    ;;
+	-n|--network)
+	    shift
+	    [ $# -gt 0 ] || usage_error 'option -n requires an argument'
+	    network=$1
+	    shift
+	    ;;
+	--)
+	    shift
+	    break
+	    ;;
+	-*)
+	    usage_error "invalid argument '$1'"
+	    ;;
+	*)
+	    break
+	    ;;
+    esac
+done
+
 if [ $# -ne 0 ]; then
     echo "ERROR: invalid number of arguments ($#), expected 0" >&2
     exit 1
 fi
 
-netstat -W -o \
-    | while read proto _ _ local_addr remote_addr state _ _; do
-    [ "${proto}" = tcp ] || continue
-    [ "${state}" = ESTABLISHED ] || continue
+ss -t -r state established dst "${network}": | tail -n+2 \
+    | while read recvq sendq local_addr remote_addr; do
     local_port=$(echo "${local_addr}" | cut -d: -f2)
 
     case "${local_port}" in
-	nfs)
+	rpc.nfs)
 	    conn_type="NFS"
 	    ;;
 	nbd)
