Don't fail the networking.service process when an error occurs executing disable_flow_control.

diff --git a/rules/bootserver_network_interfaces/templates/etc/network/if-up.d/disable_flow_control b/rules/bootserver_network_interfaces/templates/etc/network/if-up.d/disable_flow_control
--- a/rules/bootserver_network_interfaces/templates/etc/network/if-up.d/disable_flow_control
+++ b/rules/bootserver_network_interfaces/templates/etc/network/if-up.d/disable_flow_control
@@ -10,5 +10,6 @@ if [ "$puavo_hosttype" != 'bootserver' ]; then
 fi
 
 if [[ "$IFACE" =~ ^ltsp[0-9.]+$ ]]; then
-  /sbin/ethtool -A $IFACE autoneg off rx off tx off
+  /sbin/ethtool -A $IFACE autoneg off rx off tx off \
+    || echo "Error: /etc/network/if-up.d/disable_flow_control failed for $IFACE"
 fi
