Make ti-nspire-cx-cas work, mostly.  Upgrades might also work.

diff --git a/parts/pkg/packages/ti-nspire-cx-cas/rules b/parts/pkg/packages/ti-nspire-cx-cas/rules
--- a/parts/pkg/packages/ti-nspire-cx-cas/rules
+++ b/parts/pkg/packages/ti-nspire-cx-cas/rules
@@ -5,49 +5,93 @@ set -eu
 command=$1
 shift
 
-install_installer_script() {
-  cat <<'EOF' > /usr/local/bin/ti-nspire-cx-cas
-#!/bin/sh
+wrapper_script_path=/usr/local/bin/ti-nspire-cx-cas
 
-set -eu
+install_wrapper_script() {
+  cat <<'EOF' > "$wrapper_script_path"
+#!/bin/sh
 
 installer_msi_path='/usr/share/puavo-pkg/installers/ti_nspire_cx_cas_installer.msi'
 
-final_wineprefix=~/.wine-ti-nspire-cx-cas-4.5.0.1180
+link_wineprefix=~/.wine-puavo-ti-nspire-cx-cas
+version_wineprefix="${link_wineprefix}-4.5.0.118"
 
-program_exe_dir="${final_wineprefix}/drive_c/Program Files (x86)/TI Education/TI-Nspire CX CAS Student Software"
+program_exe_dir="drive_c/Program Files/TI Education/TI-Nspire CX CAS Student Software"
 program_exe_name='TI-Nspire CX CAS Student Software.exe'
 program_exe_path="${program_exe_dir}/${program_exe_name}"
 
 export WINEARCH=win32
 
-# XXX how should we support:
-# XXX   1. installing new version
-# XXX   2. updating an old version to new version (safely!)
-# XXX   3. allowing user to use the old version without nagging him/her to update?
+# we should support:
+#   1. installing a new version
+#   2. updating an old version to a new version (safely!)
+#   3. allowing user to use the old version without nagging him/her
+#      to update? (use a timestamp to periodically check for it?)
+#   4. perhaps cleaning up old versions?
 
-if [ ! -d "$final_wineprefix" ]; then
-  export WINEPREFIX="${final_wineprefix}.tmp"
+do_installation() {
+  export WINEPREFIX="${version_wineprefix}.tmp"
 
-  rm -rf "${final_wineprefix}.tmp"
+  rm -rf "${version_wineprefix}.tmp"
 
+  # if we have less than 2GB (2^31 bytes = 2147483648 bytes) available,
+  # refuse to install
+  available_diskspace=$(stat -f -c '%S * %a' "$HOME" | bc -l) || true
+  if [ -z "$available_diskspace" \
+    -o "$available_diskspace" -lt 2147483648 ]; then
+      zenity --error --text 'not enough available diskspace for installation'
+      return 1
+  fi
+
+  # if a copy exists of an old version, make a base copy for the new version
+  # before attempting upgrade
+  old_installation=$(readlink "$link_wineprefix" 2>/dev/null) || true
+  if [ -d "$old_installation" ]; then
+    last_old_installation_update_check=$(
+      stat -c %Y "${old_installation}/.latest_update_check" 2>/dev/null || true)
+
+    # if we have not bothered the user about updating in over a week,
+    # bother again
+    if [ -z "$last_old_installation_update_check" \
+      -o "$last_old_installation_update_check" \
+        -lt "$(($(date +%s) - 7*24*60*60))" ]; then
+      touch "${old_installation}/.latest_update_check"
+      msg='There is an update available for TI Nspire'
+      if ! zenity --question --text "$msg" --cancel-label 'maybe later' \
+        --ok-label 'UPDATE NOW'; then
+          # user did not click 'UPDATE NOW'
+          return 1
+      fi
+    fi
+
+    rsync -a "$old_installation" "$version_wineprefix"
+    # XXX should program_exe_path be removed so that update check is more
+    # XXX reliable?  how should we check update was successful?
+  fi
+
+  winetricks settings win7
   msiexec /i "$installer_msi_path"
 
-  if [ ! -e "$program_exe_path" ]; then
-    echo 'error occurred during installation' >&2
+  if [ ! -e "${WINEPREFIX}/${program_exe_path}" ]; then
+    zenity --error --text 'error occurred during installation'
     exit 1
   fi
 
-  ln -fns "$(basename "$final_wineprefix")" ~/.wine-ti-nspire-cx-cas
-  mv "$WINEPREFIX" "$final_wineprefix"
+  # XXX should do atomically both
+  mv "$WINEPREFIX" "$version_wineprefix"
+  ln -fns "$(basename "$version_wineprefix")" "$link_wineprefix"
+}
+
+if [ ! -d "$version_wineprefix" ]; then
+  do_installation || true
 fi
 
-export WINEPREFIX=~/.wine-ti-nspire-cx-cas
+export WINEPREFIX="$link_wineprefix"
 
-cd "$program_exe_dir"
+cd "${WINEPREFIX}/${program_exe_dir}"
 wine "$program_exe_name"
 EOF
-  chmod 755 /usr/local/bin/ti-nspire-cx-cas
+  chmod 755 "$wrapper_script_path"
 }
 
 case "$command" in
@@ -56,7 +100,7 @@ case "$command" in
     mkdir -p /usr/share/puavo-pkg/installers
     ln -fns "${upstream_dir}/TINspireCXCASStudentSoftware-4.5.0.1180.msi" \
             /usr/share/puavo-pkg/installers/ti_nspire_cx_cas_installer.msi
-    install_installer_script
+    install_wrapper_script
     ;;
 
   unconfigure)
