Create checksum file to correct path.

diff --git a/.aux/build-debs b/.aux/build-debs
--- a/.aux/build-debs
+++ b/.aux/build-debs
@@ -50,25 +50,27 @@ fi
 
 echo "Building ${srcpkgname}"
 
-cd "${pkgworkdir}/${srcpkgname}"
-debian/scripts/get-orig-source
+(
+  cd "${pkgworkdir}/${srcpkgname}"
+  debian/scripts/get-orig-source
 
-current_deb_version="$(dpkg-parsechangelog -S version \
-			 | sed -E 's/\+build[0-9]+$//')"
-if [ -z "$current_deb_version" ]; then
-  echo "Could not determine package version for ${srcpkgname}." >&2
-  exit 1
-fi
+  current_deb_version="$(dpkg-parsechangelog -S version \
+			   | sed -E 's/\+build[0-9]+$//')"
+  if [ -z "$current_deb_version" ]; then
+    echo "Could not determine package version for ${srcpkgname}." >&2
+    exit 1
+  fi
 
-if ! echo "$current_deb_version" | grep -q '\+buildonce$'; then
-  new_deb_version="${current_deb_version}+build$(date +%s)"
-  env DEBFULLNAME="Puavo Org" DEBEMAIL="dev@opinsys.fi" \
-    dch --newversion "$new_deb_version" \
-      "Automatic build for puavo-os on $(env LANG=C date)."
-    dch --distribution "$(lsb_release -cs)" --release ''
-fi
+  if ! echo "$current_deb_version" | grep -q '\+buildonce$'; then
+    new_deb_version="${current_deb_version}+build$(date +%s)"
+    env DEBFULLNAME="Puavo Org" DEBEMAIL="dev@opinsys.fi" \
+      dch --newversion "$new_deb_version" \
+	"Automatic build for puavo-os on $(env LANG=C date)."
+      dch --distribution "$(lsb_release -cs)" --release ''
+  fi
 
-dpkg-buildpackage -sa -uc -us
-../../../../parts/devscripts/bin/do-debpool-changes -m "$pooldir"
+  dpkg-buildpackage -sa -uc -us
+  ../../../../parts/devscripts/bin/do-debpool-changes -m "$pooldir"
+)
 
 echo "$current_srctree_checksum" > "$checksum_file"
