bs-release-create: accept version as an optional argument

diff --git a/apt-repositories/bs-release-create b/apt-repositories/bs-release-create
--- a/apt-repositories/bs-release-create
+++ b/apt-repositories/bs-release-create
@@ -2,15 +2,19 @@
 
 set -eu
 
-if [ $# -ne 0 ]; then
-    echo "E: invalid number of arguments ($#), expected 0" >&2
-    exit 1
-fi
-
 cd /srv/aptirepo
 
 old_version=$(readlink latest)
-new_version=$((old_version + 1))
+
+if [ $# -eq 0 ]; then
+    new_version=$((old_version + 1))
+elif [ $# -eq 1 ]; then
+    new_version=$1
+    shift
+else
+    echo "E: invalid number of arguments ($#), expected 0" >&2
+    exit 1
+fi
 
 if [ -e "${new_version}" ]; then
     echo "E: version ${new_version} already exists" >&2
