Use cache for restricted packages if cache exists and has some stuff.  Includes software packs and license file.

diff --git a/parts/ltsp/client/restricted-packages/lib/commands/downloadlicense b/parts/ltsp/client/restricted-packages/lib/commands/downloadlicense
--- a/parts/ltsp/client/restricted-packages/lib/commands/downloadlicense
+++ b/parts/ltsp/client/restricted-packages/lib/commands/downloadlicense
@@ -48,12 +48,13 @@ while [ $# -gt 0 ]; do
             echo
             exit 0
             ;;
-	--all)
-	    shift
-	    packages=$(puavo-restricted-package-tool list | awk '{ print $1 }')
-	    set -- ${packages}
-	    break
-	    ;;
+        --all)
+            shift
+            packages=$(puavo-restricted-package-tool list | awk '{ print $1 }')
+            set -- ${packages}
+            [ $# -eq 0 ] && exit 0
+            break
+            ;;
         --)
             shift
             break
@@ -75,10 +76,10 @@ exitval=0
 
 for package in "$@"; do
     "${RESTRICTED_PKG_LIBDIR}/helpers/downloadlicense" "${package}" || {
-	exitval=$?
-	echo "E: failed to download package license for '${package}'" >&2
-	# Continue until we have tried to download all given package licenses
-	# and then fail.
+        exitval=$?
+        echo "E: failed to download package license for '${package}'" >&2
+        # Continue until we have tried to download all given package licenses
+        # and then fail.
     }
 done
 
