ap: do not set txpower on laptops

diff --git a/parts/wlan/ap/lib/set-txpower b/parts/wlan/ap/lib/set-txpower
--- a/parts/wlan/ap/lib/set-txpower
+++ b/parts/wlan/ap/lib/set-txpower
@@ -5,6 +5,12 @@ set -eu
 txpower=$(jq -r '.tags[]' /etc/puavo/device.json | sed -r -n 's/^txpower://p' | tail -n1)
 txpower5=$(jq -r '.tags[]' /etc/puavo/device.json | sed -r -n 's/^txpower5://p' | tail -n1)
 
+hosttype=$(cat /etc/puavo/hosttype)
+if [ "${hosttype}" = laptop ]; then
+    echo "ERROR: tried to set txpower on laptop, aborting" >&2
+    exit 1
+fi
+
 if [ -n "${txpower}" ]; then
     iwconfig "${INTERFACE}" txpower "${txpower}"
 fi
