Make pre-push fail if debian/changelog is not part of the HEAD

diff --git a/parts/devscripts/share/git-hooks/pre-push b/parts/devscripts/share/git-hooks/pre-push
--- a/parts/devscripts/share/git-hooks/pre-push
+++ b/parts/devscripts/share/git-hooks/pre-push
@@ -45,6 +45,11 @@ on_exit()
     exit $exitvalue
 }
 
+if [ -z "$(git ls-tree HEAD debian/changelog)" ]; then
+    echo 'error: debian/changelog is not part of the HEAD tree' >&2
+    exit 1
+fi
+
 if [ ! -d debian/changelog ]; then
     echo 'error: debian/changelog is missing' >&2
     exit 1
