parts/ltsp: client: darkdm: output error messages to stderr

diff --git a/parts/ltsp/client/lib/darkdm b/parts/ltsp/client/lib/darkdm
--- a/parts/ltsp/client/lib/darkdm
+++ b/parts/ltsp/client/lib/darkdm
@@ -35,8 +35,7 @@ while true; do
 	    print_help
 	    ;;
 	*)
-	    echo "Invalid command '${command}'"
-	    echo "Type 'help' to get help"
+	    echo "Error: Invalid command '${command}'. Try 'help'." >&2
 	;;
     esac
 done
