Use cleaner json data gathering and amend with resolution data.

diff --git a/parts/ltsp/client/lib/darkdm b/parts/ltsp/client/lib/darkdm
--- a/parts/ltsp/client/lib/darkdm
+++ b/parts/ltsp/client/lib/darkdm
@@ -662,29 +662,10 @@ darkdm_main()
   darkdm_menu "$initial_command" "$forced" || return 1
 }
 
-gather_device_data()
-{
-#"battery": "$(upower --show-info /org/freedesktop/UPower/devices/battery_BAT0 \
-#  |grep 'vendor:\|model:\|serial:\|capacity:\|percentage:\|voltage:' 2>/dev/null || true)",
-  cat <<EOF
-{
-
-"bios": "$(facter dmi.bios.vendor) / $(facter dmi.bios.version)",
-"cpu": "$(facter processors.models.1)",
-"disks": $(facter --json disks | jq -r '.disks '),
-"manufacturer": "$(facter dmi.manufacturer)",
-"memory": "$(facter memory.system.total_bytes) $(facter memory.system.total)",
-"model": "$(facter dmi.product.name)",
-"resolution": "`cat /sys/class/graphics/fb0/virtual_size`",
-"serialnum": "$(facter dmi.product.serial_number)"
-}
-EOF
-}
-
-
 # get preseed, we might need it
 echo -n 'Getting preseed and device identifier (if server can be found)... '
 preseed_json=''
+sysinfo_json=''
 device_identifier=''
 if image_server=$(/usr/lib/puavo-ltsp-client/lookup-image-server-by-dns); then
   preseed_url="https://${image_server}/preseeds/index.json"
@@ -693,10 +674,19 @@ if image_server=$(/usr/lib/puavo-ltsp-client/lookup-image-server-by-dns); then
     preseed_json=''
   fi
   deviceid_url="https://${image_server}/deviceid"
-  if ! device_identifier=$(curl --cacert /etc/puavo-conf/rootca.pem  \
-                           -d "$(gather_device_data)" --fail  -H "Content-Type: application/json" --max-time 5 --silent \
-                           -X POST "$deviceid_url"); then
-    device_identifier=''
+  if sysinfo_json=$(
+    dbus-send --system --dest=org.puavo.client.systeminfocollectordaemon \
+              --print-reply=literal /systeminfocollector \
+              org.puavo.client.systeminfocollector.CollectSysinfo \
+              | jq --arg nresolution "`cat /sys/class/graphics/fb0/virtual_size`" \
+              '. + {"resolution": $nresolution}'); then
+        if ! device_identifier=$(curl --cacert /etc/puavo-conf/rootca.pem  \
+                            -d "${sysinfo_json}" --fail  -H "Content-Type: application/json" --max-time 5 --silent \
+                            -X POST "$deviceid_url"); then
+            device_identifier=''
+        fi
+  else
+    device_identifier='-'
   fi
 fi
 if [ -n "$preseed_json" ]; then
@@ -707,6 +697,9 @@ fi
 
 if [ "$device_identifier" == "n/a" ]; then
   echo 'Device backend not enabled.'
+  device_identifier=''
+elif [ "$device_identifier" == "-" ]; then
+  echo 'Error during device data gathering.'
   device_identifier=''
 elif [ -n "$device_identifier" ]; then
   echo 'Device identifier OK.'
