Just formatting.  (In infotv-session -script, wrap lines to 80 columns, and to make that feasible, use 2-column indent).

diff --git a/parts/ltsp/client/lib/infotv-session b/parts/ltsp/client/lib/infotv-session
--- a/parts/ltsp/client/lib/infotv-session
+++ b/parts/ltsp/client/lib/infotv-session
@@ -6,39 +6,42 @@ set -eu
 
 run_idid()
 {
-	# Hide the mouse cursor except when moving
-	unclutter -idle 0.1 -root &
+  # Hide the mouse cursor except when moving
+  unclutter -idle 0.1 -root &
 
-	# Start idid and keep it running
-	while true; do
-		idid || true
-		logger -p local0.err -t infotv "The idid process has exited or crashed, restarting it..."
-		sleep 5
-	done
+  # Start idid and keep it running
+  while true; do
+    idid || true
+    logger -p local0.err -t infotv \
+           'The idid process has exited or crashed, restarting it...'
+    sleep 5
+  done
 }
 
 run_iivari()
 {
-	# Clean up iivari's cache
-	rm -rf /home/infotv/.iivari >/dev/null 2>&1
+  # Clean up iivari's cache
+  rm -rf /home/infotv/.iivari >/dev/null 2>&1
 
-	# Start iivari and keep it running
-	while true; do
-		iivari_kiosk_domain="$(cat /etc/puavo/domain)"
-		iivari-kiosk --urlbase "https://${iivari_kiosk_domain}/infotv/conductor" || true
-		logger -p local0.err -t infotv "The iivari process has exited or crashed, restarting it..."
-		sleep 5
-	done
+  # Start iivari and keep it running
+  while true; do
+    iivari_kiosk_domain="$(cat /etc/puavo/domain)"
+    iivari-kiosk --urlbase "https://${iivari_kiosk_domain}/infotv/conductor" \
+      || true
+    logger -p local0.err -t infotv \
+           'The iivari process has exited or crashed, restarting it...'
+    sleep 5
+  done
 }
 
 # Start openbox and keep it running
 (
-	while true; do
-		openbox || true
-		logger -p local0.err -t infotv \
-                       'openbox has exited or crashed, restarting it...'
-		sleep 5
-	done
+  while true; do
+    openbox || true
+    logger -p local0.err -t infotv \
+           'openbox has exited or crashed, restarting it...'
+    sleep 5
+  done
 ) &
 
 # Disable screen blanking and power saving features
@@ -50,23 +53,25 @@ xset -dpms
 
 # Run the specified software
 case "$(puavo-conf puavo.infotv.software)" in
-	iivari)
-		run_iivari
-		break
-		;;
-	idid)
-		run_idid
-		break
-		;;
-	*)
-		while true; do
-			logger -p local0.err -t infotv "Invalid/missing signage software specified in puavo.infotv.software"
-			sleep 300
-		done
-		break
-		;;
+  iivari)
+    run_iivari
+    break
+    ;;
+  idid)
+    run_idid
+    break
+    ;;
+  *)
+    while true; do
+      logger -p local0.err -t infotv \
+             'Invalid/missing software specified in puavo.infotv.software'
+      sleep 300
+    done
+    break
+    ;;
 esac
 
 # We should never get here...
-logger -p local0.err -t infotv "The info-tv-session script is exiting! This should not happen!"
+logger -p local0.err -t infotv \
+       'The info-tv-session script is exiting! This should not happen!'
 exit 1
