Merge code from puavo-install-ltspimages to puavo-install-and-update-ltspimages. The puavo-install-ltspimages -part is not functional yet.

diff --git a/puavo-install/puavo-install-and-update-ltspimages b/puavo-install/puavo-install-and-update-ltspimages
--- a/puavo-install/puavo-install-and-update-ltspimages
+++ b/puavo-install/puavo-install-and-update-ltspimages
@@ -226,7 +226,6 @@ get_rdiff() {
   log notice "new rdiff file $rdiff_filename has been put into its place"
 }
 
-# XXX somewhat duplicate code with build_rdiffs.sh
 get_rdiff_filename() {
   previous_image_name=$1
   next_image_name=$2
@@ -252,7 +251,20 @@ get_rdiff_filename() {
       '
 }
 
-# XXX duplicate code with puavo-install-ltspimages
+lookup_image_server_from_dns() {
+  puavo_domain=$(cat /etc/puavo/domain)
+  image_server=$(
+    dig SRV "_imageserver._tcp.${puavo_domain}" +search +short \
+      | awk '{ sub(/\.$/, ""); printf "%s:%s", $4, $3 }')
+
+  if [ -z "$image_server" ]; then
+    log err "could not find the image server from DNS"
+    return 1
+  else
+    echo "$image_server"
+  fi
+}
+
 lookup_ltspimage_name_by_alias() {
   images_dir=$1
   imagename=$2
@@ -277,20 +289,6 @@ lookup_ltspimage_name_by_alias() {
 
   log err "could not find the current ltsp image name"
   return 1
-}
-
-lookup_image_server_from_dns() {
-  puavo_domain=$(cat /etc/puavo/domain)
-  image_server=$(
-    dig SRV "_imageserver._tcp.${puavo_domain}" +search +short \
-      | awk '{ sub(/\.$/, ""); printf "%s:%s", $4, $3 }')
-
-  if [ -z "$image_server" ]; then
-    log err "could not find the image server from DNS"
-    return 1
-  else
-    echo "$image_server"
-  fi
 }
 
 patch_with_rdiff() {
@@ -340,7 +338,6 @@ set_image_as_default_image() {
   log notice "new ltsp image $next_image has been set as default"
 }
 
-# XXX duplicate code with puavo-install-ltspimages
 update_image_labels_for_grub() {
   images_dir=$1
 
@@ -380,3 +377,89 @@ else
   puavo-install-grub --only-update-config
   set_image_as_default_image "$images_dir" "$next_image"
 fi
+
+exit 0
+
+#
+# puavo-install-ltspimages (old code to be merged)
+#
+
+#!/bin/sh
+
+set -e
+
+install_from_nbd() {
+  images_dir=$1
+  imagename=$2
+  imagepath=$images_dir/$imagename
+
+  test -e "$imagepath" && return 0
+
+  # clean up old temporary images
+  rm -f $images_dir/*.tmp
+
+  total_size=$(df /dev/nbd0 | awk '$1 == "/dev/nbd0" { print $2 "k" }')
+  dd if=/dev/nbd0 2>/dev/null | pv -s "$total_size" \
+    > "${imagepath}.tmp"
+  sync
+  mv "${imagepath}.tmp" "$imagepath"
+  sync
+}
+
+query_update_confirmation() {
+  current_ltspimage_name=$1
+  new_ltspimage_name=$2
+
+  cat <<EOF
+The current PuavoLTSP image is $current_ltspimage_name,
+but version $new_ltspimage_name is available.
+
+Press ENTER to proceed to update it.
+EOF
+  read answer
+}
+
+install_image() {
+  images_dir=$1
+  imagename=$2
+
+  current_ltspimage_name=$(lookup_ltspimage_name_by_alias "$images_dir" \
+							  ltsp.img)
+  if [ "$current_ltspimage_name" = "$imagename" ]; then
+    echo "The wanted PuavoLTSP image $imagename"
+    echo "is already in place."
+    return 0
+  fi
+
+  if [ -n "$current_ltspimage_name" ]; then
+    query_update_confirmation "$current_ltspimage_name" "$imagename"
+  fi
+
+  install_from_nbd "$images_dir" "$imagename"
+  set_image_as_default_image "$images_dir" "$imagename"
+
+  echo "The PuavoLTSP image $imagename"
+  echo "is now installed and set as default."
+}
+
+
+ltspimage_name=$1
+images_dir=${2:-/images}
+
+if [ -z "$ltspimage_name" -o ! -d "$images_dir" ]; then
+  echo "Usage: $(basename $0) ltspimage_name images_dir" > /dev/stderr
+  exit 1
+fi
+
+hosttype=$(cat /etc/puavo/hosttype)
+
+case "$hosttype" in
+  laptop)
+    install_image "$images_dir" "$ltspimage_name"
+    ;;
+  *)
+    echo "Hosttype '$hosttype' is not supported" > /dev/stderr
+    exit 1
+    ;;
+esac
+
