Support updating the ltsp image, if laptops (or some such) have been booted from the network, and there is something to update.

diff --git a/puavo-install/puavo-install-ltspimages b/puavo-install/puavo-install-ltspimages
--- a/puavo-install/puavo-install-ltspimages
+++ b/puavo-install/puavo-install-ltspimages
@@ -3,8 +3,13 @@
 set -e
 
 install_from_nbd() {
-  imagepath=$1
+  images_dir=$1
+  imagename=$2
+  imagepath=$images_dir/$imagename
 
+  test -e "$imagepath" && return 0
+
+  # clean up old tmpimages
   rm -f $images_dir/*.tmpimage
 
   total_size=$(df /dev/nbd0 | awk '$1 == "/dev/nbd0" { print $2 "k" }')
@@ -15,18 +20,65 @@ install_from_nbd() {
   sync
 }
 
+set_image_as_default_image() {
+  images_dir=$1
+  imagename=$2
+  imagepath=$images_dir/$imagename
+
+  backup_ltspimage_path=$images_dir/ltsp-backup.img
+  default_ltspimage_path=$images_dir/ltsp.img
+
+  ln -f "$default_ltspimage_path" "$backup_ltspimage_path" 2>/dev/null || true
+  ln -f "$imagepath" "${default_ltspimage_path}.tmp"
+  mv "${default_ltspimage_path}.tmp" "$default_ltspimage_path"
+  sync
+}
+
+lookup_current_ltspimage_name() {
+  images_dir=$1
+
+  current_ltspimage_path=$images_dir/ltsp.img
+  current_ltspimage_inode="$(stat -c %i $current_ltspimage_path || true)"
+
+  for file in $images_dir/*.img; do
+    test "$file" = "$current_ltspimage_path" && continue
+
+    if [ "$(stat -c %i "$file" || true)" = "$current_ltspimage_inode" ]; then
+      echo "$(basename "$file")"
+      break
+    fi
+  done
+}
+
+query_update_confirmation() {
+  current_ltspimage_name=$1
+  new_ltspimage_name=$2
+
+  cat <<EOF
+The current PuavoLTSP image is $current_ltspimage_name,
+but version $new_ltspimage_name is available.
+
+Press ENTER to proceed to update it.
+EOF
+  read  
+}
+
 install_image() {
   images_dir=$1
   imagename=$2
 
-  imagepath=$images_dir/$imagename
-
-  if [ -e "$imagepath" ]; then
-    echo "Image $imagename is already in place."
+  current_ltspimage_name=$(lookup_current_ltspimage_name "$images_dir")
+  if [ "$current_ltspimage_name" = "$imagename" ]; then
+    # the image is already in place
     return 0
   fi
 
-  install_from_nbd "$imagepath"
+  if [ -n "$current_ltspimage_name" ]; then
+    query_update_confirmation "$current_ltspimage_name" "$imagename"
+  fi
+
+  install_from_nbd "$images_dir" "$imagename"
+  set_image_as_default_image "$images_dir" "$imagename"
 }
 
 ltspimage_name=$1
