Install new puavo-pkg package in puavo-pkg-update only if there is no old version installed or the new package is of a newer version than then old one.  This is needed so that puavo-pkg-update is actually worthy of the name, making puavo-pkg updates happen.  Note that updates happen in place while the system is used, we are hoping that most software is okay with that.

diff --git a/parts/pkg/puavo-pkg-update b/parts/pkg/puavo-pkg-update
--- a/parts/pkg/puavo-pkg-update
+++ b/parts/pkg/puavo-pkg-update
@@ -128,15 +128,21 @@ install_pkg() {
     return 1
   fi
 
-  installation_dir=$(readlink "${installed_links_dir}/${puavo_pkg}" \
-                       2>/dev/null || true)
-  if [ -e "$installation_dir" ]; then
-    return 0
+  old_package_version=$(
+    awk '$1 == "version" { print $2 }' \
+      "${installed_links_dir}/${puavo_pkg}/.puavo-pkg-version" 2>/dev/null || true)
+  if ! new_package_version=$(
+         tar --wildcards -Ozx -f "$installer_fullpath" '*/.puavo-pkg-version' \
+           | awk '$1 == "version" { print $2 }'); then
+    echo "Could not determine new package version for $puavo_pkg $version" >&2
+    return 1
   fi
 
-  logmsg user.notice "installing ${puavo_pkg} from ${installer_fullpath}"
-
-  puavo-pkg install "$installer_fullpath"
+  if [ -z "$old_package_version" ] \
+    || [ "$old_package_version" -lt "$new_package_version" ]; then
+      logmsg user.notice "installing ${puavo_pkg} from ${installer_fullpath}"
+      puavo-pkg install "$installer_fullpath"
+  fi
 }
 
 prepare_pkg() {
