Implement the concept of read-only cache and rootdirs in puavo-pkg.

diff --git a/parts/pkg/puavo-pkg b/parts/pkg/puavo-pkg
--- a/parts/pkg/puavo-pkg
+++ b/parts/pkg/puavo-pkg
@@ -19,6 +19,8 @@ g_puavo_pkg_rootdir=/var/lib/puavo-pkg
 g_puavo_pkg_readonly_cachedir=
 g_puavo_pkg_readonly_rootdir=
 
+# this can not be overridden with PUAVO_PKG_ROOTDIR by design
+# (we could also move it somewhere else than /var/lib/puavo-pkg/installed)
 g_puavo_pkg_installed_dir="${g_puavo_pkg_rootdir}/installed"
 
 LOG_EMERG=0
@@ -189,8 +191,8 @@ list_installed_pkgs()
     local pkg_dir pkg_name
 
     while read -d '' pkg_dir; do
-        pkg_name=$(get_pkg_name "${pkg_dir}") || return 1
-        echo "${pkg_name}" || return 1
+        pkg_name=$(get_pkg_name "$pkg_dir") || return 1
+        echo "$pkg_name" || return 1
     done < <(list_installed_pkg_dirs)
 }
 
@@ -203,8 +205,9 @@ list_installed_pkgs_with_dirs()
                     END   { print max }' < <(list_installed_pkgs)) || return 1
 
     while read -d '' pkg_dir; do
-        pkg_name=$(get_pkg_name "${pkg_dir}") || return 1
-        printf "%-${col1_len}s    %s\n" "${pkg_name}" "${pkg_dir}"
+        pkg_name=$(get_pkg_name "$pkg_dir") || return 1
+        pkg_id=$(get_pkg_id "$pkg_dir")
+        printf "%-${col1_len}s    %s\n" "$pkg_name" "$pkg_id"
     done < <(list_installed_pkg_dirs)
 }
 
@@ -227,35 +230,40 @@ get_license_url()
     [ -f "${pkg_dir}/license" ] && echo "file://${pkg_dir}/license"
 }
 
-get_pkg_basedir()
-{
-    echo "${g_puavo_pkg_rootdir}/packages/$1"
-}
-
 get_pkg_link()
 {
-    echo "${g_puavo_pkg_installed_dir}/${pkg_name}"
+    echo "${g_puavo_pkg_installed_dir}/$1"
 }
 
 get_pkg_dir()
 {
-    local pkg_name pkg_id pkg_basedir
+    local pkg_dir pkg_id pkg_name
 
     pkg_name=$1
     pkg_id=$2
-    pkg_basedir=$(get_pkg_basedir "${pkg_name}") || return 1
 
-    echo "${pkg_basedir}/${pkg_id}"
+    pkg_dir="${g_puavo_pkg_readonly_rootdir}/packages/${pkg_name}/${pkg_id}"
+    if [ -d "$pkg_dir" ]; then
+       echo "$pkg_dir"
+       return 0
+    fi
+
+    echo "${g_puavo_pkg_rootdir}/packages/${pkg_name}/${pkg_id}"
+}
+
+get_writable_pkg_dir()
+{
+    local pkg_name pkg_id
+
+    pkg_name=$1
+    pkg_id=$2
+
+    echo "${g_puavo_pkg_rootdir}/packages/${pkg_name}/${pkg_id}"
 }
 
 get_installed_pkg_dir()
 {
-    local pkg_name pkg_link
-
-    pkg_name=$1
-    pkg_link=$(get_pkg_link "${pkg_name}") || return 1
-
-    readlink -e "${pkg_link}" || true
+    readlink -e "$(get_pkg_link "$1")"
 }
 
 get_installed_pkg_id()
@@ -263,11 +271,11 @@ get_installed_pkg_id()
     local pkg_name pkg_dir
 
     pkg_name=$1
-    pkg_dir=$(get_installed_pkg_dir "${pkg_name}") || return 1
+    pkg_dir=$(get_installed_pkg_dir "$pkg_name") || return 1
 
-    [ -n "${pkg_dir}" ] || return 0
+    [ -n "$pkg_dir" ] || return 0
 
-    basename "${pkg_dir}"
+    basename "$pkg_dir"
 }
 
 get_pkg_name()
@@ -275,9 +283,9 @@ get_pkg_name()
     local pkg_dir pkg_basedir
 
     pkg_dir=$1
-    pkg_basedir=$(dirname "${pkg_dir}") || return 1
+    pkg_basedir=$(dirname "$pkg_dir") || return 1
 
-    basename "${pkg_basedir}"
+    basename "$pkg_basedir"
 }
 
 get_pkg_id()
@@ -314,15 +322,15 @@ configure_pkg()
         fi
     fi
 
-    pushd "${pkg_dir}" >/dev/null || return 1
-    ./rules configure "${upstream_dir}" || {
+    pushd "$pkg_dir" >/dev/null || return 1
+    ./rules configure "$upstream_dir" || {
         popd >/dev/null || true
         log_error "failed to configure package '${pkg_name}'"
         return 1
     }
     popd >/dev/null || return 1
 
-    ln -fns "${pkg_dir}" "${pkg_link}" || {
+    ln -fns "$pkg_dir" "$pkg_link" || {
         log_error "failed to create a package link"
         return 1
     }
@@ -334,10 +342,13 @@ reconfigure_pkg()
 {
     local pkg_name pkg_id
 
-    pkg_name=$1
-    pkg_id=$(get_installed_pkg_id "${pkg_name}") || return 1
+    # XXX this should probably unconfigure the previously installed
+    # XXX package version it there is such
 
-    configure_pkg "${pkg_name}" "${pkg_id}"
+    pkg_name=$1
+    pkg_id=$(get_installed_pkg_id "$pkg_name") || return 1
+
+    configure_pkg "$pkg_name" "$pkg_id"
 }
 
 reconfigure_all_pkgs()
@@ -348,7 +359,7 @@ reconfigure_all_pkgs()
     retval=0
 
     for pkg in ${pkgs}; do
-        reconfigure_pkg "${pkg}" || retval=1
+        reconfigure_pkg "$pkg" || retval=1
     done
 
     return ${retval}
@@ -361,21 +372,21 @@ unconfigure_pkg()
     pkg_name=$1
     pkg_id=$2
 
-    pkg_link=$(get_pkg_link "${pkg_name}") || return 1
-    pkg_dir=$(readlink -e "${pkg_link}") || true
+    pkg_link=$(get_pkg_link "$pkg_name") || return 1
+    pkg_dir=$(readlink -e "$pkg_link") || true
     upstream_dir="${pkg_dir}/upstream"
 
-    [ -n "${pkg_dir}" ] || return 0
+    [ -n "$pkg_dir" ] || return 0
 
-    pushd "${pkg_dir}" >/dev/null || return 1
-    ./rules unconfigure "${upstream_dir}" >/dev/null || {
+    pushd "$pkg_dir" >/dev/null || return 1
+    ./rules unconfigure "$upstream_dir" >/dev/null || {
         popd >/dev/null || true
         log_error "failed to unconfigure package '${pkg_name}'"
         return 1
     }
     popd >/dev/null || return 1
 
-    rm -f "${pkg_link}" || return 1
+    rm -f "$pkg_link" || return 1
 
     log_info "${pkg_name}: unconfigured successfully"
 }
@@ -386,43 +397,43 @@ unpack_upstream_pack()
 
     pkg_name=$1
     pkg_id=$2
-    pkg_dir=$(get_pkg_dir "${pkg_name}" "${pkg_id}") || return 1
+    pkg_dir=$(get_writable_pkg_dir "$pkg_name" "$pkg_id") || return 1
     upstream_pack="${pkg_dir}/upstream_pack"
     upstream_dir="${pkg_dir}/upstream"
     upstream_tmpdir="${upstream_dir}.tmp"
 
-    if [ -d "${upstream_dir}" ]; then
+    if [ -d "$upstream_dir" ]; then
         return 0
     fi
 
-    check_cksum "${pkg_dir}/upstream_pack_sha384sum" "${upstream_pack}" || {
+    check_cksum "${pkg_dir}/upstream_pack_sha384sum" "$upstream_pack" || {
         log_error "upstream pack has incorrect checksum, " \
             "perhaps you should purge the package and download it again?"
         return 1
     }
 
-    rm -rf "${upstream_tmpdir}"
-    mkdir "${upstream_tmpdir}" || return 1
+    rm -rf "$upstream_tmpdir"
+    mkdir "$upstream_tmpdir" || return 1
 
-    pushd "${pkg_dir}" >/dev/null || return 1
-    ./rules unpack "${upstream_pack}" "${upstream_tmpdir}" || {
+    pushd "$pkg_dir" >/dev/null || return 1
+    ./rules unpack "$upstream_pack" "$upstream_tmpdir" || {
         popd >/dev/null || true
-        rm -rf "${upstream_tmpdir}"
+        rm -rf "$upstream_tmpdir"
         return 1
     }
     popd >/dev/null || {
-        rm -rf "${upstream_tmpdir}"
+        rm -rf "$upstream_tmpdir"
         return 1
     }
 
-    mv -T "${upstream_tmpdir}" "${upstream_dir}" || {
-        rm -rf "${upstream_tmpdir}"
+    mv -T "$upstream_tmpdir" "$upstream_dir" || {
+        rm -rf "$upstream_tmpdir"
         return 1
     }
 
     ## Remove the upstream pack, it is not needed anymore since we just
     ## unpacked it successfully.
-    rm -f "${upstream_pack}"
+    rm -f "$upstream_pack"
 
     log_info "${pkg_name}: unpacked upstream pack successfully"
 }
@@ -460,9 +471,9 @@ cache_load_upstream_pack()
     pkg_name=$1
     pkg_id=$2
 
-    [ -n "${g_puavo_pkg_cachedir}" ] || return 0
+    [ -n "$g_puavo_pkg_cachedir" ] || return 0
 
-    pkg_dir=$(get_pkg_dir "${pkg_name}" "${pkg_id}") || return 1
+    pkg_dir=$(get_writable_pkg_dir "$pkg_name" "$pkg_id") || return 1
     upstream_pack="${pkg_dir}/upstream_pack"
     cksum_file="${pkg_dir}/upstream_pack_sha384sum"
 
@@ -472,9 +483,13 @@ cache_load_upstream_pack()
     [ -n "${cksum_str}" ] || return 0
 
     cached_upstream_pack="${g_puavo_pkg_cachedir}/upstream_packs/${pkg_name}/${cksum_str}"
-    if [ -r "${cached_upstream_pack}" ]; then
-        cp -a -T "${cached_upstream_pack}" "${upstream_pack}" || return 1
-        log_info "${pkg_name}: loaded upstream pack from the cache successfully"
+    cached_readonly_upstream_pack="${g_puavo_pkg_readonly_cachedir}/upstream_packs/${pkg_name}/${cksum_str}"
+    if [ -r "$cached_upstream_pack" ]; then
+        cp -a -T "$cached_upstream_pack" "$upstream_pack" || return 1
+        log_info "${pkg_name}: loaded the upstream pack from the cache"
+    elif [ -r "$cached_readonly_upstream_pack" ]; then
+        cp -a -T "$cached_readonly_upstream_pack" "$upstream_pack" || return 1
+        log_info "${pkg_name}: loaded the upstream pack from the readonly cache"
     fi
 }
 
@@ -485,15 +500,17 @@ cache_save_upstream_pack()
     pkg_name=$1
     pkg_id=$2
 
-    [ -n "${g_puavo_pkg_cachedir}" ] || return 0
+    [ -n "$g_puavo_pkg_cachedir" ] || return 0
 
-    pkg_dir=$(get_pkg_dir "${pkg_name}" "${pkg_id}") || return 1
+    pkg_dir=$(get_writable_pkg_dir "$pkg_name" "$pkg_id") || return 1
     upstream_pack="${pkg_dir}/upstream_pack"
-    cksum_str=$(sha384sum "${upstream_pack}" | cut -d' ' -f1)
+    cksum_str=$(sha384sum "$upstream_pack" | cut -d' ' -f1)
 
-    if [ -n "${cksum_str}" ]; then
+    if [ -n "$cksum_str" ]; then
         mkdir -p "${g_puavo_pkg_cachedir}/upstream_packs/${pkg_name}"
-        cp -a -T "${upstream_pack}" "${g_puavo_pkg_cachedir}/upstream_packs/${pkg_name}/${cksum_str}" || return 1
+        cp -a -T "$upstream_pack" \
+                 "${g_puavo_pkg_cachedir}/upstream_packs/${pkg_name}/${cksum_str}" \
+          || return 1
     fi
 
     log_info "${pkg_name}: saved upstream pack to cache successfully"
@@ -505,11 +522,11 @@ download_upstream_pack()
 
     pkg_name=$1
     pkg_id=$2
-    pkg_dir=$(get_pkg_dir "${pkg_name}" "${pkg_id}") || return 1
+    pkg_dir=$(get_writable_pkg_dir "$pkg_name" "$pkg_id") || return 1
     upstream_pack="${pkg_dir}/upstream_pack"
     upstream_tmppack="${upstream_pack}.tmp"
 
-    cache_load_upstream_pack "${pkg_name}" "${pkg_id}" || {
+    cache_load_upstream_pack "$pkg_name" "$pkg_id" || {
         log_warning "${pkg_name}: failed to load the upstream pack from the cache"
     }
 
@@ -555,7 +572,7 @@ download_upstream_pack()
         return 1
     }
 
-    cache_save_upstream_pack "${pkg_name}" "${pkg_id}" || {
+    cache_save_upstream_pack "$pkg_name" "$pkg_id" || {
         log_warning "${pkg_name}: failed to save upstream pack to the cache"
     }
 
@@ -584,28 +601,28 @@ extract_installer()
     local installer pkg_name pkg_id pkg_dir pkg_tmpdir pkg_format
 
     installer=$1
-    pkg_name=$(basename "${installer}" .tar.gz) || return 1
+    pkg_name=$(basename "$installer" .tar.gz) || return 1
 
-    if [ ! -f "${installer}" ]; then
+    if [ ! -f "$installer" ]; then
         log_error "installer '${installer}' does not exist"
         return 1
     fi
 
     pkg_id=$(get_pkg_id_from_installer "$installer") || return 1
 
-    pkg_dir=$(get_pkg_dir "${pkg_name}" "${pkg_id}")
+    pkg_dir=$(get_writable_pkg_dir "$pkg_name" "$pkg_id")
     pkg_tmpdir="${pkg_dir}.tmp"
 
-    if [ -d "${pkg_dir}" ]; then
-        echo "${pkg_dir}"
+    if [ -d "$pkg_dir" ]; then
+        echo "$pkg_dir"
         return
     fi
 
-    mkdir -p "${pkg_tmpdir}" || return 1
+    mkdir -p "$pkg_tmpdir" || return 1
 
     tar --no-same-owner --no-same-permissions --strip-components=1 \
-        -z -x -f "${installer}" -C "${pkg_tmpdir}" || {
-        rm -rf "${pkg_tmpdir}"
+        -z -x -f "$installer" -C "$pkg_tmpdir" || {
+        rm -rf "$pkg_tmpdir"
         return 1
     }
 
@@ -614,12 +631,12 @@ extract_installer()
     if [ -f "${pkg_tmpdir}/format" ]; then
         pkg_format=$(cat "${pkg_tmpdir}/format") || {
             log_error "failed to read installer format"
-            rm -rf "${pkg_tmpdir}"
+            rm -rf "$pkg_tmpdir"
             return 1
         }
     fi
 
-    if [ "${pkg_format}" != "${SUPPORTED_PKG_FORMAT}" ]; then
+    if [ "$pkg_format" != "${SUPPORTED_PKG_FORMAT}" ]; then
         log_error "installer has unsupported format"
         rm -rf "${pkg_tmpdir}"
         return 1
@@ -640,36 +657,36 @@ install_pkg_with_installer()
     local installer pkg_dir pkg_name pkg_id old_pkg_id old_pkg_dir
 
     installer=$1
-    pkg_dir=$(extract_installer "${installer}") || {
-        log_error "failed to extract '${installer}'"
+    pkg_dir=$(extract_installer "$installer") || {
+        log_error "failed to extract '$installer'"
         return 1
     }
 
-    pkg_name=$(get_pkg_name "${pkg_dir}") || return 1
-    pkg_id=$(get_pkg_id "${pkg_dir}") || return 1
+    pkg_name=$(get_pkg_name "$pkg_dir") || return 1
+    pkg_id=$(get_pkg_id "$pkg_dir") || return 1
 
-    download_upstream_pack "${pkg_name}" "${pkg_id}" || {
+    download_upstream_pack "$pkg_name" "$pkg_id" || {
         log_error "failed to download the upstream pack of package '${pkg_name}'"
         return 1
     }
 
-    unpack_upstream_pack "${pkg_name}" "${pkg_id}" || {
+    unpack_upstream_pack "$pkg_name" "$pkg_id" || {
         log_error "failed to unpack the upstream pack of package '${pkg_name}'"
         return 1
     }
 
-    old_pkg_id=$(get_installed_pkg_id "${pkg_name}") || return 1
-    if [ -n "${old_pkg_id}" -a "${old_pkg_id}" != "${pkg_id}" ]; then
-        unconfigure_pkg "${pkg_name}" "${old_pkg_id}" || {
+    old_pkg_id=$(get_installed_pkg_id "$pkg_name") || return 1
+    if [ -n "$old_pkg_id" -a "$old_pkg_id" != "$pkg_id" ]; then
+        unconfigure_pkg "$pkg_name" "$old_pkg_id" || {
             log_error "failed to unconfigure package '${pkg_name}'"
             return 1
         }
     fi
 
-    configure_pkg "${pkg_name}" "${pkg_id}" || {
+    configure_pkg "$pkg_name" "$pkg_id" || {
         log_error "${pkg_name}: failed to configure package version '${pkg_id}'"
-        if [ -n "${old_pkg_id}" -a "${old_pkg_id}" != "${pkg_id}" ]; then
-            configure_pkg "${pkg_name}" "${old_pkg_id}" || {
+        if [ -n "$old_pkg_id" -a "$old_pkg_id" != "$pkg_id" ]; then
+            configure_pkg "$pkg_name" "$old_pkg_id" || {
                 log_error "${pkg_name}: failed to reconfigure the previous version '${old_pkg_id}'"
                 return 1
             }
@@ -678,9 +695,9 @@ install_pkg_with_installer()
         return 1
     }
 
-    if [ -n "${old_pkg_id}" -a "${old_pkg_id}" != "${pkg_id}" ]; then
-        old_pkg_dir=$(get_pkg_dir "${pkg_name}" "${old_pkg_id}") \
-            && rm -rf "${old_pkg_dir}" || true
+    if [ -n "$old_pkg_id" -a "$old_pkg_id" != "$pkg_id" ]; then
+        old_pkg_dir=$(get_writable_pkg_dir "$pkg_name" "$old_pkg_id") \
+            && rm -rf "$old_pkg_dir" || true
     fi
 
     log_info "${pkg_name}: installed successfully"
@@ -692,13 +709,13 @@ remove_pkg()
 
     pkg_name=$1
 
-    pkg_id=$(get_installed_pkg_id "${pkg_name}") || return 1
+    pkg_id=$(get_installed_pkg_id "$pkg_name") || return 1
     if [ -n "${pkg_id}" ]; then
-        unconfigure_pkg "${pkg_name}" "${pkg_id}" || {
+        unconfigure_pkg "$pkg_name" "$pkg_id" || {
             log_error "failed to unconfigure package '${pkg_name}'"
             return 1
         }
-        pkg_dir=$(get_pkg_dir "${pkg_name}" "${pkg_id}") || return 1
+        pkg_dir=$(get_writable_pkg_dir "$pkg_name" "$pkg_id") || return 1
         rm -rf "${pkg_dir}" || return 1
         log_info "removed package '${pkg_name}'"
         return 0
@@ -716,7 +733,7 @@ remove_all_pkgs()
     retval=0
 
     for pkg in ${pkgs}; do
-        remove_pkg "${pkg}" || retval=1
+        remove_pkg "$pkg" || retval=1
     done
 
     return ${retval}
@@ -731,23 +748,28 @@ show_pkg()
 
     INSTALLER_REGEX='\.tar\.gz$'
 
-    if [[ "${identifier}" =~ ${INSTALLER_REGEX} ]]; then
-        pkg_dir=$(extract_installer "${identifier}") || {
+    if [[ "$identifier" =~ ${INSTALLER_REGEX} ]]; then
+        pkg_dir=$(extract_installer "$identifier") || {
             log_error "failed to extract installer '${identifier}'"
             return 1
         }
     else
-        pkg_dir=$(get_installed_pkg_dir "${identifier}") || return 1
+        pkg_dir=$(get_installed_pkg_dir "$identifier") || return 1
     fi
 
-    pkg_name=$(get_pkg_name "${pkg_dir}") || return 1
-    pkg_id=$(get_pkg_id "${pkg_dir}") || return 1
+    pkg_name=$(get_pkg_name "$pkg_dir") || return 1
+    pkg_id=$(get_pkg_id "$pkg_dir") || return 1
     if [ -z "${pkg_id}" ]; then
         log_error "package ${pkg_name} is not installed"
         return 1
     fi
 
-    pkg_legend="${pkg_name}"
+    pkg_version=$(get_pkg_version "$pkg_dir") || return 1
+    if [ -z "$pkg_version" ]; then
+      pkg_version='?'
+    fi
+
+    pkg_legend="$pkg_name"
     if [ -r "${pkg_dir}/legend" ]; then
         pkg_legend=$(head -n1 "${pkg_dir}/legend") || return 1
     fi
@@ -854,16 +876,26 @@ fi
 ## Override default configuration with values from the config file.
 if [ -r /etc/puavo-pkg/puavo-pkg.conf ]; then
     . /etc/puavo-pkg/puavo-pkg.conf
-    if [ ! -z ${PUAVO_PKG_ROOTDIR+x} ]; then
-        g_puavo_pkg_rootdir="${PUAVO_PKG_ROOTDIR}"
-    fi
     if [ ! -z ${PUAVO_PKG_CACHEDIR+x} ]; then
-        g_puavo_pkg_cachedir="${PUAVO_PKG_CACHEDIR}"
+        g_puavo_pkg_cachedir="$PUAVO_PKG_READONLY_CACHEDIR"
+    fi
+    if [ ! -z ${PUAVO_PKG_ROOTDIR+x} ]; then
+        g_puavo_pkg_rootdir="$PUAVO_PKG_ROOTDIR"
+    fi
+    if [ ! -z ${PUAVO_PKG_READONLY_CACHEDIR+x} ]; then
+        g_puavo_pkg_readonly_cachedir="$PUAVO_PKG_READONLY_CACHEDIR"
+    fi
+    if [ ! -z ${PUAVO_PKG_READONLY_ROOTDIR+x} ]; then
+        g_puavo_pkg_readonly_cachedir="$PUAVO_PKG_READONLY_ROOTDIR"
     fi
 fi
 
 ## Validate configuration.
-[[ "${g_puavo_pkg_rootdir}" =~ ^/ ]] || usage_error "invalid root dir path"
+[[ "$g_puavo_pkg_rootdir" =~ ^/ ]] || usage_error "invalid root dir path"
+
+[ -z "$g_puavo_pkg_readonly_rootdir" ] \
+  || [[ "$g_puavo_pkg_readonly_rootdir" =~ ^/ ]] \
+  || usage_error "invalid readonly root dir path"
 
 mkdir -p "${g_puavo_pkg_rootdir}/packages" "$g_puavo_pkg_installed_dir"
 
