Do not unconfigure/remove the updated package version

diff --git a/parts/pkg/puavo-pkg b/parts/pkg/puavo-pkg
--- a/parts/pkg/puavo-pkg
+++ b/parts/pkg/puavo-pkg
@@ -222,6 +222,8 @@ unconfigure_pkg()
     local pkg_name pkg_link pkg_dir upstream_dir
 
     pkg_name=$1
+    pkg_version=$2
+
     pkg_link=$(get_pkg_link "${pkg_name}") || return 1
     pkg_dir=$(readlink -e "${pkg_link}") || true
     upstream_dir="${pkg_dir}/upstream"
@@ -239,7 +241,6 @@ unconfigure_pkg()
     rm -f "${pkg_link}" || return 1
 
     log_info "${pkg_name}: unconfigured successfully"
-    basename "${pkg_dir}"
 }
 
 unpack_upstream_pack()
@@ -483,22 +484,27 @@ install_pkg_with_installer()
         return 1
     }
 
-    old_pkg_version=$(unconfigure_pkg "${pkg_name}") || {
-        log_error "failed to unconfigure package '${pkg_name}'"
-        return 1
-    }
+    old_pkg_version=$(get_installed_pkg_version "${pkg_name}") || return 1
+    if [ -n "${old_pkg_version}" -a "${old_pkg_version}" != "${pkg_version}" ]; then
+        unconfigure_pkg "${pkg_name}" "${old_pkg_version}" || {
+            log_error "failed to unconfigure package '${pkg_name}'"
+            return 1
+        }
+    fi
 
     configure_pkg "${pkg_name}" "${pkg_version}" || {
         log_error "${pkg_name}: failed to configure package version '${pkg_version}'"
-        configure_pkg "${pkg_name}" "${old_pkg_version}" || {
-            log_error "${pkg_name}: failed to reconfigure the previous version '${old_pkg_version}'"
-            return 1
-        }
-        log_info "${pkg_name}: reconfigured the previous version '${old_pkg_version}' successfully"
+        if [ -n "${old_pkg_version}" -a "${old_pkg_version}" != "${pkg_version}" ]; then
+            configure_pkg "${pkg_name}" "${old_pkg_version}" || {
+                log_error "${pkg_name}: failed to reconfigure the previous version '${old_pkg_version}'"
+                return 1
+            }
+            log_info "${pkg_name}: reconfigured the previous version '${old_pkg_version}' successfully"
+        fi
         return 1
     }
 
-    if [ -n "${old_pkg_version}" ]; then
+    if [ -n "${old_pkg_version}" -a "${old_pkg_version}" != "${pkg_version}" ]; then
         old_pkg_dir=$(get_pkg_dir "${pkg_name}" "${old_pkg_version}") \
             && rm -rf "${old_pkg_dir}" || true
     fi
@@ -512,12 +518,12 @@ remove_pkg()
 
     pkg_name=$1
 
-    pkg_version=$(unconfigure_pkg "${pkg_name}") || {
-        log_error "failed to unconfigure package '${pkg_name}'"
-        return 1
-    }
-
+    pkg_version=$(get_installed_pkg_version "${pkg_name}") || return 1
     if [ -n "${pkg_version}" ]; then
+        unconfigure_pkg "${pkg_name}" "${pkg_version}" || {
+            log_error "failed to unconfigure package '${pkg_name}'"
+            return 1
+        }
         pkg_dir=$(get_pkg_dir "${pkg_name}" "${pkg_version}") || return 1
         rm -rf "${pkg_dir}" || return 1
         log_info "removed package '${pkg_name}'"
