Make show command accept installer files

diff --git a/parts/pkg/puavo-pkg b/parts/pkg/puavo-pkg
--- a/parts/pkg/puavo-pkg
+++ b/parts/pkg/puavo-pkg
@@ -66,7 +66,7 @@ print_help_and_exit()
     echo "  remove PACKAGE                 remove installed PACKAGE"
     echo "  remove --all                   remove all installed packages"
     echo
-    echo "  show PACKAGE                   show package details"
+    echo "  show INSTALLER|PACKAGE         show package details"
     echo "  show -F|--field FIELD PACKAGE  show specific FIELD"
     echo
     echo "Files:"
@@ -629,18 +629,28 @@ remove_all_pkgs()
 
 show_pkg()
 {
-    local pkg_name pkg_dir pkg_version pkg_legend pkg_description pkg_field
+    local pkg_name pkg_dir pkg_version pkg_legend pkg_description pkg_field identifier INSTALLER_REGEX
 
-    pkg_name=$1
+    identifier=$1
     pkg_field=$2
 
-    pkg_version=$(get_installed_pkg_version "${pkg_name}") || return 1
+    INSTALLER_REGEX='\.tar\.gz$'
+
+    if [[ "${identifier}" =~ ${INSTALLER_REGEX} ]]; then
+        pkg_dir=$(extract_installer "${identifier}") || {
+            log_error "failed to extract installer '${identifier}'"
+            return 1
+        }
+    else
+        pkg_dir=$(get_installed_pkg_dir "${identifier}") || return 1
+    fi
+
+    pkg_name=$(get_pkg_name "${pkg_dir}") || return 1
+    pkg_version=$(get_pkg_version "${pkg_dir}") || return 1
     if [ -z "${pkg_version}" ]; then
         log_error "package ${pkg_name} is not installed"
         return 1
     fi
-
-    pkg_dir=$(get_pkg_dir "${pkg_name}" "${pkg_version}") || return 1
 
     pkg_legend="${pkg_name}"
     if [ -r "${pkg_dir}/legend" ]; then
