puavo-ers: Refactor ERS modes startup
Change all ERS modes to start in visible terminal window, which provides common place to show progress and status information.

diff --git a/parts/ers/puavo-ers-naksu b/parts/ers/puavo-ers-naksu
--- a/parts/ers/puavo-ers-naksu
+++ b/parts/ers/puavo-ers-naksu
@@ -2,6 +2,8 @@
 
 set -eu
 
+echo "\e[32mStarting Puavo Exam Room Server in Naksu mode...\e[0m"
+
 puavo_ers_dir="${HOME}/.puavo/puavo-ers"
 
 if ! mkdir -p "$puavo_ers_dir"; then
@@ -19,11 +21,14 @@ if [ ! -x "${puavo_ers_dir}/naksu" ]; then
   fi
 fi
 
+echo "\e[32mChecking VirtualBox kernel module...\e[0m"
+
 # Wait for the VirtualBox kernel module to load
 for i in 4 8 16 32 64; do
   if [ -e /dev/vboxdrv ]; then
     break
   fi
+  echo "\e[33mWaiting for vboxdrv to load in kernel...\e[0m"
   logger -p user.warning -t puavo-ers-naksu 'waiting for vboxdrv to load in kernel'
   sleep "$i"
 done
@@ -33,13 +38,16 @@ if [ ! -e /dev/vboxdrv ]; then
   exit 1
 fi
 
+echo "\e[32mVirtualBox kernel module loaded.\e[0m"
+sleep 2
+
 cd "$puavo_ers_dir"
 
 while true; do
+  echo "\e[32mStarting Naksu...\e[0m"
   logger -p user.notice -t puavo-ers-naksu 'starting up naksu'
-  if ! /usr/bin/terminator -T 'naksu terminal' \
-         --no-dbus "--working-directory=${puavo_ers_dir}" -x ./naksu \
-         --self-update=enabled; then
+  if ! ${puavo_ers_dir}/naksu --self-update=enabled; then
+    echo "\e[31mNaksu failed to start. Will try again in 5 seconds...\e[0m"
     logger -p user.err -t puavo-ers-naksu 'error when running naksu'
   fi
   sleep 5
diff --git a/parts/ers/puavo-ers-naksu2 b/parts/ers/puavo-ers-naksu2
--- a/parts/ers/puavo-ers-naksu2
+++ b/parts/ers/puavo-ers-naksu2
@@ -27,8 +27,11 @@ setup_naksu2_configuration() {
 
 network_interface=${1:-}
 
+echo "\e[32mStarting Puavo Exam Room Server in Naksu2 mode...\e[0m"
+
 workdir="${HOME}/.puavo/puavo-ers/naksu2"
 
+echo "\e[32mPreparing to run naksu2...\e[0m"
 logger -p user.notice -t puavo-ers-naksu2 \
        "preparing to run naksu2 in '${workdir}'"
 
@@ -57,12 +60,15 @@ if is_abitti2_server; then
   setup_naksu2_configuration "$network_interface"
 fi
 
+echo "\e[32mEverything looks ok.\e[0m"
+
 cd "$workdir"
 
 while true; do
+  echo "\e[32mStarting Naksu2...\e[0m"
   logger -p user.notice -t puavo-ers-naksu2 'starting up naksu2'
-  if ! /usr/bin/terminator -T 'naksu2 terminal' \
-       --no-dbus "--working-directory=${workdir}" -x naksu2; then
+  if ! naksu2; then
+    echo "\e[31mNaksu2 failed to start. Will try again in 5 seconds...\e[0m"
     logger -p user.err -t puavo-ers-naksu2 'naksu2 failed'
   fi
   sleep 5
