Do not do restarts in puavo-ers-naksu2.
This we can leave for supervisor.

diff --git a/parts/ers/puavo-ers-naksu2 b/parts/ers/puavo-ers-naksu2
--- a/parts/ers/puavo-ers-naksu2
+++ b/parts/ers/puavo-ers-naksu2
@@ -59,11 +59,9 @@ fi
 
 cd "$workdir"
 
-while true; do
-  logger -p user.notice -t puavo-ers-naksu2 'starting up naksu2'
-  if ! /usr/bin/terminator -T 'naksu2 terminal' \
-       --no-dbus "--working-directory=${workdir}" -x naksu2; then
-    logger -p user.err -t puavo-ers-naksu2 'naksu2 failed'
-  fi
-  sleep 5
-done
+logger -p user.notice -t puavo-ers-naksu2 'starting up naksu2'
+
+if ! /usr/bin/terminator -T 'naksu2 terminal' \
+     --no-dbus "--working-directory=${workdir}" -x naksu2; then
+  logger -p user.err -t puavo-ers-naksu2 'naksu2 failed'
+fi
