cp-changes: add --help flag

diff --git a/parts/devscripts/bin/cp-changes b/parts/devscripts/bin/cp-changes
--- a/parts/devscripts/bin/cp-changes
+++ b/parts/devscripts/bin/cp-changes
@@ -2,6 +2,34 @@
 
 set -eu
 
+while [ $# -gt 0 ]; do
+    case $1 in
+        -h|--help)
+            shift
+            echo "Usage: $0 [OPTION]... [CHANGES_FILE] DIR"
+            echo
+            echo 'Copy files listed in .changes file to the target directory.'
+            echo 'If CHANGES_FILE is omitted, it will be deduced from debian/changelog.'
+            echo
+            echo "Options:"
+            echo "    -h, --help                   print help and exit"
+            echo
+            exit 0
+            ;;
+        --)
+            shift
+            break
+            ;;
+        -*)
+            echo "error: invalid argument '$1'" >&2
+            exit 1
+            ;;
+        *)
+            break
+            ;;
+    esac
+done
+
 if [ $# -eq 1 ]; then
     pkg_name=$(dpkg-parsechangelog -SSource)
     pkg_version=$(dpkg-parsechangelog -SVersion)
