parts/devscripts: remove git hook support from git-update-debian-changelog

diff --git a/parts/devscripts/bin/git-update-debian-changelog b/parts/devscripts/bin/git-update-debian-changelog
--- a/parts/devscripts/bin/git-update-debian-changelog
+++ b/parts/devscripts/bin/git-update-debian-changelog
@@ -25,10 +25,9 @@
 ## If there are new commits on top of the last release commit, the
 ## user is prompted with a suggestion to create a release commit. If
 ## the user accepts, debian/changelog is updated, commited and the
-## script exits with non-zero status code. If the user rejects, the
-## scripts exits with zero status code without making any
-## changes. This status code scheme allows this script to be used as a
-## pre-push hook.
+## script exits with zero status code. If the user rejects, or the
+## script fails, the scripts exits with zero status code without
+## making any changes.
 ##
 ## A commit is identified as a release commit if its message matches
 ## with '^RELEASE: '.
@@ -45,15 +44,9 @@ on_exit()
     exit $exitvalue
 }
 
-is_hook=false
-if [ $# -eq 2 ]; then
-    is_hook=true
-fi
-
 git diff-index --quiet HEAD -- debian/changelog || {
     echo 'warning: there are uncommitted changes in debian/changelog, not creating a release commit' >&2
-    $is_hook || exit 1
-    exit 0
+    exit 1
 }
 
 if [ -z "$(git ls-tree HEAD debian/changelog)" ]; then
@@ -63,7 +56,6 @@ fi
 
 if [ ! -f debian/changelog ]; then
     echo 'error: debian/changelog is missing' >&2
-    $is_hook || exit 0
     exit 1
 fi
 
@@ -143,19 +135,10 @@ while true; do
             cp "${tmpdir}/changelog" debian/changelog
             version=$(dpkg-parsechangelog | sed -r -n 's/^Version: //p')
             git commit debian/changelog -m "RELEASE: ${version}"
-	    if $is_hook; then
-		exitvalue=1
-	    else
-		exitvalue=0
-	    fi
+	    exitvalue=0
             break
             ;;
         n)
-	    if $is_hook; then
-		exitvalue=0
-	    else
-		exitvalue=1
-	    fi
             break
             ;;
         *)
