git-dch: add -z to exit success on empty release

diff --git a/parts/devscripts/bin/git-dch b/parts/devscripts/bin/git-dch
--- a/parts/devscripts/bin/git-dch
+++ b/parts/devscripts/bin/git-dch
@@ -30,6 +30,7 @@ on_exit()
 }
 
 changelog_file=debian/changelog
+do_test_empty_release=false
 
 while [ $# -gt 0 ]; do
     case $1 in
@@ -50,6 +51,7 @@ while [ $# -gt 0 ]; do
             echo "Options:"
             echo "    -h, --help                   print help and exit"
             echo "    -f, --changelog FILE         edit FILE instead of ${changelog_file}"
+            echo "    -z                           exit 0 if there are zero commits to be released, otherwise exit 1"
             echo
             exit 0
             ;;
@@ -61,6 +63,10 @@ while [ $# -gt 0 ]; do
             fi
             changelog_file=$1
             shift
+            ;;
+        -z)
+            shift
+            do_test_empty_release=true
             ;;
         --)
             shift
@@ -97,7 +103,15 @@ if [ ! -f "${changelog_file}" ]; then
 fi
 
 if git log -n1 --format='%s' | egrep -q '^RELEASE: '; then
+    if $do_test_empty_release; then
+        exit 0
+    fi
     echo "warning: there aren't any commits since the last relase" >&2
+else
+    if $do_test_empty_release; then
+        echo "error: HEAD is not a release commit" >&2
+        exit 1
+    fi
 fi
 
 ## Update the changelog.
