mkaptrepo: add --help

diff --git a/parts/devscripts/bin/mkaptrepo b/parts/devscripts/bin/mkaptrepo
--- a/parts/devscripts/bin/mkaptrepo
+++ b/parts/devscripts/bin/mkaptrepo
@@ -24,14 +24,41 @@
 
 set -eu
 
+usage_error()
+{
+    echo "ERROR: $1" >&2
+    echo "Try --help for help". >&2
+    return 1
+}
+
+while [ $# -gt 0 ]; do
+    case $1 in
+        -h|--help)
+            shift
+            echo "Usage: $0 DIR"
+            echo
+            echo "Create a very simple APT repository."
+            echo
+            echo "Options:"
+            echo "    -h, --help                   print help and exit"
+            echo
+            exit 0
+            ;;
+        --)
+            shift
+            break
+            ;;
+        -*)
+            usage_error "invalid argument '$1'"
+            ;;
+        *)
+            break
+            ;;
+    esac
+done
+
 if [ $# -ne 1 ]; then
-    echo "ERROR: invalid number of arguments: got $#, expected 1" >&2
-    echo >&2
-    echo "Usage: $0 DIR" >&2
-    echo >&2
-    echo "    Create empty APT repository to DIR." >&2
-    echo >&2
-    exit 1
+    usage_error "invalid number of arguments: got $#, expected 1"
 fi
 
 repopath=$1
