mkaptrepo: ensure all files listed include list get copied

diff --git a/parts/devscripts/bin/mkaptrepo b/parts/devscripts/bin/mkaptrepo
--- a/parts/devscripts/bin/mkaptrepo
+++ b/parts/devscripts/bin/mkaptrepo
@@ -174,6 +174,15 @@ if [ ${#copy_src_dirs[@]} -gt 0 ]; then
                 fi
             fi
     done
+
+    if [ -n "${include_from}" ]; then
+	while read package; do
+	    if [ ! -e "${repopath}/pool/${package}" ]; then
+		echo "ERROR: package '${package}' is missing" >&2
+		exit 1
+	    fi
+	done <"${include_from}"
+    fi
 fi
 
 make -s -C "${repopath}"
