puavo-img-clone: rename variables

diff --git a/parts/devscripts/bin/puavo-img-clone b/parts/devscripts/bin/puavo-img-clone
--- a/parts/devscripts/bin/puavo-img-clone
+++ b/parts/devscripts/bin/puavo-img-clone
@@ -30,8 +30,8 @@ on_exit()
 
     set +eu
 
-    umount "${src_filepath_G}"
-    rmdir "${src_fsroot_G}"
+    umount "${srcfile_G}"
+    rmdir "${srcmountdir_G}"
 
     return ${exitval}
 }
@@ -57,138 +57,138 @@ is_uint()
 
 clone_to_ext4()
 {
-    local dst_loopdev
+    local loopdev
     local imgname
     local retval
-    local src_size
+    local srcsize
     local tmpdir
     local tmpfile
 
-    imgname=$(basename "${dst_filepath_G}" .img) || return $?
+    imgname=$(basename "${dstfile_G}" .img) || return $?
 
-    src_size=$(df --block-size=1 --output=size "${src_fsroot_G}" | tail -n1)
-    if [ -z "${src_size}" ]; then
+    srcsize=$(df --block-size=1 --output=size "${srcmountdir_G}" | tail -n1)
+    if [ -z "${srcsize}" ]; then
         echo "error: failed to determine the size of the source filesystem" >&2
         return 1
     fi
 
-    if [ -z "${dst_size_G}" ]; then
-        dst_size_G=$((src_size * 2))
+    if [ -z "${dstsize_G}" ]; then
+        dstsize_G=$((srcsize * 2))
     fi
 
     tmpfile=$(mktemp) || return $?
 
-    dd if=/dev/zero of="${tmpfile}" count=0 bs=1 seek="${dst_size_G}" || {
+    dd if=/dev/zero of="${tmpfile}" count=0 bs=1 seek="${dstsize_G}" || {
         retval=$?
         rm -rf "${tmpfile}" || true
-        return $retval
+        return ${retval}
     }
 
-    dst_loopdev=$(losetup -f --show "${tmpfile}") || {
+    loopdev=$(losetup -f --show "${tmpfile}") || {
         retval=$?
         rm -rf "${tmpfile}" || true
-        return $retval
+        return ${retval}
     }
 
-    mkfs.ext4 "${dst_loopdev}" || {
+    mkfs.ext4 "${loopdev}" || {
         retval=$?
-        losetup -d "${dst_loopdev}" || true
+        losetup -d "${loopdev}" || true
         rm -rf "${tmpfile}" || true
-        return $retval
+        return ${retval}
     }
 
-    losetup -d "${dst_loopdev}" || {
+    losetup -d "${loopdev}" || {
         retval=$?
         rm -rf "${tmpfile}" || true
-        return $retval
+        return ${retval}
     }
 
     tmpdir=$(mktemp -d) || {
         retval=$?
         rm -rf "${tmpfile}" || true
-        return $retval
+        return ${retval}
     }
 
     mount -o loop "${tmpfile}" "${tmpdir}" || {
         retval=$?
         rm -rf "${tmpfile}" || true
         rmdir "${tmpdir}" || true
-        return $retval
+        return ${retval}
     }
 
-    rsync -a "${src_fsroot_G}/" "${tmpdir}/" || {
+    rsync -a "${srcmountdir_G}/" "${tmpdir}/" || {
         retval=$?
         # If umount fails, leave everything as it is so that the user
         # can cleanup manually later.
-        umount "${tmpdir}" || return $retval
+        umount "${tmpdir}" || return ${retval}
         rmdir "${tmpdir}" || true
         rm -rf "${tmpfile}" || true
-        return $retval
+        return ${retval}
     }
 
     echo "${imgname}" >"${tmpdir}/etc/ltsp/this_ltspimage_name" || {
         retval=$?
-        umount "${tmpdir}" || return $retval
+        umount "${tmpdir}" || return ${retval}
         rmdir "${tmpdir}" || true
         rm -rf "${tmpfile}" || true
-        return $retval
+        return ${retval}
     }
 
     umount "${tmpdir}" || return $?
 
-    mv "${tmpfile}" "${dst_filepath_G}" || return $?
+    mv "${tmpfile}" "${dstfile_G}" || return $?
 
     rmdir "${tmpdir}"
 }
 
 clone_to_squashfs()
 {
-    local dst_file_dir
+    local dstdir
     local imgname
     local retval
     local tmpdir
     local tmpfile
 
-    imgname=$(basename "${dst_filepath_G}" .img) || return $?
+    imgname=$(basename "${dstfile_G}" .img) || return $?
 
     tmpdir=$(mktemp -d) || return $?
 
-    rsync -a "${src_fsroot_G}/" "${tmpdir}/" || {
+    rsync -a "${srcmountdir_G}/" "${tmpdir}/" || {
         retval=$?
         rm -rf "${tmpdir}" || true
-        return $retval
+        return ${retval}
     }
 
     echo "${imgname}" >"${tmpdir}/etc/ltsp/this_ltspimage_name" || {
         retval=$?
         rm -rf "${tmpdir}" || true
-        return $retval
+        return ${retval}
     }
 
-    dst_file_dir=$(dirname "${dst_filepath_G}") || {
+    dstdir=$(dirname "${dstfile_G}") || {
         retval=$?
         rm -rf "${tmpdir}" || true
-        return $retval
+        return ${retval}
     }
 
-    tmpfile=$(mktemp --tmpdir="${dst_file_dir}") || {
+    tmpfile=$(mktemp --tmpdir="${dstdir}") || {
         retval=$?
         rm -rf "${tmpdir}" || true
-        return $retval
+        return ${retval}
     }
 
     mksquashfs "${tmpdir}" "${tmpfile}" -noappend -no-recovery || {
         retval=$?
         rm -rf "${tmpdir}" || true
         rm -rf "${tmpfile}" || true
-        return $retval
+        return ${retval}
     }
 
-    mv "${tmpfile}" "${dst_filepath_G}" || {
+    mv "${tmpfile}" "${dstfile_G}" || {
         retval=$?
         rm -rf "${tmpdir}" || true
         rm -rf "${tmpfile}" || true
-        return $retval
+        return ${retval}
     }
 
     rm -rf "${tmpdir}"
@@ -197,12 +197,12 @@ clone_to_squashfs()
 # Main below
 
 # Declare all global variables here and only here.
-clone_func_G=clone_to_ext4
-dst_filepath_G=
-dst_size_G=
+clonefunc_G=clone_to_ext4
+dstfile_G=
+dstsize_G=
 force_G=0
-src_filepath_G=
-src_fsroot_G=
+srcfile_G=
+srcfsroot_G=
 
 while [ $# -gt 0 ]; do
     case $1 in
@@ -228,10 +228,10 @@ while [ $# -gt 0 ]; do
             shift
             case $1 in
                 ext4)
-                    clone_func_G=clone_to_ext4
+                    clonefunc_G=clone_to_ext4
                     ;;
                 squashfs)
-                    clone_func_G=clone_to_squashfs
+                    clonefunc_G=clone_to_squashfs
                     ;;
                 *)
                     usage_error "invalid value '$1' for option '--type', expected 'ext4' or 'squashfs'"
@@ -241,10 +241,10 @@ while [ $# -gt 0 ]; do
             ;;
         --size)
             shift
-            dst_size_G=$1
+            dstsize_G=$1
             shift
-            is_uint "${dst_size_G}" || {
-                usage_error "invalid value '${dst_size_G}' for option '--size', expected unsigned integer"
+            is_uint "${dstsize_G}" || {
+                usage_error "invalid value '${dstsize_G}' for option '--size', expected unsigned integer"
             }
             ;;
         -f|--force)
@@ -273,17 +273,17 @@ if [ $# -ne 2 ]; then
     usage_error "invalid number of arguments ($#), expected 2"
 fi
 
-src_filepath_G=$(readlink -e $1)
-dst_filepath_G=$(readlink -f $2)
+srcfile_G=$(readlink -e $1)
+dstfile_G=$(readlink -f $2)
 
-if [ ${force_G} -eq 0 -a -f "${dst_filepath_G}" ]; then
-    echo "error: destination file '${dst_filepath_G}' already exists, use --force to overwrite" >&2
+if [ ${force_G} -eq 0 -a -f "${dstfile_G}" ]; then
+    echo "error: destination file '${dstfile_G}' already exists, use --force to overwrite" >&2
     exit 1
 fi
 
 trap on_exit EXIT
 
-src_fsroot_G=$(mktemp -d)
+srcmountdir_G=$(mktemp -d)
 
-mount -o loop,ro "${src_filepath_G}" "${src_fsroot_G}"
-${clone_func_G}
+mount -o loop,ro "${srcfile_G}" "${srcmountdir_G}"
+${clonefunc_G}
