Add --force to overwrite local Git hooks

diff --git a/parts/devscripts/bin/puavo-install-git-hooks b/parts/devscripts/bin/puavo-install-git-hooks
--- a/parts/devscripts/bin/puavo-install-git-hooks
+++ b/parts/devscripts/bin/puavo-install-git-hooks
@@ -4,6 +4,51 @@ set -eu
 
 . puavo-devscripts-env
 
+usage_error()
+{
+    echo "error: $1" >&2
+    echo "Try '$0 --help' for more information". >&2
+    return 1
+}
+
+force=false
+
+while [ $# -gt 0 ]; do
+    case $1 in
+        -h|--help)
+            shift
+            echo "Usage: $0"
+            echo
+            echo "Copy Git hooks from ${PUAVO_DEVSCRIPTS_SHAREDIR}/git-hooks"
+            echo "to the local git repository."
+            echo
+            echo "Options:"
+            echo "    -f, --force                  overwrite existing hooks"
+            echo "    -h, --help                   print help and exit"
+            echo
+            exit 0
+            ;;
+        -f|--force)
+            shift
+            force=true
+            ;;
+        --)
+            shift
+            break
+            ;;
+        -*)
+            usage_error "invalid argument '$1'"
+            ;;
+        *)
+            break
+            ;;
+    esac
+done
+
+if [ $# -ne 0 ]; then
+    usage_error "invalid number of arguments ($#), expected 0"
+fi
+
 rootdir=$(git rev-parse --show-toplevel)
 
 src_hooks=$(find "${PUAVO_DEVSCRIPTS_SHAREDIR}/git-hooks" \
@@ -12,9 +57,13 @@ src_hooks=$(find "${PUAVO_DEVSCRIPTS_SHAREDIR}/git-hooks" \
 while read src_hook; do
     hook=$(basename "${src_hook}")
     dst_hook="${rootdir}/.git/hooks/${hook}"
-    if [ -e "${dst_hook}" ]; then
-        echo "warning: destination '${dst_hook}' already exists, skipping" >&2
-        continue
+    if $force; then
+        cp -v "${src_hook}" "${dst_hook}"
+    else
+        if [ -e "${dst_hook}" ]; then
+            echo "warning: destination '${dst_hook}' already exists, use -f to overwrite" >&2
+            continue
+        fi
+        cp -v -n "${src_hook}" "${dst_hook}"
     fi
-    cp -v -n "${src_hook}" "${dst_hook}"
 done <<<"${src_hooks}"
