Make DISTRIB_CODENAME lookup work also on Debian.

diff --git a/parts/devscripts/bin/puavo-build-debian-dir b/parts/devscripts/bin/puavo-build-debian-dir
--- a/parts/devscripts/bin/puavo-build-debian-dir
+++ b/parts/devscripts/bin/puavo-build-debian-dir
@@ -28,8 +28,12 @@ if [ -e debian ]; then
     exit 1
 fi
 
-# Get ubuntu version to $DISTRIB_CODENAME
-. /etc/lsb-release
+# Get Debian version to $DISTRIB_CODENAME
+DISTRIB_CODENAME=$(lsb_release --codename --short)
+if [ -z "$DISTRIB_CODENAME" ]; then
+    echo "Could not determine distribution codename" >&2
+    exit 1
+fi
 
 mkdir debian
 
