Add --help option

diff --git a/parts/autopilot/bin/puavo-autopilot-detect-png b/parts/autopilot/bin/puavo-autopilot-detect-png
--- a/parts/autopilot/bin/puavo-autopilot-detect-png
+++ b/parts/autopilot/bin/puavo-autopilot-detect-png
@@ -31,10 +31,41 @@ on_exit()
     exit $exitval
 }
 
+usage_error()
+{
+    echo "error: $1" >&2
+    echo "Try '$0 --help' for more information". >&2
+    return 1
+}
+
+while [ $# -gt 0 ]; do
+    case $1 in
+        -h|--help)
+            shift
+            echo "Usage: $0 PNG"
+            echo
+            echo "Try to find the given image from the current screen."
+            echo
+            echo "Options:"
+            echo "    -h, --help                   print help and exit"
+            echo
+            exit 0
+            ;;
+        --)
+            shift
+            break
+            ;;
+        -*)
+            usage_error "invalid option '$1'"
+            ;;
+        *)
+            break
+            ;;
+    esac
+done
+
 if [ $# -ne 1 ]; then
-    echo "E: missing argument" >&2
-    echo "Usage: $0 PNG" >&2
-    exit 1
+    usage_error "invalid number of arguments ($#), expected 1"
 fi
 
 png=$(readlink -e "$1") || {
