Add --try-times option to detect images at most N times

diff --git a/parts/autopilot/bin/puavo-autopilot-detect-png b/parts/autopilot/bin/puavo-autopilot-detect-png
--- a/parts/autopilot/bin/puavo-autopilot-detect-png
+++ b/parts/autopilot/bin/puavo-autopilot-detect-png
@@ -24,8 +24,8 @@ on_exit()
     ## up and exiting.
     set +e
 
-    if [ -n "${workdir}" ]; then
-        rm -rf "${workdir}" || exitval=$?
+    if [ -n "${screenshot}" ]; then
+        rm -f "${screenshot}" || exitval=$?
     fi
 
     exit $exitval
@@ -38,6 +38,8 @@ usage_error()
     return 1
 }
 
+try_times=
+
 while [ $# -gt 0 ]; do
     case $1 in
         -h|--help)
@@ -49,9 +51,23 @@ Try to find the given image from the current screen.
 
 Options:
     -h, --help                   print help and exit
+    -n N, --try-times N          try at most N times before giving up
 
 EOF
             exit 0
+            ;;
+        -n|--try-times)
+            [ -z "${try_times}" ] || usage_error "option $1 is already given"
+            [ $# -ge 2 ] || usage_error "missing value for option $1"
+            case $2 in
+                ''|*[!0-9]*|0*)
+                    usage_error "invalid value for option $1"
+                    ;;
+                *)
+                    ;;
+            esac
+            try_times=$2
+            shift 2
             ;;
         --)
             shift
@@ -66,6 +82,9 @@ EOF
     esac
 done
 
+## Default values for parameters.
+[ -n "${try_times}" ] || try_times=1
+
 if [ $# -ne 1 ]; then
     usage_error "invalid number of arguments ($#), expected 1"
 fi
@@ -77,22 +96,29 @@ png=$(readlink -e "$1") || {
 shift
 
 exitval=1
-workdir=''
+screenshot=
 
 # After this point, we are going to make permanent changes, hence we
 # setup cleanup hook to make sure we do not leave anything behind us.
 
 trap on_exit EXIT
 
-workdir=$(mktemp -d)
+screenshot=$(mktemp --suffix='.png')
 
-cd "${workdir}"
+ntries=0
+while [ "${ntries}" -lt "${try_times}" ]; do
+    escrotum "${screenshot}" >/dev/null || {
+        echo 'error: failed to take a screenshot' >&2
+        exit 1
+    }
 
-escrotum screenshot.png >/dev/null || {
-    echo 'error: failed to take a screenshot' >&2
-    exit 1
-}
+    xy=$(visgrep "${screenshot}" "${png}") || {
+        ntries=$((ntries + 1))
+        continue
+    }
 
-visgrep screenshot.png "${png}" | sed -n -r 's/^([0-9]+),([0-9]+) .*$/\1 \2/p'
+    echo "${xy}" | sed -n -r 's/^([0-9]+),([0-9]+) .*$/\1 \2/p'
+    break
+done
 
 exitval=0
