Trivial cleanup

diff --git a/parts/autopilot/bin/puavo-autopilot-detect-png b/parts/autopilot/bin/puavo-autopilot-detect-png
--- a/parts/autopilot/bin/puavo-autopilot-detect-png
+++ b/parts/autopilot/bin/puavo-autopilot-detect-png
@@ -34,7 +34,7 @@ on_exit()
 usage_error()
 {
     echo "error: $1" >&2
-    echo "Try '$0 --help' for more information". >&2
+    echo "Run '$0 --help' for more information". >&2
     return 1
 }
 
@@ -42,13 +42,15 @@ while [ $# -gt 0 ]; do
     case $1 in
         -h|--help)
             shift
-            echo "Usage: $0 PNG"
-            echo
-            echo "Try to find the given image from the current screen."
-            echo
-            echo "Options:"
-            echo "    -h, --help                   print help and exit"
-            echo
+            cat <<EOF
+Usage: $0 PNG
+
+Try to find the given image from the current screen.
+
+Options:
+    -h, --help                   print help and exit
+
+EOF
             exit 0
             ;;
         --)
@@ -87,7 +89,7 @@ workdir=$(mktemp -d)
 cd "${workdir}"
 
 escrotum screenshot.png >/dev/null || {
-    echo "error: failed to take a screenshot" >&2
+    echo 'error: failed to take a screenshot' >&2
     exit 1
 }
 
