Use -b option to pass branch name argument
Branch name is appended to the distribution name to form the directory
name of the pool.

Normally the destination directory for packages is of the form
'pool/DISTRIBUTION/COMPONENT/FIRST_CHARACTER_OF_THE_PACKAGE_NAME'. For
example for webmenu built for Quantal, the destination directory would
be 'pool/quantal/main/w'. Now if '-b updates' argument was passed the
directory path would be 'pool/quantal-updates/main/w'. This allows one
to decide the publish target at import time rather than packaging
time. The pool directory structre is then used to generate equivalent
dists directory.

diff --git a/parts/aptirepo/aptirepo-import b/parts/aptirepo/aptirepo-import
--- a/parts/aptirepo/aptirepo-import
+++ b/parts/aptirepo/aptirepo-import
@@ -101,6 +101,10 @@ import_changes()
             component="main"
         fi
 
+        if [ -n "${APTIREPO_BRANCH}" ]; then
+            distribution="${distribution}-${APTIREPO_BRANCH}"
+        fi
+
         dstdir="pool/${distribution}/${component}/$(echo ${source_name} | head -c1)/${source_name}"
 
         mkdir -p "${dstdir}" || {
@@ -121,9 +125,33 @@ APTIREPO_ROOT=${APTIREPO_ROOT:-.}
 
 cd "${APTIREPO_ROOT}"
 
+APTIREPO_BRANCH=''
+
+while getopts "b:" flag; do
+    case $flag in
+        b)
+            if [ -n "${APTIREPO_BRANCH}" ]; then
+                echo "-b can be used only once" >&2
+                exit 1
+            fi
+            # TODO: validate input
+            APTIREPO_BRANCH="${OPTARG}"
+            ;;
+        ?)
+            exit 1
+            ;;
+        *)
+            echo "getopts failed catastrophically" >&2
+            exit 1
+            ;;
+  esac
+done
+
+shift $((OPTIND-1))
+
 if [ $# -ne 1 ]; then
     echo "wrong number of arguments" >&2
-    echo "Usage: $(basename $0) FILE" >&2
+    echo "Usage: $(basename $0) [-b BRANCH] FILE" >&2
     exit 1
 fi
 
