Wrap long lines

diff --git a/parts/aptirepo/aptirepo-update b/parts/aptirepo/aptirepo-update
--- a/parts/aptirepo/aptirepo-update
+++ b/parts/aptirepo/aptirepo-update
@@ -5,7 +5,7 @@ set -u
 APTIREPO_ROOT=${APTIREPO_ROOT:-.}
 
 cd "${APTIREPO_ROOT}" || {
-    echo "could not change the current directory to repository root directory '${APTIREPO_ROOT}'" >&2
+    echo "cannot access the repository root directory '${APTIREPO_ROOT}'" >&2
     exit 1
 }
 
@@ -15,22 +15,35 @@ if [ ! -d .aptirepo ]; then
 fi
 
 
-## - generate Sources and Packages For each architecture in each component in each distribution
+list_dirs()
+{
+    find "$1" -mindepth 1 -maxdepth 1 -type d -printf '%f\n'
+}
+
+## - generate Sources and Packages For each architecture in each
+##   component in each distribution
 ## - generate Contents for each component in each distribution
 ## - generate Release for each distribution
-find dists -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | while read dist; do
-    find "dists/${dist}" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | while read comp; do
-        apt-ftparchive --db .aptirepo/db contents "pool/${dist}/${comp}" | gzip >"dists/${dist}/${comp}/Contents.gz"
-        find "dists/${dist}/${comp}" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | while read archdir; do
+list_dirs dists | while read dist; do
+    list_dirs "dists/${dist}" | while read comp; do
+        apt-ftparchive --db .aptirepo/db contents "pool/${dist}/${comp}" \
+            | gzip >"dists/${dist}/${comp}/Contents.gz"
+        list_dirs "dists/${dist}/${comp}" | while read archdir; do
             if [ "${archdir}" = "source" ]; then
-                apt-ftparchive sources "pool/${dist}/${comp}" >"dists/${dist}/${comp}/${archdir}/Sources"
-                gzip -c "dists/${dist}/${comp}/${archdir}/Sources" >"dists/${dist}/${comp}/${archdir}/Sources.gz"
+                apt-ftparchive sources "pool/${dist}/${comp}" \
+                    >"dists/${dist}/${comp}/${archdir}/Sources"
+                gzip -c "dists/${dist}/${comp}/${archdir}/Sources" \
+                    >"dists/${dist}/${comp}/${archdir}/Sources.gz"
             else
-                apt-ftparchive --db .aptirepo/db --arch "${archdir#binary-}" packages "pool/${dist}/${comp}" >"dists/${dist}/${comp}/${archdir}/Packages"
-                gzip -c "dists/${dist}/${comp}/${archdir}/Packages" >"dists/${dist}/${comp}/${archdir}/Packages.gz"
+                apt-ftparchive --db .aptirepo/db --arch "${archdir#binary-}" \
+                    packages "pool/${dist}/${comp}" \
+                    >"dists/${dist}/${comp}/${archdir}/Packages"
+                gzip -c "dists/${dist}/${comp}/${archdir}/Packages" \
+                    >"dists/${dist}/${comp}/${archdir}/Packages.gz"
             fi
         done
     done
+
     comps=$(find "dists/${dist}" -mindepth 1 -maxdepth 1 -type d -printf '%f ')
     archs=$(find "dists/${dist}" -mindepth 2 -maxdepth 2 -type d -printf '%f ')
     apt-ftparchive --db .aptirepo/db \
@@ -38,4 +51,5 @@ find dists -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | while read dist; do
         -o "APT::FTPArchive::Release::Components=${comps}" \
         -o "APT::FTPArchive::Release::Architectures=${archs}" \
         release "dists/${dist}" >"dists/${dist}/Release"
+
 done
