Allow Next-Exam to work in the examination mode.
As the Next-Exam app is a puavo-pkg, it exists under /images/puavo-pkg
and thus we must allow access there in the examination mode.

diff --git a/rules/exammode/files/puavo-examusersh b/rules/exammode/files/puavo-examusersh
--- a/rules/exammode/files/puavo-examusersh
+++ b/rules/exammode/files/puavo-examusersh
@@ -2,31 +2,45 @@
 
 set -eu
 
-if [ "$(tty)" = '/dev/tty42' ]; then
-  clear
-
-  dirs_to_hide='
-    /anon
-    /home
-    /images
-    /state
-    /tmp
-    /var/lib/puavo-exammode/user
-    /var/tmp
-  '
-
-  # not all of the ${dirs_to_hide} directories actually exist (depending on
-  # things), so check them before adding to --tmpfs arguments
-  bwrap_tmpfs_args=''
-  for dir in $dirs_to_hide; do
-    if [ -d "$dir" ]; then
-      bwrap_tmpfs_args="${bwrap_tmpfs_args} --tmpfs ${dir}"
-    fi
-  done
-
-  exec env HOME=/var/lib/puavo-exammode/user \
-    bwrap --dev-bind / / $bwrap_tmpfs_args   \
-      startx /usr/lib/puavo-ltsp-client/exammode-session -- :42 > /dev/null 2>&1
+if [ "$(tty)" != '/dev/tty42' ]; then
+  exec /bin/bash
 fi
 
-exec /bin/bash
+clear
+
+dirs_to_hide='
+  /anon
+  /home
+  /images
+  /state
+  /tmp
+  /var/lib/puavo-exammode/user
+  /var/tmp
+'
+
+allow_access_to_images=false
+if ! exam_session_type=$(jq -r .type /var/lib/puavo-exammode/session.json \
+                           2>/dev/null); then
+  echo 'could not lookup the exam session type' >&2
+  exit 1
+fi
+if [ "$exam_session_type" = 'next-exam-session' ]; then
+  allow_access_to_images=true
+fi
+
+# not all of the ${dirs_to_hide} directories actually exist (depending on
+# things), so check them before adding to --tmpfs arguments
+bwrap_tmpfs_args=''
+for dir in $dirs_to_hide; do
+  if [ "$dir" = '/images' ] && $allow_access_to_images; then
+    # the Next-Exam session cannot work without access to /images/puavo-pkg
+    continue
+  fi
+  if [ -d "$dir" ]; then
+    bwrap_tmpfs_args="${bwrap_tmpfs_args} --tmpfs ${dir}"
+  fi
+done
+
+exec env HOME=/var/lib/puavo-exammode/user \
+  bwrap --dev-bind / / $bwrap_tmpfs_args   \
+    startx /usr/lib/puavo-ltsp-client/exammode-session -- :42 > /dev/null 2>&1
