Openvpn replaced with vtund

diff --git a/parts/wlan/sbin/puavo-wlanap-configure b/parts/wlan/sbin/puavo-wlanap-configure
--- a/parts/wlan/sbin/puavo-wlanap-configure
+++ b/parts/wlan/sbin/puavo-wlanap-configure
@@ -1,216 +1,88 @@
-#!/usr/bin/ruby
+#!/bin/sh
 
-require 'resolv'
-require 'syslog'
-require 'yaml'
+set -u
 
-def get_serverip
-  File.open('/etc/ltsp/getltscfg-cluster.conf').each do |line|
-    match = line.match(/^SERVER=(.*)$/)
-    if match
-      return match[1]
-    end
-  end
-  Syslog.err('%s', 'Server IP is not known, aborting')
-  exit(1)
-end
+. /etc/puavo-wlanap.conf
 
-Syslog.open(File.basename($0), Syslog::LOG_PID)
+while read line
+do
+    case line in
+    	openwlan)
+    	    wlantype="open"
+    	    ;;
+    	eapwlan)
+    	    wlantype="eap"
+    	    ;;
+    	pskwlan)
+    	    wlantype="psk"
+    	    ;;
+    	*)
+	    if [ -z $wlantype ]
+	    then
+		wlantype=$(echo $line | sed -n 's/^wlantype:\(.*\)$/\1/p')
+	    fi
 
-#
-# Determine the boot server where OpenVPN and RADIUS servers
-# should be listening.
-#
+	    if [ -z $wlanch ]
+	    then
+		wlanch=$(echo $line | sed -n 's/^wlanch:\(.*\)$/\1/p')
+	    fi
 
-Syslog.info('%s', 'Checking wlan configuration')
+	    if [ -z $wlanif ]
+	    then
+		wlanif=$(echo $line | sed -n 's/^wlanif:\(.*\)$/\1/p')
+	    fi
 
-auth_server_addr   = get_serverip()
-server_fqdn = nil
+	    if [ -z $ssid ]
+	    then
+		ssid=$(echo $line | sed -n 's/^ssid:\(.*\)$/\1/p')
+	    fi
 
-# recover even if DNS is down
-until server_fqdn do
-  begin
-    server_fqdn = Resolv.getname(auth_server_addr)
-  rescue
-    Syslog.warn('%s', 'Problem reaching DNS server')
-    sleep 10
-  end
-end
+	    if [ -z $password ]
+	    then
+		password=$(echo $line | sed -n 's/^psk:\(.*\)$/\1/p')
+	    fi
 
-#
-# Get server specific wlantype, password and ssid settings.
-#
+    	    ;;
+    esac
+done < $puavoroot/hosttags
 
-conf = (YAML::load_file("/etc/puavo-wlanap/init.conf") || {}) rescue {}
+if [ -z "$wlanch" ]
+then
+    logger -p user.info "wlan channel is not set, exiting"
+    exit 0
+fi
 
-wlanif         = conf['wlanif']
-wlantype       = conf['wlantype']
-wpa_passphrase = conf['password']
-ssid           = conf['ssid']
-puavoroot      = conf['puavoroot']
-wlan_ca        = conf['wlan-ca']
-wlan_key       = conf['wlan-key']
-wlan_cert      = conf['wlan-cert']
+if [ -z "$ssid" ]
+then
+    logger -p user.err "wlan ssid is not set, aborting"
+    exit 1
+fi
 
-File.open("/etc/puavo-wlanap/wlan-ca.crt", "w") do |file|
-  file.puts(wlan_ca)
-end
+if [ -z "$wlantype" ]
+then
+    logger -p user.err "wlan type is not set, aborting"
+    exit 1
+fi
 
-File.open("/etc/puavo-wlanap/wlan-client.key", "w", 0600) do |file|
-  file.puts(wlan_key)
-end
+if [ "$wlantype" = "psk" ]
+then
+    if [ ${#password} -lt 8 -o ${#password} -gt 63 ]
+    then
+	logger -p user.err "password must be 8-63 characters long, aborting"
+	exit 1
+    fi
+fi
 
-File.open("/etc/puavo-wlanap/wlan-client.crt", "w") do |file|
-  file.puts(wlan_cert)
-end
+sed -e "s/#{wlanif}/$wlanif/g" \
+    -e "s/#{ssid}/$ssid/g" \
+    -e "s/#{password}/$password/g" \
+    -e "s/#{eap_auth_server_addr}/$eap_auth_server_addr/g" \
+    -e "s/#{eap_auth_server_port}/$eap_auth_server_port/g" \
+    -e "s/#{eap_auth_server_shared_secret}/$eap_auth_server_shared_secret/g" \
+    -e "s/#{eap_acct_server_addr}/$eap_acct_server_addr/g" \
+    -e "s/#{eap_acct_server_port}/$eap_acct_server_port/g" \
+    -e "s/#{eap_acct_server_shared_secret}/$eap_acct_server_shared_secret/g" \
+    /etc/puavo-wlanap/${wlantype}_hostapd.conf.template > /var/tmp/puavo-wlanap/hostapd.conf
 
-Syslog.info('%s',
-            "Access point defaults: wlantype=#{ wlantype } " \
-              + "ssid=#{ ssid }")
-
-#
-# Get (mandatory) wlan channel parameter from host tags,
-# and possibly override other parameters.
-#
-
-wlanch = nil           # mandatory parameter to be set with host tag
-
-(File.readlines("#{puavoroot}/hosttags").map &:strip).each do |line|
-  set_wlantype = lambda { |type|
-                   wlantype = type
-                   Syslog.info('%s',
-                               "From host tags set wlantype=#{ wlantype }")
-                 }
-
-  case line
-    when /^wlantype:(.*)$/
-      set_wlantype.call($1)
-    when 'openwlan'             # XXX for backwards compatibility
-      set_wlantype.call('open')
-    when 'eapwlan'              # XXX for backwards compatibility
-      set_wlantype.call('eap')
-    when 'pskwlan'              # XXX for backwards compatibility
-      set_wlantype.call('psk')
-    when /^wlanch(?:|:)(\d+)$/  # XXX (?:|:) for backwards compatibility
-      wlanch = $1
-      Syslog.info('%s', "From host tags set wlanch=#{ wlanch }")
-    when /^wlanif(?:|:)(\d+)$/  # XXX (?:|:) for backwards compatibility
-      wlanif = "wlan#{$1}"
-      Syslog.info('%s', "From host tags set wlanif=#{ wlanif }")
-    when /^psk:(.*)$/
-      wpa_passphrase = $1
-      Syslog.info('%s', "From host tags set wpa_passphrase")
-    when /^ssid:(.*)$/
-      ssid = $1
-      Syslog.info('%s', "From host tags set ssid=#{ ssid }")
-  end
-end
-
-if not wlanch
-  Syslog.info('%s', 'Channel is not set, this host is not an access point')
-  exit(0)	# this is a normal condition
-end
-
-if not ssid
-  Syslog.info('%s', 'Ssid is not set, aborting')
-  exit(1)
-end
-
-if not %w(open eap psk).include?(wlantype)
-  Syslog.info('%s', "Wlantype '#{ wlantype }' is not supported, aborting")
-  exit(1)
-end
-
-if wlantype == 'psk'
-  if wpa_passphrase.nil? || wpa_passphrase.empty?
-    Syslog.info('%s', "Password is not set, yet wlan type is 'psk', aborting")
-    exit(1)
-  end
-  if wpa_passphrase.length < 8 || 63 < wpa_passphrase.length
-    Syslog.info('%s',
-                "Password must be between 8-63 characters long, aborting")
-    exit(1)
-  end
-end
-
-File.open("/etc/puavo-wlanap/hostapd.conf", "w") do |config|
-  config.puts "interface=#{wlanif}"
-  config.puts "bridge=br.tap0"
-  config.puts "driver=nl80211"
-  config.puts "ssid=#{ssid}"
-  config.puts "country_code=FI"
-  config.puts "hw_mode=g"
-  config.puts "#channel=#{wlanch}"
-  config.puts "channel=6"
-  config.puts "max_num_sta=1000"
-  config.puts "wmm_enabled=1"
-  config.puts "ctrl_interface=/var/run/hostapd"
-  config.puts "ieee80211n=1"
-  config.puts "ht_capab=[HT40-]"
-  config.puts "#rsn_preauth_interfaces=eth0 br.tap0"
-  config.puts "wds_sta=1"
-  config.puts "#peerkey=1"
-
-  case wlantype
-  when 'open'
-    config.puts "wpa=0"
-  when 'eap'
-    config.puts "ieee8021x=1"
-    config.puts "auth_server_addr=#{eap_auth_server_addr}"
-    config.puts "auth_server_port=#{eap_auth_server_port}"
-    config.puts "auth_server_shared_secret=#{eap_auth_server_shared_secret}"
-    config.puts "acct_server_addr=#{eap_acct_server_addr}"
-    config.puts "acct_server_port=#{eap_acct_server_port}"
-    config.puts "acct_server_shared_secret=#{eap_acct_server_shared_secret}"
-    config.puts "wpa=2"
-    config.puts "auth_algs=3"
-    config.puts "#wpa_pairwise=TKIP CCMP"
-    config.puts "rsn_pairwise=CCMP"
-    config.puts "wpa_key_mgmt=WPA-EAP"
-    config.puts "eapol_version=1"
-    config.puts "eapol_key_index_workaround=1"
-    config.puts "eap_reauth_period=0"
-    config.puts "wpa_strict_rekey=0"
-    config.puts "wpa_group_rekey=0"
-    config.puts "rsn_preauth=1"
-    config.puts "wpa_gmk_rekey=0"
-  when 'psk'
-    config.puts "wpa=2"
-    config.puts "auth_algs=3"
-    config.puts "wpa_passphrase=#{wpa_passphrase}"
-    config.puts "#wpa_pairwise=TKIP CCMP"
-    config.puts "rsn_pairwise=CCMP"
-    config.puts "wpa_key_mgmt=WPA-PSK"
-    config.puts "eapol_version=1"
-    config.puts "eapol_key_index_workaround=1"
-    config.puts "eap_reauth_period=0"
-    config.puts "wpa_strict_rekey=0"
-    config.puts "wpa_group_rekey=0"
-    config.puts "#rsn_preauth=1"
-    config.puts "wpa_gmk_rekey=0"
-  end
-end
-
-Syslog.info('%s', 'Wrote hostapd configurations')
-
-File.open("/etc/openvpn/puavo-wlanap.conf", "w") do |config|
-  config.puts "client"
-  config.puts "dev tap0"
-  config.puts "remote #{server_fqdn}"
-  config.puts "port 956"
-  config.puts "proto tcp-client"
-  config.puts "up \"/usr/share/puavo-wlanap/openvpn-up.sh\""
-  config.puts "down \"/usr/share/puavo-wlanap/openvpn-down.sh\""
-  config.puts "ca \"/etc/puavo-wlanap/wlan-ca.crt\""
-  config.puts "cert \"/etc/puavo-wlanap/wlan-client.crt\""
-  config.puts "key \"/etc/puavo-wlanap/wlan-client.key\""
-
-  config.puts "keepalive 10 60"
-  config.puts "persist-tun"
-  config.puts "persist-key"
-  config.puts "up-delay"
-end
-
-Syslog.info('%s', 'Wrote openvpn configurations')
-
-Syslog.close
+sed -e "s/#{wlanif}/$wlanif/g" \
+    /etc/puavo-wlanap/vtund.conf.template > /var/tmp/puavo-wlanap/vtund.conf
