In puavo-pwa, get browser to use from "/var/lib/puavo-pwa/${pwa}/browser".

diff --git a/rules/progressive_web_applications/files/puavo-pwa b/rules/progressive_web_applications/files/puavo-pwa
--- a/rules/progressive_web_applications/files/puavo-pwa
+++ b/rules/progressive_web_applications/files/puavo-pwa
@@ -17,6 +17,23 @@ cleanup() {
   fi
 }
 
+get_browser() {
+  local browser pwa_dir
+  pwa_dir=$1
+
+  browser=$(cat "${pwa_dir}/browser" 2>/dev/null || true)
+  case "$browser" in
+    chrome|chromium)
+      ;;
+    *)
+      echo "Unsupported browser '${browser}' in PWA ${pwa_dir}" >&2
+      return 1
+      ;;
+  esac
+
+  printf %s "$browser"
+}
+
 get_browser_bin_name() {
   if [ "$browser" = 'chrome' ]; then
     printf %s google-chrome-stable
@@ -35,8 +52,6 @@ get_browser_preferences_path() {
   printf %s ~/".config/${browser}/Default/Preferences"
 }
 
-set -x
-
 # XXX the browser should be configurable to chromium or chrome with a command
 # XXX line parameter or something?  or maybe we have it in
 # XXX /var/lib/puavo-pwa/${pwa_name}/browser ?
@@ -44,12 +59,6 @@ set -x
 
 # XXX we should also check that chrome/chromium is configured to install
 # XXX the particular PWA we need!
-
-# XXX $browser must be chrome or chromium
-browser=chrome
-browser=chromium
-browser_bin=$(get_browser_bin_name "$browser")
-browser_preferences_path=$(get_browser_preferences_path "$browser")
 
 browser_pid=
 xvfb_pid=
@@ -109,8 +118,6 @@ lookup_app_id() {
 
 trap cleanup 0 ABRT INT PIPE QUIT TERM
 
-manifests_dir='/var/lib/puavo-pwa/manifests'
-
 pwa_name=${1:-}
 
 if [ -z "$pwa_name" ]; then
@@ -118,7 +125,21 @@ if [ -z "$pwa_name" ]; then
   exit 1
 fi
 
-manifest_path="${manifests_dir}/${pwa_name}.json"
+pwa_dir="/var/lib/puavo-pwa/${pwa_name}"
+manifest_path="${pwa_dir}/manifest.json"
+
+if [ ! -d "$pwa_dir" ]; then
+  echo "PWA '${pwa_name}' has not been setup for use" >&2
+  exit 1
+fi
+
+if ! browser=$(get_browser "$pwa_dir"); then
+  echo 'Could not determine the browser to use' >&2
+  exit 1
+fi
+
+browser_bin=$(get_browser_bin_name "$browser")
+browser_preferences_path=$(get_browser_preferences_path "$browser")
 
 pwa_url="$(jq -r .start_url "$manifest_path" 2>/dev/null || true)"
 if [ -z "$pwa_url" -o "$pwa_url" = 'null' ]; then
