Revert "Make /etc/puavo-conf/scripts/manage_system_services a bit faster"
This reverts commit c59314da18c320d0202e11727cdcf50f95ef1f38.

This is not as easy as this.  "nbd" is not handled correctly
because of "@" in the service-file name and sysv-fallbacks are
not handled (slapd for example).

diff --git a/parts/core/puavo-conf/scripts/manage_system_services b/parts/core/puavo-conf/scripts/manage_system_services
--- a/parts/core/puavo-conf/scripts/manage_system_services
+++ b/parts/core/puavo-conf/scripts/manage_system_services
@@ -28,14 +28,10 @@ services='
 
 status=0
 
-target_wants_dir='/etc/systemd/system/multi-user.target.wants'
+# XXX look if this is slow and could be optimized (skipping systemctl-tool?)
 
 for service in ${services}; do
-  if ! enabled=$(puavo-conf "puavo.service.${service}.enabled"); then
-    echo "No puavo-conf variable for service '${service}' status" >&2
-    status=1
-    continue
-  fi
+  enabled=$(puavo-conf "puavo.service.${service}.enabled")
 
   # As an exception, do not run puavo-vpn-client-dnsmasq on netboot devices,
   # because that will mess up dns configuration (XXX perhaps we need a
@@ -47,27 +43,16 @@ for service in ${services}; do
     fi
   fi
 
-  if [ "${enabled}" != 'true' ]; then
-    if ! rm -f "${target_wants_dir}/${service}.service"; then
-      echo "Could not disable service '${service}'" >&2
+  if [ "${enabled}" = 'true' ]; then
+    if ! systemctl enable "${service}"; then
+      echo "Could not enable ${service}" >&2
       status=1
     fi
-    continue
-  fi
-
-  if [ -e "/lib/systemd/system/${service}.service" ]; then
-    service_target="/lib/systemd/system/${service}.service"
-  elif [ -e "/etc/systemd/system/${service}.service" ]; then
-    service_target="/etc/systemd/system/${service}.service"
   else
-    echo "Could not find service '${service}' to enable" >&2
-    status=1
-    continue
-  fi
-
-  if ! ln -fns "$service_target" "${target_wants_dir}/${service}.service"; then
-    echo "Could not disable service '${service}'" >&2
-    status=1
+    if ! systemctl disable "${service}"; then
+      echo "Could not disable ${service}" >&2
+      status=1
+    fi
   fi
 done
 
