Mount /images/puavo-pkg from bootservers on fatclients.

diff --git a/parts/core/puavo-conf/scripts/setup_puavopkgs b/parts/core/puavo-conf/scripts/setup_puavopkgs
--- a/parts/core/puavo-conf/scripts/setup_puavopkgs
+++ b/parts/core/puavo-conf/scripts/setup_puavopkgs
@@ -52,10 +52,22 @@ fi
 # puavo-pkg images.  (Note that this does not install or update
 # the puavo-pkg packages, only sets them up at boottime).
 
-host_puavo_pkg_cachedir='/images/puavo-pkg/cache'
-host_puavo_pkg_rootdir='/images/puavo-pkg/root'
+host_puavo_pkg_dir='/images/puavo-pkg'
+host_puavo_pkg_cachedir="${host_puavo_pkg_dir}/cache"
+host_puavo_pkg_rootdir="${host_puavo_pkg_dir}/root"
 
 install_puavo_pkg_conf "$host_puavo_pkg_cachedir" "$host_puavo_pkg_rootdir"
+
+# mount /images/puavo-pkg from bootserver in case we have booted from network
+if [ -e /run/puavo/nbd-server ]; then
+  read nbd_server < /run/puavo/nbd-server
+  mkdir -p "$host_puavo_pkg_dir"
+  if ! timeout -k 5 30 mount -t nfs4 -o sec=sys "${nbd_server}:/puavo-pkg" \
+                                                "$host_puavo_pkg_dir"; then
+    echo "could not mount ${nbd_server}:/puavo-pkg" >&2
+    exit 1
+  fi
+fi
 
 # Setup puavo-pkgs from under /images/puavo-pkg only if they are missing
 # from the system image, or the versions under /images/puavo-pkg are
