Some changes to background image handling through puavo-conf.
Support absolute paths in both "puavo.greeter.background.default"
and "puavo.desktop.background".  Change
"puavo.greeter.background.random.subdir" key name to
"puavo.greeter.background.random.dir" reflecting the fact that
absolute directories are okay with that puavo-conf variable
as well.  When not using absolute directories, be more relaxed
when finding matches for all of the above: as long as a
file/directory exists under "/usr/share/backgrounds" that
matches exactly the puavo-conf value, use the first one that
can be found.

After some inspection it appears we have never used
the dynamic/firstlogin functionality with puavo-os,
so I feel I can change the API without much risk.

Closes #538 and #539.

diff --git a/parts/core/puavo-conf/scripts/setup_dconf_settings b/parts/core/puavo-conf/scripts/setup_dconf_settings
--- a/parts/core/puavo-conf/scripts/setup_dconf_settings
+++ b/parts/core/puavo-conf/scripts/setup_dconf_settings
@@ -87,11 +87,21 @@ fi
 
 puavo_desktop_background=$(puavo-conf puavo.desktop.background)
 
-if [ -n "$puavo_desktop_background" \
-     -a -e "/usr/share/backgrounds/${puavo_desktop_background}" ]; then
+if [ -n "$puavo_desktop_background" ]; then
+  case "$puavo_desktop_background" in
+    /*) desktop_background_path="$puavo_desktop_background" ;;
+    *)  desktop_background_path=$(find /usr/share/backgrounds \
+          '(' -type f -or -type l ')' -name "$puavo_desktop_background" \
+          -print -quit) ;;
+  esac
+  if [ ! -e "$desktop_background_path" ]; then
+    echo "could not find background ${desktop_background_path}" >&2
+    rm -f /etc/dconf/db/puavo-desktopbackground
+    exit 1
+  fi
   new_dconf_chunk puavo-desktopbackground <<EOF
 [org/gnome/desktop/background]
-picture-uri='file:///usr/share/backgrounds/${puavo_desktop_background}'
+picture-uri='file://${desktop_background_path}'
 EOF
 else
   rm -f /etc/dconf/db/puavo-desktopbackground
diff --git a/rules/gdm/files/setup_loginscreen_background b/rules/gdm/files/setup_loginscreen_background
--- a/rules/gdm/files/setup_loginscreen_background
+++ b/rules/gdm/files/setup_loginscreen_background
@@ -5,16 +5,16 @@ set -eu
 set_background() {
   background_path=$1
 
-  [ -e "$background_path" ] || return 1
+  if [ ! -e "$background_path" ]; then
+    echo "could not find background ${background_path}" >&2
+    return 1
+  fi
 
   ln -fns "$background_path" /etc/gdm3/background.img
 }
 
-backgrounds_basedir=/usr/share/backgrounds/puavo-greeter
-backgrounds_randomdir="${backgrounds_basedir}/default"
-
+backgrounds_basedir=/usr/share/backgrounds
 background_firstlogin=$(puavo-conf puavo.greeter.background.firstlogin)
-
 background_path=''
 
 if [ ! -s /var/lib/extrausers/passwd -a -n "$background_firstlogin" ]; then
@@ -33,21 +33,24 @@ case "$background_mode" in
     ;;
   dynamic|firstlogin)
     if [ -n "$background" ]; then
-      if find "$backgrounds_basedir" '(' -type f -o -type l ')' -printf '%P\n' \
-        | grep -qx "$background"; then
-          background_path="${backgrounds_basedir}/${background}"
-      fi
+      case "$background" in
+        /*) background_path=$background ;;
+        *)  background_path=$(find "$backgrounds_basedir" \
+                                '(' -type f -o -type l ')' \
+                                 -name "$background" -print -quit) ;;
+      esac
     fi
     ;;
   random)
-    bg_random_subdir=$(puavo-conf puavo.greeter.background.random.subdir)
-    if [ -n "$bg_random_subdir" ]; then
-      if find "$backgrounds_basedir" -mindepth 1 -type d -printf '%P\n' \
-        | grep -qx "$bg_random_subdir"; then
-          backgrounds_randomdir="${backgrounds_basedir}/${bg_random_subdir}"
-          background_path=$(find "$backgrounds_randomdir" \
-            '(' -type f -o -type l ')' | sort -R | head -n1)
-      fi
+    bg_random_dir=$(puavo-conf puavo.greeter.background.random.dir)
+    if [ -n "$bg_random_dir" ]; then
+      case "$bg_random_dir" in
+        /*) ;;
+        *)  bg_random_dir=$(find "$backgrounds_basedir" -type d \
+                              -name "$bg_random_dir" -print -quit) ;;
+      esac
+      background_path=$(find "$bg_random_dir" \
+        '(' -type f -o -type l ')' | sort -R | head -n1)
     fi
     ;;
   *)
