In setup_grub_environment, avoid copying the Grub environment file in case it has not changed.  In case it has, move it into its place through a temporary file and then do "mv".
The point of this is to try to minimize the amount of copy
operations that are destructive for a very short while.
The "mv" command is probably not atomic on Linux with FAT,
but I think it is worth trying.

diff --git a/parts/core/puavo-conf/scripts/setup_grub_environment b/parts/core/puavo-conf/scripts/setup_grub_environment
--- a/parts/core/puavo-conf/scripts/setup_grub_environment
+++ b/parts/core/puavo-conf/scripts/setup_grub_environment
@@ -197,15 +197,20 @@ update_boot_device_environments() {
   local status=0
 
   for diskdev in $boot_disks; do
-    echo "installing GRUB environment to boot device $diskdev"
+    echo "installing GRUB environment to boot device ${diskdev}"
     if ! mount_disk_efi_partition "$diskdev"; then
       echo "failed to mount ${diskdev}" >&2
       status=1
       continue
     fi
-    if ! cp -p "$grubenv_path" "${UKI_ROOT}/grub/grubenv"; then
-      echo "failed to copy Grub environment to ${diskdev}" >&2
-      status=1
+    if ! cmp "$grubenv_path" "${UKI_ROOT}/grub/grubenv" >/dev/null 2>&1; then
+      if ! cp -p "$grubenv_path" "${UKI_ROOT}/grub/grubenv.tmp"; then
+        echo "failed to copy Grub environment to ${diskdev} (temporary file)" >&2
+        status=1
+      elif ! mv "${UKI_ROOT}/grub/grubenv.tmp" "${UKI_ROOT}/grub/grubenv"; then
+        echo "failed to move the Grub environment file in ${diskdev}" >&2
+        status=1
+      fi
     fi
     umount /boot/efi || true
   done
