Revert "Use nfs version 3 when mounting /images/puavo-pkg (readonly)"
This reverts commit 599ec93999fe5f52350f94e5f93ffc42fb656b16.

After some testing, I found that mounting nfs3 is not possible
before systemd has started some necessary services that mounting
depends on.  Mounting NFSv4 is possible.

diff --git a/parts/core/puavo-conf/scripts/setup_puavopkgs b/parts/core/puavo-conf/scripts/setup_puavopkgs
--- a/parts/core/puavo-conf/scripts/setup_puavopkgs
+++ b/parts/core/puavo-conf/scripts/setup_puavopkgs
@@ -166,11 +166,10 @@ setup_puavopkg_for_localboot_devices() {
 setup_puavopkg_for_netboot_devices() {
   # mount /images/puavo-pkg from bootserver in case we have booted from network
   read nbd_server < /run/puavo/nbd-server
-  mkdir -p /cow/puavo-pkg.rootdir /cow/puavo-pkg.workdir \
-           "$remote_mountdir" "${remote_mountdir}.rofs"
-  if ! timeout -k 5 30 mount -t nfs -o ro,nfsvers=3 \
-               "${nbd_server}:/images/puavo-pkg" "${remote_mountdir}.rofs"; then
-    echo "could not mount ${nbd_server}:/images/puavo-pkg" >&2
+  mkdir -p "$remote_mountdir"
+  if ! timeout -k 5 30 mount -t nfs4 -o ro,sec=sys "${nbd_server}:/images/puavo-pkg" \
+                                                   "$remote_mountdir"; then
+    echo "could not mount ${nbd_server}:/puavo-pkg" >&2
     return 1
   fi
 
