puavo-manage-efi: require excplicit disk devpath as arg
Previously, puavo-manage-efi expected to find just one ESP, but it's
certainly possible that there are multiple ESPs on different disks
etc. Require the disk of the Windows installation explicitly as an
argument.

setup_grub_environment script assumes the Windows installation disk is
the same which contains /images. Which is quite reasonable assumption:
we only support single-disk installations for dual-boot hosts.

diff --git a/parts/core/puavo-conf/scripts/setup_grub_environment b/parts/core/puavo-conf/scripts/setup_grub_environment
--- a/parts/core/puavo-conf/scripts/setup_grub_environment
+++ b/parts/core/puavo-conf/scripts/setup_grub_environment
@@ -74,12 +74,19 @@ setup_timeout() {
 }
 
 setup_windows_enabled() {
+  local grubdisk
+
+  grubdisk=$(puavo-get-disk-of-filepath /images) || {
+    echo 'ERROR: failed to get disk of images' >&2
+    return 1
+  }
+
   if [ "$(puavo-conf puavo.grub.windows.enabled)" = 'true' ]; then
-    puavo-manage-efi --no-efi-is-ok enable-windows || return 1
+    puavo-manage-efi --no-efi-is-ok enable-windows "${grubdisk}" || return 1
     grubedit set "puavo_grub_windows_enabled=true" || return 1
   else
     grubedit unset puavo_grub_windows_enabled || return 1
-    puavo-manage-efi --no-efi-is-ok disable-windows || return 1
+    puavo-manage-efi --no-efi-is-ok disable-windows "${grubdisk}" || return 1
   fi
 
   return 0
