Provide a more helpful error message in case we could not determine the target directory.

diff --git a/parts/ltsp/tools/image-build/puavo-imgbuild-tool b/parts/ltsp/tools/image-build/puavo-imgbuild-tool
--- a/parts/ltsp/tools/image-build/puavo-imgbuild-tool
+++ b/parts/ltsp/tools/image-build/puavo-imgbuild-tool
@@ -202,8 +202,9 @@ if [ -z "$target_dir" ]; then
       target_dir=$(/usr/lib/puavo-image-tools/puavo-ask-buildtarget-dir \
                      "$builds_dir")
     fi
-    [ -z "$target_dir" ] && usage
-  else
+  fi
+  if [ -z "$target_dir" ]; then
+    echo 'Could not determine target dir' >&2
     usage
   fi
 fi
