Upgrade openjdk-11 to version 11.0.23+9-1~deb11u1.

diff --git a/debs/openjdk-11/debian/tests/jtreg-autopkgtest.in b/debs/openjdk-11/debian/tests/jtreg-autopkgtest.in
--- a/debs/openjdk-11/debian/tests/jtreg-autopkgtest.in
+++ b/debs/openjdk-11/debian/tests/jtreg-autopkgtest.in
@@ -39,6 +39,11 @@ if [ ! -x "${JDK_TO_TEST}/bin/java" ]; then
   exit 1
 fi
 
+if [ ! -x "${BOOTJDK_HOME}/bin/java" ]; then
+  echo "Error: '${BOOTJDK_HOME}/bin/java' is not an executable." >&2
+  exit 1
+fi
+
 # restrict the tests to a few archs (set from debian/rules)
 if ! echo "${host_arch}" | grep -qE "^($(echo @jtreg_archs@ | tr ' ' '|'))$"; then
   echo "Error: ${host_arch} is not on the jtreg_archs list, ignoring it."
@@ -92,7 +97,7 @@ for i in 0 1 2; do
   report_path="${i}/JTreport"
   report_dir="${output_dir}/${report_path}"
   jtreg ${jt_options} \
-    -vmoption:-Djtreg.home=/usr/share/jtreg \
+    -J-Djtreg.home=/usr/share/jtreg \
     -verbose:summary \
     -automatic \
     -retain:none \
