Oops... I did not notice puavo-update-gtk-bookmarks was written with 4-column indents, and now the indentation style was inconsistent. Better fix it! ;-P

diff --git a/parts/sharedir/client/puavo-update-gtk-bookmarks b/parts/sharedir/client/puavo-update-gtk-bookmarks
--- a/parts/sharedir/client/puavo-update-gtk-bookmarks
+++ b/parts/sharedir/client/puavo-update-gtk-bookmarks
@@ -10,51 +10,51 @@ use_sambahomes() {
 }
 
 filter_out_our_bookmarks() {
-    local domain_re_pattern
-    domain_re_pattern=$(echo "^smb://homedir.${puavo_domain}" \
-                          | sed 's/\./\\./g')
+  local domain_re_pattern
+  domain_re_pattern=$(echo "^smb://homedir.${puavo_domain}" \
+			| sed 's/\./\\./g')
 
-    # Grep fails if the file is empty or missing, which is ok in this
-    # situation: it just means that there is not anything to preserve
-    # (or maybe means something else, but probably not serious).
-    egrep -v "\.puavo-sharedir|^file:///home/share/|${domain_re_pattern}" \
-      || true
+  # Grep fails if the file is empty or missing, which is ok in this
+  # situation: it just means that there is not anything to preserve
+  # (or maybe means something else, but probably not serious).
+  egrep -v "\.puavo-sharedir|^file:///home/share/|${domain_re_pattern}" \
+    || true
 }
 
 update_bookmarks() {
-    local bookmarksdir
-    local bookmarksfile
-    local schooldir_displayname
-    local sharename
-    local tmpfile
+  local bookmarksdir
+  local bookmarksfile
+  local schooldir_displayname
+  local sharename
+  local tmpfile
 
-    schooldir_displayname=$1
-    sharename=$2
-    bookmarksfile=$3
+  schooldir_displayname=$1
+  sharename=$2
+  bookmarksfile=$3
 
-    bookmarksdir=$(dirname "${bookmarksfile}")
-    mkdir -p "${bookmarksdir}"
+  bookmarksdir=$(dirname "${bookmarksfile}")
+  mkdir -p "${bookmarksdir}"
 
-    tmpfile="${bookmarksfile}.tmp"
+  tmpfile="${bookmarksfile}.tmp"
 
-    filter_out_our_bookmarks < "${bookmarksfile}" > "${tmpfile}"
+  filter_out_our_bookmarks < "${bookmarksfile}" > "${tmpfile}"
 
-    case "$puavo_hosttype" in
-        fatclient|ltspserver)
-            if use_sambahomes; then
-                echo "file://${HOME}/.puavo-sharedir.schooldir/${sharename}/$(id -gn) ${schooldir_displayname}" >> "${tmpfile}"
-            else
-                user_primary_group=$(id -gn)
-                echo "file:///home/share/${sharename}/${user_primary_group} ${schooldir_displayname}" >> "${tmpfile}"
-            fi
-            ;;
-        laptop)
-            # do nothing... we end up cleaning up old stuff from
-            # ${bookmarksfile}
-            ;;
-    esac
+  case "$puavo_hosttype" in
+    fatclient|ltspserver)
+      if use_sambahomes; then
+	echo "file://${HOME}/.puavo-sharedir.schooldir/${sharename}/$(id -gn) ${schooldir_displayname}" >> "${tmpfile}"
+      else
+	user_primary_group=$(id -gn)
+	echo "file:///home/share/${sharename}/${user_primary_group} ${schooldir_displayname}" >> "${tmpfile}"
+      fi
+      ;;
+    laptop)
+      # do nothing... we end up cleaning up old stuff from
+      # ${bookmarksfile}
+      ;;
+  esac
 
-    mv "${tmpfile}" "${bookmarksfile}"
+  mv "${tmpfile}" "${bookmarksfile}"
 }
 
 case "$(echo $LANG | cut -c 1-2)" in
