ap-dnsproxy: move iptables command to puavo-wlanap-dnsproxy
Previously, when iptables was modified directly from vtun-up/down
scripts, iptables was modified even when puavo-wlanap-dnsproxy was not
running. Now scripts just notify the main daemon about vtun-up/down
events, and the daemon is responsible of applying necessary iptables
changes. If puavo-wlanap-dnsproxy is not running, nothing happens, as it
should be.

diff --git a/parts/wlan/ap-dnsproxy/puavo-wlanap-dnsproxy b/parts/wlan/ap-dnsproxy/puavo-wlanap-dnsproxy
--- a/parts/wlan/ap-dnsproxy/puavo-wlanap-dnsproxy
+++ b/parts/wlan/ap-dnsproxy/puavo-wlanap-dnsproxy
@@ -54,4 +54,22 @@ dnsmasq \
     --pid-file="${PWAP_DNSPROXY_RUNDIR}/dnsmasq.pid" \
     ${dnsmasq_ptr_record_args} &
 
+nc -k -l -U "${PWAP_DNSPROXY_RUNDIR}/control.socket" | while read event wlanbridge; do
+    case "$event" in
+        vtun-up)
+            iptables -t nat -A PREROUTING -p udp --dport 53 -i "${wlanbridge}" -j REDIRECT --to-port 5353 || {
+                echo "W: failed to enable dns redirection" >&2
+            }
+            ;;
+        vtun-down)
+            iptables -t nat -D PREROUTING -p udp --dport 53 -i "${wlanbridge}" -j REDIRECT --to-port 5353 || {
+                echo "W: failed to disable dns redirection" >&2
+            }
+            ;;
+        *)
+            echo "W: received unknown event '${event} ${wlanbridge}'" >&2
+            ;;
+    esac
+done
+
 wait
