Some fixes and improvements to puavo-trigger-nightly-updates. Make it simpler (now just one script on cron, not tied to suspend/resume, meaning it might work from poweroff as well).

diff --git a/rules/nightly_updates/files/puavo-trigger-nightly-updates b/rules/nightly_updates/files/puavo-trigger-nightly-updates
--- a/rules/nightly_updates/files/puavo-trigger-nightly-updates
+++ b/rules/nightly_updates/files/puavo-trigger-nightly-updates
@@ -2,23 +2,176 @@
 
 set -eu
 
-lid_state() {
-  awk '$1 == "state:" { print $2 }' /proc/acpi/button/lid/LID/state \
-    2>/dev/null || true
-}
-
 if [ "$(puavo-conf puavo.admin.nightly.updates)" != 'true' ]; then
   exit 0
 fi
 
-if rtcwake --utc -m show | grep -Fqx 'alarm: off'; then
-  action_time=$(expr "$(printf %d 0x$(hostname -f | md5sum | cut -c 1-8))" % 180)
-  action_hour=$(expr 21 + "$action_time" / 60)
-  action_minute=$(expr "$action_time" % 60)
+exec 3< "$0"
+flock -nx 3 || exit 1
 
-  rtcwake -m no --date "${action_hour}:${action_minute}"
+ac_online_path='/sys/class/power_supply/AC/online'
+battery_capacity_path='/sys/class/power_supply/BAT0/capacity'
+lid_state_path='/proc/acpi/button/lid/LID/state'
+vpn_interface='vpn0'
+
+# some safeguards, this does not make much sense except on laptops
+mountpoint -q /state            || exit 0
+[ -e "$ac_online_path"        ] || exit 0
+[ -e "$battery_capacity_path" ] || exit 0
+[ -e "$lid_state_path"        ] || exit 0
+
+# our update window is 0:30 - 5:30 (plus time for updates)
+number_from_hostname="$(printf %d 0x$(hostname -f | md5sum | cut -c 1-8))"
+action_time=$(expr '(' 30 + "$number_from_hostname" ')' % 300)
+action_hour=$(expr "$action_time" / 60)
+action_minute=$(expr "$action_time" % 60)
+
+current_date=$(date -I)
+current_hour=$(date +%H)
+current_minute=$(date +%M)
+
+battery_capacity_over() {
+  requested_capacity=$1
+  capacity=$(cat "$battery_capacity_path" 2>/dev/null) || true
+  [ -n "$capacity" -a "$capacity" -ge "$requested_capacity" ]
+}
+
+image_is_updated() {
+  old_image_inode=$1
+  new_image_inode="$(stat -c %i /images/ltsp.img 2>/dev/null)" || true
+  [ -n "$new_image_inode" -a "$old_image_inode" -ne "$new_image_inode" ]
+}
+
+lid_state() {
+  awk '$1 == "state:" { print $2 }' "$lid_state_path" 2>/dev/null || true
+}
+
+on_ac_power() {
+  grep -Fqx 1 "$ac_online_path" 2>/dev/null
+}
+
+setup_rtcwake() {
+  if rtcwake --utc -m show | grep -Fqx 'alarm: off'; then
+    tomorrow=$(date -I --date=tomorrow)
+    logger -t puavo-trigger-nightly-updates -p user.notice \
+           "setting rtcwake to $tomorrow ${action_hour}:${action_minute}"
+    if rtcwake -m no --date "$tomorrow ${action_hour}:${action_minute}"; then
+      if [ ! -e /state/.do_nightly_update ]; then
+        echo "$tomorrow" > /state/.do_nightly_update.tmp
+        mv /state/.do_nightly_update.tmp /state/.do_nightly_update
+      fi
+    fi
+  fi
+}
+
+wait_for_openvpn() {
+  for i in $(seq 16); do
+    vpn_ip=$(ifdata -pa "$vpn_interface" 2>/dev/null) || true
+    if [ -n "$vpn_ip" ]; then
+      logger -t puavo-updates-on-resume -p user.notice 'vpn is up'
+      return 0
+    fi
+    sleep "$i"
+  done
+
+  logger -t puavo-updates-on-resume -p user.err 'vpn connection not active'
+
+  return 1
+}
+
+if [ "$current_hour" -lt "$action_hour" \
+     -o '(' "$current_hour" -eq "$action_hour" \
+            -a "$current_minute" -le "$action_minute" ')' ]; then
+  exit 0
 fi
 
-if [ -e /state/.suspend_if_lid_closed -a "$(lid_state)" = 'closed' ]; then
-  systemctl suspend
+setup_rtcwake || true
+
+if [ -e /state/.suspend_if_lid_closed ]; then
+  # wait until gnome-shell is up (on the login screen)
+  pgrep -c -x gnome-shell > /dev/null || exit 0
+
+  if [ "$(lid_state)" = 'closed' ]; then
+    logger -t puavo-updates-on-resume -p user.notice \
+           'suspending because lid is closed and have pending request'
+    systemctl suspend
+  fi
+  rm -f /state/.suspend_if_lid_closed
+  exit 0
+fi
+
+nightly_update_date="$(cat /state/.do_nightly_update 2>/dev/null)" || true
+if [ -z "$nightly_update_date" ]; then
+  exit 0
+fi
+smaller_date=$(printf "%s\n%s\n" "$nightly_update_date" "$current_date" \
+                 | sort | head -1)
+if [ "$smaller_date" != "$nightly_update_date" ]; then
+  exit 0
+fi
+
+rm -f /state/.do_nightly_update
+
+# allow some time for user to open the lid in case this is a normal resume
+# (the host might also be booted up)
+sleep 10
+
+if [ "$(lid_state)" != 'closed' ]; then
+  logger -t puavo-updates-on-resume -p user.notice \
+         'not doing nightly updates today because the lid state is not closed'
+  exit 0
+fi
+
+logger -t puavo-updates-on-resume -p user.notice \
+       "doing nightly updates on ${action_hour}:${action_minute}"
+
+old_image_inode="$(stat -c %i /images/ltsp.img 2>/dev/null)" || true
+if [ -z "$old_image_inode" ]; then
+  logger -t puavo-updates-on-resume \
+         -p user.err 'could not lookup the current image inode'
+  exit 1
+fi
+
+if on_ac_power; then
+  logger -t puavo-updates-on-resume -p user.notice \
+         'on AC power, waiting for openvpn'
+  if wait_for_openvpn; then
+    puavo-update-client --wait-for-image-update || true
+    if image_is_updated "$old_image_inode"; then
+      logger -t puavo-updates-on-resume -p user.notice \
+             'image updated, rebooting to suspend'
+      touch /state/.suspend_if_lid_closed
+      reboot
+      exit 0
+    else
+      logger -t puavo-updates-on-resume -p user.notice \
+             'no image update, not rebooting'
+    fi
+  fi
+elif battery_capacity_over 30; then
+  logger -t puavo-updates-on-resume -p user.notice \
+         'on enough battery power, updating'
+  if wait_for_openvpn; then
+    puavo-update-client --wait-for-image-update || true
+    if image_is_updated "$old_image_inode"; then
+      logger -t puavo-updates-on-resume -p user.notice \
+             'image updated, powering off'
+      poweroff
+      exit 0
+    else
+      logger -t puavo-updates-on-resume -p user.notice \
+             'no image update, not powering off'
+    fi
+  fi
+else
+  logger -t puavo-updates-on-resume -p user.notice \
+         'not enough battery power, not updating'
+fi
+
+if [ "$(lid_state)" = 'closed' ]; then
+  logger -t puavo-updates-on-resume -p user.notice \
+        'suspending, because lid is closed'
+  if ! systemctl suspend; then
+    touch /state/.suspend_if_lid_closed
+  fi
 fi
