Do not expose "gocryptfs".  We know the new password so no need to ask that from user.

diff --git a/parts/ltsp/client/pam/puavo-manage-homedir b/parts/ltsp/client/pam/puavo-manage-homedir
--- a/parts/ltsp/client/pam/puavo-manage-homedir
+++ b/parts/ltsp/client/pam/puavo-manage-homedir
@@ -45,17 +45,25 @@ create_encrypted_home() {
   logmsg -p user.notice "created an encrypted directory for user ${user_uid}"
 }
 
-setup_tmphome() {
-  local msg tmp_home user_gid user_homedir user_uid
+setup_home_pw_change() {
+  local msg tmp_home user_gid user_homedir user_password user_uid
 
   user_homedir=$1
   user_uid=$2
   user_gid=$3
+  user_password=$4
 
-  rmdir "$user_homedir"                                          || return 1
-  tmp_home=$(mktemp -d /anon/tmphome_${username}.XXXXXX)         || return 1
-  mkdir -p "${tmp_home}/.puavo" "$user_homedir"                  || return 1
-  touch "${tmp_home}/.puavo/change_gocryptfs_password"           || return 1
+  rmdir "$user_homedir"                                  || return 1
+  tmp_home=$(mktemp -d /anon/tmphome_${username}.XXXXXX) || return 1
+  mkdir -p "${tmp_home}/.puavo" "$user_homedir"          || return 1
+
+  # XXX should this password be encrypted at least a bit?
+  # XXX (even though the key should be available somewhere...
+  # XXX it is obfuscation but might be nice anyway so that passwords
+  # XXX are not accidentally read by admins)
+  printf %s "$user_password" \
+    > "${tmp_home}/.puavo/new_gocryptfs_password" || return 1
+
   chown -R "${user_uid}:${user_gid}" "$tmp_home" "$user_homedir" || return 1
   mount --bind "$tmp_home" "$user_homedir"                       || return 1
 
@@ -194,9 +202,10 @@ if [ -d "$gocryptfs_dir" ]; then
     | gocryptfs -allow_other "$gocryptfs_dir" "$user_homedir"; then
       logmsg -p user.err \
              "could not decrypt dir ${gocryptfs_dir} with user password"
-      if ! setup_tmphome "$user_homedir" "$user_uid" "$user_gid"; then
-        logmsg -p user.err 'failed to set up a temporary home'
-        exit 1
+      if ! setup_home_pw_change "$user_homedir" "$user_uid" "$user_gid" \
+                                "$user_password"; then
+          logmsg -p user.err 'failed to set up a temporary home'
+          exit 1
       fi
       exit 0
   fi
