client: apply access control for admin users

diff --git a/parts/ltsp/client/pam/restrict-logins-by-local-config b/parts/ltsp/client/pam/restrict-logins-by-local-config
--- a/parts/ltsp/client/pam/restrict-logins-by-local-config
+++ b/parts/ltsp/client/pam/restrict-logins-by-local-config
@@ -6,15 +6,36 @@ config_path=/state/etc/puavo/local/config.json
 
 allowed_logins() { jq -r .allow_logins_for[] "$config_path"; }
 
+is_admin_user()
+{
+    # No one is admin if reading the admin group name fails.
+    admin_group=$(cat /etc/ltsp/admin_group) || return 1
+
+    getent group "${admin_group}" | cut -d ':' -f4 | tr , '\n' \
+	| grep -x -q "${PAM_USER}"
+}
+
 # config does not exist or is not readable, so do not restrict anyone
 [ ! -r "$config_path" ] && exit 0
+
+# Allow all explicitly listed users, not matter what.
+allowed_logins | fgrep -qx "${PAM_USER}" && exit 0
+
+if is_admin_user; then
+    case $(jq -r .allow_admins "$config_path") in
+	true)
+	    exit 0
+	    ;;
+	*)
+	    echo 'Access denied due to local policy.' >&2
+	    exit 1
+	    ;;
+    esac
+fi
 
 # if configuration contains '*', allow all
 allowed_logins | fgrep -qx '*' && exit 0
 
-# allow this specific user, if match is found in configuration file
-allowed_logins | fgrep -qx "${PAM_USER}" && exit 0
-
 # otherwise, tough luck!
-echo 'User is not allowed in based on locally administered restrictions' >&2
+echo 'Access denied due to local policy.' >&2
 exit 1
