In puavo-run-extra-boot-scripts, do fetch extra_boot_scripts in "--fetch-only"-mode also for the preferred image, because that might be the one the host will boot on the next boot.

diff --git a/rules/extra_boot_scripts/files/puavo-run-extra-boot-scripts b/rules/extra_boot_scripts/files/puavo-run-extra-boot-scripts
--- a/rules/extra_boot_scripts/files/puavo-run-extra-boot-scripts
+++ b/rules/extra_boot_scripts/files/puavo-run-extra-boot-scripts
@@ -24,23 +24,32 @@ lookup_image_server_by_dns() {
 }
 
 generate_possible_ebs_names() {
-  read imagename < /etc/puavo-image/name
+  preferred_image=$1
 
-  echo "$imagename" \
-    | awk '{
-        sub(/\.img$/, "", $1)
+  imagename=$(awk '{ sub(/\.img$/, "", $1); print $1 }' /etc/puavo-image/name)
+  if [ -z "$imagename" ]; then
+    echo 'Could not determine image name from /etc/puavo-image/name' >&2
+    return 1
+  fi
+
+  {
+    echo "$imagename"
+    if [ -n "$preferred_image" -a "$preferred_image" != "$imagename" ]; then
+      echo "$preferred_image"
+    fi
+  } | awk '{
 
         a_count = split($1, a, "-")
         for (i = 1; i <= a_count; i++) {
           for (j = 1; j <= i; j++) {
             printf "%s%s", a[j], (i == j ? "" : "-")
           }
-          print ".ebs"
+          print ""
         }
-      }'
+      }' \
+    | sort -u \
+    | awk '{ print $1 ".ebs" }'
 }
-
-possible_ebs_names=$(generate_possible_ebs_names)
 
 fetch_with_curl() {
   curl_ebs_server=$1
@@ -88,6 +97,8 @@ try_fetching() {
 }
 
 fetch_extra_boot_scripts() {
+  preferred_image=$1
+
   mkdir -p /state/ebs
 
   ebs_server=$(lookup_image_server_by_dns)
@@ -96,14 +107,14 @@ fetch_extra_boot_scripts() {
     return 1
   fi
 
-  for ebs_filename in $possible_ebs_names; do
+  for ebs_filename in $(generate_possible_ebs_names "$preferred_image"); do
     try_fetching "$ebs_server" "$ebs_filename" "/state/ebs/${ebs_filename}" \
       || ebs_status=1
   done
 }
 
 execute_extra_boot_scripts() {
-  for ebs_filename in $possible_ebs_names; do
+  for ebs_filename in $(generate_possible_ebs_names ''); do
     if [ -s "/state/ebs/${ebs_filename}" ]; then
       echo "======= EXECUTING /state/ebs/${ebs_filename}"
       cat "/state/ebs/${ebs_filename}"
@@ -124,14 +135,18 @@ case "$mode" in
     execute_extra_boot_scripts || ebs_status=1
     ;;
   --fetch-and-execute)
-    fetch_extra_boot_scripts   || ebs_status=1
-    execute_extra_boot_scripts || ebs_status=1
+    fetch_extra_boot_scripts '' || ebs_status=1
+    execute_extra_boot_scripts  || ebs_status=1
     ;;
   --fetch-only)
-    fetch_extra_boot_scripts || ebs_status=1
+    preferred_image=$(puavo-conf puavo.image.preferred)
+    fetch_extra_boot_scripts "$preferred_image" || ebs_status=1
     ;;
   *)
-    echo "Unknown mode '$mode'" >&2
+    cat <<EOF >&2
+Unknown mode '$mode'
+Usage: $(basename $0) --execute-only|--fetch-and-execute|--fetch-only
+EOF
     exit 1
     ;;
 esac
