When cleaning up user caches, go through each home directory only once.
The same logic as in homedir cleanup does not work, because
home directories are not actually removed.

diff --git a/rules/homedir_management/files/puavo-cleanup-caches-to-ensure-free-space b/rules/homedir_management/files/puavo-cleanup-caches-to-ensure-free-space
--- a/rules/homedir_management/files/puavo-cleanup-caches-to-ensure-free-space
+++ b/rules/homedir_management/files/puavo-cleanup-caches-to-ensure-free-space
@@ -41,11 +41,12 @@ if [ -n "${PAM_USER:-}" ]; then
 fi
 
 cleanup_caches_under_homedir() {
-  local cache_path user_homedir user_gid user_uid
+  local cache_dir cache_name user_homedir user_gid user_uid
   user_homedir=$1
 
   user_gid=$(stat -c %g "$user_homedir") || return 1
   user_uid=$(stat -c %u "$user_homedir") || return 1
+
   for cache_name in $cache_name_list; do
     if ! printf %s "$cache_name" | grep -qE "$cache_name_regexp"; then
       continue
@@ -60,6 +61,7 @@ cleanup_caches_under_homedir() {
     if [ ! -d "$cache_dir" ]; then
       continue
     fi
+
     if ! setpriv "--reuid=${user_uid}" "--regid=${user_gid}" --init-groups \
       --inh-caps=-all rm -rf -- "$cache_dir"; then
         logmsg -p user.warning "error in removing ${cache_dir}"
@@ -78,10 +80,13 @@ get_freespace_amount() {
   stat -f -c '%S * %a' /home | bc -l
 }
 
-lookup_oldest_file() {
+lookup_homedirs_oldest_first() {
   find /home -maxdepth 1 -mindepth 1 ! -type l \
-    -a ! -name "$save_homedir_exception" -printf '%T@ %p\0' \
-      | sort -nz | grep -zom 1 '.*' | sed 's/[^ ]* //'
+    -a ! -name "$save_homedir_exception" -printf '%T@ %f\0' \
+      | sort -nz | awk '
+                     BEGIN { RS = "\0" }
+                     $2 ~ /^[A-Za-z0-9][A-Za-z0-9_.-]+$/ { print "/home/" $2 }
+                   '
 }
 
 # log warnings about bad cache names (but carry on)
@@ -91,26 +96,19 @@ for cache_name in $cache_name_list; do
   fi
 done
 
-while true; do
+for homedir in $(lookup_homedirs_oldest_first); do
   freespace_amount=$(get_freespace_amount)
   logmsg -p user.info \
          "/home has ${freespace_amount} bytes of free space, expecting ${freespace_min} bytes"
-  if [ "$(get_freespace_amount)" -ge "$freespace_min" ]; then
+  if [ "$freespace_amount" -ge "$freespace_min" ]; then
     logmsg -p user.info '/home has enough free space'
     break
   fi
 
-  oldest_homedir=$(lookup_oldest_file)
-  if [ -z "$oldest_homedir" ]; then
-    logmsg -p user.info \
-           'oldest homedir could not be found, perhaps there are no files under /home?'
-    break
-  fi
-
   logmsg -p user.info \
-         "not enough free space on /home, removing caches from under ${oldest_homedir}: last modified on $(stat -c %y "$oldest_homedir" || true)"
-  if ! cleanup_caches_under_homedir "$oldest_homedir"; then
-    logmsg -p user.err "error cleaning up cache in ${oldest_homedir}"
+         "not enough free space on /home, removing caches from under ${homedir}: last modified on $(stat -c %y "$homedir" || true)"
+  if ! cleanup_caches_under_homedir "$homedir"; then
+    logmsg -p user.err "error cleaning up cache in ${homedir}"
     logmsg -p user.err 'giving up cleaning up caches'
     exit 1
   fi
