A rewrite of puavo-download-usb-factory-images for Abitti 2.

diff --git a/rules/abitti2/files/puavo-download-usb-factory-images b/rules/abitti2/files/puavo-download-usb-factory-images
--- a/rules/abitti2/files/puavo-download-usb-factory-images
+++ b/rules/abitti2/files/puavo-download-usb-factory-images
@@ -2,63 +2,53 @@
 
 set -eu
 
-puavo_usb_factory_dir=~/.puavo/usb-factory
+g_puavo_usb_factory_dir=~/.puavo/usb-factory
+g_abitti2_client_images_dir="${g_puavo_usb_factory_dir}/Abitti2"
+g_custom_images_dir="${g_puavo_usb_factory_dir}/custom"
 
-abitti_koe_images_dir="${puavo_usb_factory_dir}/Abitti-KOE"
-abitti_ktp_images_dir="${puavo_usb_factory_dir}/Abitti-KTP"
-
-abitti_images_dir=${1:-}
-abitti_json_path="${abitti_images_dir}/abitti.json"
+g_abitti2_images_dir=${1:-}
+g_abitti2_json_path="${g_abitti2_images_dir}/abitti.json"
+g_abitti2_server=''
 
 logmsg() {
   logger -s -t puavo-download-usb-factory-images "$@" || true
 }
 
-if [ -z "$abitti_images_dir" ]; then
+if [ -z "$g_abitti2_images_dir" ]; then
   echo "Usage: $(basename "$0") abitti_image_dir" >&2
   exit 1
 fi
 
 do_setup=false
-if [ "$abitti_images_dir" = '--setup' ]; then
-  abitti_images_dir=''
-  lock_directory="$puavo_usb_factory_dir"
+if [ "$g_abitti2_images_dir" = '--setup' ]; then
+  g_abitti2_images_dir=''
+  lock_directory="$g_puavo_usb_factory_dir"
   do_setup=true
 else
-  lock_directory="$abitti_images_dir"
+  lock_directory="$g_abitti2_images_dir"
 fi
 
 if ! $do_setup \
-     && [ "$abitti_images_dir" != "$abitti_koe_images_dir" \
-          -a "$abitti_images_dir" != "$abitti_ktp_images_dir" ]; then
-  logmsg -p user.err "content directory '${abitti_images_dir}' not supported"
+     && [ "$g_abitti2_images_dir" != "$g_abitti2_client_images_dir" ] \
+     && [ "$g_abitti2_images_dir" != "$g_custom_images_dir" ]; then
+  logmsg -p user.err "content directory '${g_abitti2_images_dir}' not supported"
   exit 1
-fi
-
-image_server=$(puavo-conf puavo.image.servers | awk '{ print $1 }')
-if [ -z "$image_server" ]; then
-  if ! topdomain=$(cat /etc/puavo/topdomain 2>/dev/null); then
-    logmsg -p user.err 'could not find image server to download abitti.json'
-    return 1
-  fi
-  image_server="cdn.${topdomain}"
 fi
 
 get_download_status_path()        { printf "%s/DOWNLOAD_STATUS" "$1"; }
 get_latest_abitti_filename_path() { printf "%s/LATEST_IMAGE"    "$1"; }
 
 cleanup() {
-  local download_status_path
+  local cleanup_status download_status_path
 
   cleanup_status=0
-
-  download_status_path=$(get_download_status_path "$abitti_images_dir")
-  if grep 'in progress' "$download_status_path" 2>/dev/null; then
+  download_status_path=$(get_download_status_path "$g_abitti2_images_dir")
+  if grep -q 'in progress' "$download_status_path" 2>&1; then
     echo failed > "$download_status_path"
     cleanup_status=1
   fi
 
-  exit $cleanup_status
+  exit "$cleanup_status"
 }
 
 if ! $do_setup; then
@@ -66,14 +56,15 @@ if ! $do_setup; then
 fi
 
 set_latest_image() {
-  local abitti_version usbimg_filename
+  local abitti_version latest_abitti_filename_path latest_abitti_version_path \
+        usbimg_filename
 
   abitti_version=$1
   usbimg_filename=$2
 
   latest_abitti_filename_path=$(
-    get_latest_abitti_filename_path "$abitti_images_dir")
-  latest_abitti_version_path="${abitti_images_dir}/VERSION"
+    get_latest_abitti_filename_path "$g_abitti2_images_dir")
+  latest_abitti_version_path="${g_abitti2_images_dir}/VERSION"
 
   printf "%s\n" "$usbimg_filename" > "${latest_abitti_filename_path}.tmp" \
     || return 1
@@ -85,208 +76,163 @@ set_latest_image() {
     || return 1
 }
 
-get_abitti_json() {
-  if ! wget -q --ca-certificate=/etc/puavo/certs/rootca.pem \
-            -O "${abitti_json_path}.tmp" \
-            "https://${image_server}/abitti-images/abitti.json"; then
-     rm -f "${abitti_json_path}.tmp"
-     logmsg -p user.err "could not download abitti.json from ${image_server}"
-     return 1
-  fi
-  mv "${abitti_json_path}.tmp" "$abitti_json_path"
+wget_with_certauth()
+{
+   wget --ca-certificate=/etc/puavo-conf/rootca.pem        \
+        --certificate=/etc/puavo/certs/hostorgcabundle.pem \
+        --private-key=/etc/puavo/certs/host.key            \
+        "$@"
 }
 
-get_build_number() {
-  local abitti_image_type abitti_version build_number requested_version
+# this is mostly a duplicate from /usr/local/sbin/puavo-update-abitti2-image
+get_abitti2_catalogue() {
+  local abitti2_json_gpg_tmppath abitti2_json_tmppath abitti2_server \
+        abitti2_sources gnupg_dir url
 
-  requested_version=$1
-  abitti_image_type=$2
+  abitti2_json_gpg_tmppath="${g_abitti2_json_path}.gpg.tmp"
+  abitti2_json_tmppath="${g_abitti2_json_path}.tmp"
+  abitti2_sources=$(puavo-conf puavo.abitti2.image.sources)
 
-  abitti_version="$requested_version"
-  if [ -z "$requested_version" -o "$requested_version" = 'by puavo-conf' ]; then
-    if ! abitti_version=$(puavo-conf "$puavo_conf_key"); then
-      logmsg -p user.err "could not lookup puavo-conf key ${puavo_conf_key}"
-      return 1
+  for url in $abitti2_sources; do
+    if ! wget_with_certauth -q \
+      --output-document "$abitti2_json_gpg_tmppath" "$url"; then
+        error "error fetching ${url}"
+        rm -f "$abitti2_json_gpg_tmppath"
+        continue
     fi
-  fi
 
-  if [ "$abitti_version" = 'latest' ]; then
-    abitti_version=''
-    if [ "$abitti_image_type" = 'ktp' ]; then
-      abitti_version=$(jq -r .ktp.latest "$abitti_json_path" 2>/dev/null) || true
+    abitti2_server=$(dirname "${url#https://}")
+    gnupg_dir="/root/.puavo/gnupg/${abitti2_server}/digabios"
+    if ! gpg --decrypt --homedir "$gnupg_dir" "$abitti2_json_gpg_tmppath" \
+      2>/dev/null > "$abitti2_json_tmppath"; then
+        error "GPG verification failed for ${url}"
+        rm -f "$abitti2_json_gpg_tmppath" "$abitti2_json_tmppath"
+        continue
     fi
-    if [ -z "$abitti_version" -o "$abitti_version" = 'null' ]; then
-      abitti_version=$(jq -r .latest "$abitti_json_path" 2>/dev/null) || true
-    fi
-    if [ -z "$abitti_version" -o "$abitti_version" = 'null' ]; then
-      logmsg -p user.err 'requesting latest but is it not known'
-      return 1
-    fi
-  fi
 
-  build_number=''
+    rm -f "$abitti2_json_gpg_tmppath" || return 1
+    mv "$abitti2_json_tmppath" "$g_abitti2_json_path" || return 1
+    logmsg -p user.info 'downloaded abitti2.json'
+    printf "%s" "${url%/*}" || return 1
+    return 0
+  done
 
-  case "$abitti_version" in
-    abitti-v[0-9]*)
-      build_number="${abitti_version#abitti-v}"
-      ;;
-  esac
-
-  if [ -z "$build_number" ]; then
-    build_number=$(jq -r --arg abitti_version "$abitti_version" \
-                     '.build_numbers[$abitti_version]' \
-                     "$abitti_json_path") || true
-    if [ -z "$build_number" -o "$build_number" = 'null' ]; then
-      if [ "$abitti_image_type" = 'koe' ]; then
-        long_abitti_version="ABITTI${abitti_version}"
-      else
-        long_abitti_version="SERVER${abitti_version}"
-      fi
-      build_number=$(jq -r --arg abitti_version "$long_abitti_version" \
-                       '.build_numbers[$abitti_version]' \
-                       "$abitti_json_path") || true
-      if [ -z "$build_number" -o "$build_number" = 'null' ]; then
-        if printf %s "$abitti_version" | grep -Eqx '[0-9]+'; then
-          build_number="$abitti_version"
-        fi
-      fi
-    fi
-  fi
-
-  if [ -z "$build_number" -o "$build_number" = 'null' ]; then
-    logmsg -p user.err 'could not determine the Abitti build number'
-    return 1
-  fi
-
-  printf %s "$build_number"
+  error 'could not fetch any source in puavo.abitti2.image.sources'
+  return 1
 }
 
-download_abitti() {
-  local abitti_image_path abitti_image_type abitti_zip_name abitti_zip_path \
-        human_abitti_version incoming_dir jq_script \
-        latest_abitti_filename_path latest_image_name puavo_conf_key \
-        usbimg_filename
+download_abitti2() {
+  local calculated_sha256 choice image_iso image_iso_fp image_sha256 \
+        incoming_dir latest_abitti_filename_path latest_image_name   \
+        puavo_conf_key requested_version requested_version_list      \
+        tmp_download_path url_to_download
 
-  abitti_image_type=$1
-  puavo_conf_key=$2
+  puavo_conf_key=$1
 
-  if [ -z "$abitti_images_dir" ]; then
-    echo 'Internal error' >&2
+  requested_version=$(
+    cat "${g_abitti2_images_dir}/REQUESTED_VERSION" 2>/dev/null) || true)
+  if [ -z "$requested_version" ] \
+    || [ "$requested_version" = "by puavo-conf" ]; then
+      if ! requested_version_list=$(puavo-conf "$puavo_conf_key"); then
+        logmsg -p user.err \
+               "could not lookup puavo-conf '${puavo_conf_key}' value"
+        return 1
+      fi
+      # we download on the the first one on the list (in case there are many)
+      requested_version=$(printf %s "$requested_version_list" \
+                            | awk '{ print $1 }')
+  fi
+
+  if ! choice=$(
+    jq -r --arg req "$requested_version" '
+      if .aliases[$req] then .aliases[$req]
+      elif .choices[$req] then $req
+      elif .choices["abitti-candidate-" + $req] then
+        "abitti-candidate-" + $req
+      else error "no such version" end
+    ' "$g_abitti2_json_path"); then
+      logmsg -p user.err "could not find '${requested_version}' in abitti2.json"
+      return 1
+  fi
+
+  if ! choice_version=$(jq -r --arg choice "$choice" '
+                          .choices[$choice].version // error "no version"
+                        ' "$g_abitti2_json_path"); then
+    logmsg -p user.err "no version for '${choice}' in abitti2.json"
     return 1
   fi
 
-  incoming_dir="${abitti_images_dir}/incoming"
-
-  if ! get_abitti_json; then
-    logmsg -p user.err 'error in fetching abitti.json'
+  if ! image_iso=$(jq -r --arg choice "$choice" '
+                     .choices[$choice].image // error "no image"
+                   ' "$g_abitti2_json_path"); then
+    logmsg -p user.err "no image iso for '${choice}' in abitti2.json"
     return 1
   fi
 
-  requested_version=$(cat "${abitti_images_dir}/REQUESTED_VERSION" \
-                        2>/dev/null) || true
-
-  if ! build_number=$(get_build_number "$requested_version" \
-                        "$abitti_image_type"); then
-    logmsg -p user.err 'could not determine Abitti build number'
+  # verify image_iso variable
+  if printf %s "$image_iso" | grep -q /; then
+    logmsg -p user.err 'image iso has "/"-character'
+    return 1
+  fi
+  if ! printf %s "$image_iso" | grep -q '.iso$'; then
+    logmsg -p user.err 'image iso is not *.iso'
     return 1
   fi
 
-  if [ "$abitti_image_type" = 'ktp' ]; then
-    jq_script='.ktp.images[$image_abitti_version].version'
-  else
-    jq_script='.images[$image_abitti_version].version'
-  fi
-
-  human_abitti_version=$(jq -r --arg image_abitti_version \
-      "abitti-v${build_number}" "$jq_script" "$abitti_json_path") || true
-  if [ -z "$human_abitti_version" -o "$human_abitti_version" = 'null' ]; then
-    logmsg -p user.err \
-           "human Abitti version for '${requested_version}' not found"
+  if ! image_sha256=$(jq -r --arg image "$image" '
+                        .images[$image].sha256 // error "no sha256"
+                      ' "$g_abitti2_json_path"); then
+    logmsg -p user.err "no sha256 for '${image}' in abitti2.json"
     return 1
   fi
 
-  usbimg_filename="abitti-v${build_number}-${abitti_image_type}.usbimg"
-
-  latest_abitti_filename_path=$(
-    get_latest_abitti_filename_path "$abitti_images_dir")
+  latest_abitti_filename_path=$(get_latest_abitti_filename_path \
+                                  "$g_abitti2_client_images_dir")
   latest_image_name=$(cat "$latest_abitti_filename_path" 2>/dev/null) || true
   if [ -n "$latest_image_name" ]; then
-    find "$abitti_images_dir" -name '*.usbimg' \
-      -and ! '(' -name "$usbimg_filename" -or -name "$latest_image_name" ')' \
-      -and -atime +60 \
-      -exec rm -f '{}' \;
-  else
-    find "$abitti_images_dir" -name '*.usbimg' \
-      -and ! -name "$usbimg_filename" \
-      -and -atime +60 \
-      -exec rm -f '{}' \;
+    find "$g_abitti2_images_dir" -name '*.iso' \
+      -and ! '(' -name "$image_iso" -or -name "$image_iso" ')' \
+      -exec rm -f {} \;
   fi
 
-  abitti_image_path="${abitti_images_dir}/${usbimg_filename}"
-
-  if [ -e "$abitti_image_path" ]; then
-    set_latest_image "$human_abitti_version" "$usbimg_filename" || return 1
+  image_iso_fp="${g_abitti2_images_dir}/${image_iso}"
+  if [ -e "$image_iso_fp" ]; then
+    set_latest_image "$choice_version" "$image_iso" || return 1
     return 0
   fi
 
-  abitti_zip_name="${abitti_image_type}-${human_abitti_version}.zip"
-  abitti_zip_path="${incoming_dir}/${abitti_zip_name}"
+  incoming_dir="${g_abitti2_client_images_dir}/incoming"
+  mkdir -p "$incoming_dir"
 
-  printf "in progress %s\n" "$human_abitti_version" \
-    > "$(get_download_status_path "$abitti_images_dir")"
+  tmp_download_path="${incoming_dir}/${image_iso}.tmp"
 
-  if [ ! -e "$abitti_zip_path" ]; then
-    mkdir -p "$incoming_dir"
-    if ! wget -q --ca-certificate=/etc/puavo/certs/rootca.pem \
-              -O "${abitti_zip_path}.tmp" \
-              "https://${image_server}/abitti-images/etcher/${abitti_zip_name}"; then
-      logmsg -p user.err "downloading ${abitti_zip_name} failed"
-      return 1
-    fi
-    sha256sum=$(jq -r --arg abitti_image_type    "$abitti_image_type" \
-                      --arg human_abitti_version "$human_abitti_version" '
-                    .etcher[$abitti_image_type][$human_abitti_version].sha256
-                  ' "$abitti_json_path" 2>/dev/null) || true
-    if [ -z "$sha256sum" -o "$sha256sum" = 'null' ]; then
-      logmsg -p user.err "could not get checksum for ${human_abitti_version}"
-      return 1
-    fi
+  printf "in progress %s\n" "$actual_version" \
+    > "$(get_download_status_path "$g_abitti2_images_dir")"
 
-    (
-      cd "$incoming_dir"
-      if ! printf %s "$sha256sum" | awk -v abitti_zip_path="${abitti_zip_path}.tmp" \
-          '{ $2 = abitti_zip_path; print }' | sha256sum --check --status; then
-        logmsg -p user.err \
-               "sha256sum checksum check failed for ${human_abitti_version}"
-        rm -f "${abitti_zip_path}.tmp"
-        return 1
-      else
-        logmsg -p user.info \
-               "sha256sum checksum check OK ${human_abitti_version}"
-      fi
-    ) || return 1
-
-    mv "${abitti_zip_path}.tmp" "$abitti_zip_path" || return 1
-  fi
-
-  rm -rf "${incoming_dir}/${abitti_image_type}-etcher" || return 1
-
-  if ! unzip -d "${incoming_dir}/${abitti_image_type}-etcher" \
-                "$abitti_zip_path"; then
-    logmsg -p user.err "unpacking $abitti_zip_path failed"
+  url_to_download="${g_abitti2_server}/${image_iso}"
+  if ! wget_with_certauth -q -O "$tmp_download_path" "$url_to_download"
+  then
+    logmsg -p user.err "downloading ${url_to_download} failed"
+    rm -f "$tmp_download_path"
     return 1
   fi
 
-  mv "${incoming_dir}/${abitti_image_type}-etcher/ytl/${abitti_image_type}.img" \
-     "$abitti_image_path" || return 1
+  calculated_sha256="$(sha256sum "$tmp_download_path" | awk '{ print $1 }')"
+  if [ "$calculated_sha256" != "$image_sha256" ]; then
+    errmsg="calculated checksum for ${image_iso} does not match"
+    errmsg="${errmsg} the expected checksum, removing ${tmp_download_path}"
+    logmsg -p user.err "$errmsg"
+    rm -f "$tmp_download_path"
+    return 1
+  fi
 
-  set_latest_image "$human_abitti_version" "$usbimg_filename" || return 1
-
+  mv "${tmp_download_path}.tmp" "$image_iso_fp"   || return 1
+  set_latest_image "$choice_version" "$image_iso" || return 1
   rm -rf "$incoming_dir"
 }
 
 write_ui_json() {
-  cat <<'EOF' > "${puavo_usb_factory_dir}/UI.json.tmp"
+  cat <<'EOF' > "${g_puavo_usb_factory_dir}/UI.json.tmp"
 {
   "description": "HUOMIO!  Kun USB-tikku liitetään koneeseen, kaikki siinä oleva sisältö poistetaan!",
   "instructions": "OHJEET\nAseta usb-tikku usb-jakajaan.\nOdota Abitti-tikun valmistumista.\nIrrota valmis tikku.",
@@ -322,11 +268,11 @@ write_ui_json() {
   }
 }
 EOF
-  mv "${puavo_usb_factory_dir}/UI.json.tmp" \
-     "${puavo_usb_factory_dir}/UI.json"
+  mv "${g_puavo_usb_factory_dir}/UI.json.tmp" \
+     "${g_puavo_usb_factory_dir}/UI.json"
 }
 
-mkdir -p "$puavo_usb_factory_dir"
+mkdir -p "$g_puavo_usb_factory_dir"
 
 (
   if ! flock -n 9; then
@@ -334,53 +280,63 @@ mkdir -p "$puavo_usb_factory_dir"
     return 1
   fi
 
-  # in the old days Abitti-KOE was name "Abitti", this may be removed later:
-  if [ ! -d "$abitti_koe_images_dir" \
-         -a -d "${puavo_usb_factory_dir}/Abitti" ]; then
-    mv "${puavo_usb_factory_dir}/Abitti" "$abitti_koe_images_dir"
-  fi
+  # remove old Abitti 1 stuff
+  rm -rf "${g_puavo_usb_factory_dir}/Abitti"     \
+         "${g_puavo_usb_factory_dir}/Abitti-KOE" \
+         "${g_puavo_usb_factory_dir}/Abitti-KTP"
 
   write_ui_json
 
   exitstatus=0
 
-  for this_abitti_dir in "$abitti_koe_images_dir" "$abitti_ktp_images_dir"; do
-    if [ "$this_abitti_dir" = "$abitti_koe_images_dir" ]; then
-      abitti_image_type='koe'
+  for this_dir in "$g_abitti2_images_dir" "$g_custom_images_dir"; do
+    puavo_conf_key=''
+    if [ "$this_abitti_dir" = "$abitti2_images_dir" ]; then
       bg_color='#6392ac'
-      puavo_conf_key='puavo.abitti.version'
+      image_type='abitti2'
+      puavo_conf_key='puavo.abitti2.version'
       ui_png='UI-blue.png'
     else
-      abitti_image_type='ktp'
-      bg_color='#9c62ab'
-      puavo_conf_key='puavo.abitti.ktp.version'
+      bg_color='#5c5c5c'
+      image_type='custom'
       ui_png='UI-purple.png'
     fi
 
-    mkdir -p "$this_abitti_dir"
+    mkdir -p "$this_dir"
 
-    printf "%s\n" "$puavo_conf_key" > "${this_abitti_dir}/PUAVOCONF_KEY.tmp"
-    mv "${this_abitti_dir}/PUAVOCONF_KEY.tmp" \
-       "${this_abitti_dir}/PUAVOCONF_KEY"
+    printf "%s\n" "$puavo_conf_key" > "${this_dir}/PUAVOCONF_KEY.tmp"
+    mv "${this_dir}/PUAVOCONF_KEY.tmp" "${this_dir}/PUAVOCONF_KEY"
 
     if ! cmp "/usr/local/share/puavo-download-usb-factory-images/${ui_png}" \
-             "${this_abitti_dir}/UI.png" >/dev/null 2>&1; then
+             "${this_dir}/UI.png" >/dev/null 2>&1; then
       cp -p "/usr/local/share/puavo-download-usb-factory-images/${ui_png}" \
-            "${this_abitti_dir}/UI.png"
+            "${this_dir}/UI.png"
     fi
 
-    printf "%s\n" "$bg_color" > "${this_abitti_dir}/UI.png.bg_color.tmp"
-    mv "${this_abitti_dir}/UI.png.bg_color.tmp" \
-       "${this_abitti_dir}/UI.png.bg_color"
+    printf "%s\n" "$bg_color" > "${this_dir}/UI.png.bg_color.tmp"
+    mv "${this_dir}/UI.png.bg_color.tmp" "${this_dir}/UI.png.bg_color"
 
-    if $do_setup || [ "$this_abitti_dir" != "$abitti_images_dir" ]; then
+    if $do_setup || [ "$this_dir" != "$g_abitti2_images_dir" ]; then
       continue
     fi
 
-    download_status_path=$(get_download_status_path "$abitti_images_dir")
+    download_status_path=$(get_download_status_path "$g_abitti2_images_dir")
+
+    if [ "$image_type" = 'custom' ]; then
+       echo up-to-date > "$download_status_path"
+       continue
+    fi
+
     printf "in progress %s\n" ? > "$download_status_path"
-    if ! download_abitti "$abitti_image_type" "$puavo_conf_key"; then
-      logmsg -p user.err "error downloading Abitti to ${abitti_images_dir}"
+
+    if ! g_abitti2_server=$(get_abitti2_catalogue) \
+      || [ -z "$g_abitti2_server" ]; then
+        logmsg -p user.err "error in fetching abitti2.json"
+        return 1
+    fi
+
+    if ! download_abitti2 "$puavo_conf_key"; then
+      logmsg -p user.err "error downloading Abitti to ${g_abitti2_images_dir}"
       echo failed > "$download_status_path"
       exitstatus=1
     else
