Fix for dig-handling in puavo-resolve-api-server (dig can indeed return error codes), also make wirelessaccesspoints behave like laptops.

diff --git a/parts/client/bin/puavo-resolve-api-server b/parts/client/bin/puavo-resolve-api-server
--- a/parts/client/bin/puavo-resolve-api-server
+++ b/parts/client/bin/puavo-resolve-api-server
@@ -18,20 +18,32 @@ set -eu
 
 puavo_domain=$(cat /etc/puavo/domain)
 
-dig_res=$(dig +time=2 +tries=1 SRV _puavo-api._tcp.${puavo_domain} +search +short)
+lookup_puavoapi() {
+  dig +time=2 +tries=1 SRV _puavo-api._tcp.${puavo_domain} +search +short
+}
 
-# dig does not exit with nonzero exit status even if the search fails. it will
-# just give an empty response
-if [ "$dig_res" != "" ]; then
-    echo $dig_res | awk '{ sub(/\.$/, ""); printf "https://%s:%s\n", $4, $3 }'
+if dig_res=$(lookup_puavoapi); then
+    # dig might not exit with nonzero exit status even if the search fails,
+    # instead it will just give an empty response.
+    if [ -n "$dig_res" ]; then
+        echo $dig_res | awk '{
+                          sub(/\.$/, "")
+                          printf "https://%s:%s\n", $4, $3
+                        }'
+        exit 0
+    fi
+fi
+
+puavo_hosttype=$(cat /etc/puavo/hosttype)
+
+# Fallback for laptops and wirelessaccesspoints that are not in the school
+# network.
+if [    "$puavo_hosttype" = "laptop"              \
+     -o "$puavo_hosttype" = "wirelessaccesspoint" \
+     -o "$option"         = "--cloud-fallback" ]; then
+    echo "https://$puavo_domain"
     exit 0
 fi
 
-# Fallback for laptops that are not in the school network
-if [ "$(cat /etc/puavo/hosttype)" = "laptop" -o "$option" = "--cloud-fallback" ]; then
-    echo -n "https://$puavo_domain"
-    exit 0
-fi
-
-echo "Failed to resolve api server" 1>&2
+echo "Failed to resolve api server" >&2
 exit 1
