Add checksum check and cleanup old Abitti usb images in puavo-download-abitti-usb-stick-images.

diff --git a/rules/abitti/files/puavo-download-abitti-usb-stick-images b/rules/abitti/files/puavo-download-abitti-usb-stick-images
--- a/rules/abitti/files/puavo-download-abitti-usb-stick-images
+++ b/rules/abitti/files/puavo-download-abitti-usb-stick-images
@@ -1,7 +1,5 @@
 #!/bin/sh
 
-# copies code from /opinsys-os/.aux/update-abitti-image
-
 set -eu
 
 puavo_usb_factory_dir=~/.puavo/usb-factory
@@ -13,34 +11,52 @@ abitti_version_path="${abitti_images_dir}/VERSION"
 download_status_path="${abitti_images_dir}/DOWNLOAD_STATUS"
 
 cleanup() {
-  if grep 'in progress' "$download_status_path"; then
+  if grep 'in progress' "$download_status_path" 2>/dev/null; then
     echo failed > "$download_status_path"
   fi
 }
 
 trap cleanup 0 INT TERM
 
-download_abitti() {
-  # XXX find remove old abitti images?
+logmsg() {
+  logger -s -t puavo-download-abitti-usb-stick-images "$@" || true
+}
 
+download_abitti() {
   abitti_version=$(puavo-conf puavo.abitti.version)
 
   if [ "$abitti_version" = 'latest' ]; then
     abitti_version=$(
-      wget -q -O - http://static.abitti.fi/usbimg/prod/latest.txt 2>/dev/null)
+      wget -q -O - http://static.abitti.fi/usbimg/prod/latest.txt 2>/dev/null) \
+        || true
   else
     abitti_version=${abitti_version#abitti-v}
   fi
 
   if [ -z "$abitti_version" ]; then
-    echo 'Could not lookup determine abitti version to use' >&2
+    logmsg -p user.err 'could not lookup determine abitti version to use'
     return 1
+  fi
+
+  current_version=$(cat "${abitti_images_dir}/VERSION" 2>/dev/null) || true
+  if [ -n "$current_version" ]; then
+    find "$abitti_images_dir" -name '*.usbimg' \
+      -and ! '(' -name "abitti-v${abitti_version}.usbimg" \
+                 -or -name "abitti-v${current_version}.usbimg" ')' \
+      -and -atime +60 \
+      -exec rm -f '{}' \;
+  else
+    find "$abitti_images_dir" -name '*.usbimg' \
+      -and ! -name "abitti-v${abitti_version}.usbimg" \
+      -and -atime +60 \
+      -exec rm -f '{}' \;
   fi
 
   abitti_image_path="${abitti_images_dir}/abitti-v${abitti_version}.usbimg"
 
   if [ -e "$abitti_image_path" ]; then
-    echo "$abitti_version" > "$abitti_version_path" || return 1
+    echo "$abitti_version" > "${abitti_version_path}.tmp"  || return 1
+    mv "${abitti_version_path}.tmp" "$abitti_version_path" || return 1
     return 0
   fi
 
@@ -49,32 +65,51 @@ download_abitti() {
   if [ ! -e "$koe_zip_path" ]; then
     if ! wget -O "${koe_zip_path}.tmp" \
               "http://static.abitti.fi/usbimg/prod/${abitti_version}/koe.zip"; then
-      echo "Downloading ${koe_zip_path} failed" >&2
+      logmsg -p user.err "downloading ${koe_zip_path} failed"
       return 1
     fi
-    # XXX md5sum check?
+    if ! md5sum=$(wget -q -O - http://static.abitti.fi/usbimg/prod/${abitti_version}/koe.zip.md5); then
+      logmsg -p user.err "could not get checksum for ${abitti_version}"
+      return 1
+    fi
+
+    (
+      cd "$incoming_dir"
+      if ! echo "$md5sum" | awk -v koe_zip_path="${koe_zip_path}.tmp" \
+          '{ $2 = koe_zip_path; print }' | md5sum --check --status; then
+        logmsg -p user.err "md5sum checksum check failed for $abitti_version"
+        return 1
+      else
+        logmsg -p user.info "md5sum checksum check OK $abitti_version"
+      fi
+    ) || return 1
+
     mv "${koe_zip_path}.tmp" "$koe_zip_path" || return 1
   fi
 
   rm -rf "${incoming_dir}/koe-etcher" || return 1
 
   if ! unzip -d "${incoming_dir}/koe-etcher" "$koe_zip_path"; then
-    echo "Unpacking $koe_zip_path failed" >&2
+    logmsg -p user.err "unpacking $koe_zip_path failed"
     return 1
   fi
 
   mv "${incoming_dir}/koe-etcher/koe.dd" "$abitti_image_path" \
     || return 1
 
-  echo "$abitti_version" > "$abitti_version_path" || return 1
+  echo "$abitti_version" > "${abitti_version_path}.tmp"  || return 1
+  mv "${abitti_version_path}.tmp" "$abitti_version_path" || return 1
+
+  rm -rf "$incoming_dir"
 }
+
+mkdir -p "$abitti_images_dir" "$incoming_dir"
 
 (
   if ! flock -n 9; then
+    logmsg -p user.err 'could not get a lock, exiting...'
     return 1
   fi
-
-  mkdir -p "$abitti_images_dir" "$incoming_dir"
 
   exitstatus=0
 
@@ -86,10 +121,8 @@ download_abitti() {
     echo ok > "$download_status_path"
   fi
 
-  rm -rf "$incoming_dir"
-
   if [ "$exitstatus" -ne 0 ]; then
-    echo 'Error downloading latest version of Abitti' >&2
+    logmsg -p user.err 'error downloading latest version of Abitti'
     exit $exitstatus
   fi
 
