Make is-encrypted-install more robust in catching errors on lsblk and jq calls.
Using /bin/bash and "set -o pipefail" could be easier, but I
prefer to do it this way.

Also, do keep/add a newline to the result output.  In Unix,
lines end with a newline and it is caller's responsibility to
deal with it.

diff --git a/parts/ltsp/puavo-install/lib/is-encrypted-install b/parts/ltsp/puavo-install/lib/is-encrypted-install
--- a/parts/ltsp/puavo-install/lib/is-encrypted-install
+++ b/parts/ltsp/puavo-install/lib/is-encrypted-install
@@ -16,13 +16,25 @@ if [ ! -d "$images_dir" ]; then
 fi
 
 # Attempt to find a LUKS partition that has the images directory as mountpoint
-lsblk -J -O | jq --raw-output --arg images_dir "$images_dir" '
-  [
-    .blockdevices[]
-      | select(.type == "disk")
-      | .children[]
-      | select(.fstype == "crypto_LUKS")
-      | .children[]?
-      | .mountpoints[]?
-  ] | any(. == $images_dir)
-' | tr --delete '\n'
+if ! lsblk_output=$(lsblk -J -O); then
+  echo 'lsblk error' >&2
+  exit 1
+fi
+
+if ! jq_output=$(
+  printf %s "$lsblk_output" \
+    | jq --raw-output --arg images_dir "$images_dir" '
+        [
+          .blockdevices[]
+            | select(.type == "disk")
+            | .children[]
+            | select(.fstype == "crypto_LUKS")
+            | .children[]?
+            | .mountpoints[]?
+        ] | any(. == $images_dir)
+      '); then
+  echo 'jq error' >&2
+  exit 1
+fi
+
+printf "%s\n" "$jq_output"
