puavo-boot: Treat EFI mount error as internal error

diff --git a/parts/ltsp/puavo-install/lib/is-uki-install b/parts/ltsp/puavo-install/lib/is-uki-install
--- a/parts/ltsp/puavo-install/lib/is-uki-install
+++ b/parts/ltsp/puavo-install/lib/is-uki-install
@@ -15,17 +15,6 @@ find_efi_device_path() {
     | awk '$2 == "c12a7328-f81f-11d2-ba4b-00a0c93ec93b" { print $1; exit(0) }'
 }
 
-mount_disk_efi_partition() {
-  local diskdev="$1"
-
-  efi_devpath=$(find_efi_device_path "$diskdev")
-  if [ -z "$efi_devpath" ]; then
-    return 1
-  fi
-
-  mount "$efi_devpath" /boot/efi >/dev/null
-}
-
 cleanup() {
   umount /boot/efi 2>/dev/null || true
 }
@@ -53,8 +42,16 @@ for diskdev in $boot_disks; do
   # Check if the disk contains UKI installation
   is_uki_disk=0
 
-  # XXX what if $diskdev has an EFI partition but mounting it fails?
-  if mount_disk_efi_partition "$diskdev"; then
+  # Find and mount the EFI partition of the current disk device.
+  # UKI installation requires the existence of EFI partition.
+  efi_device_path=$(find_efi_device_path "$diskdev")
+
+  if [ -n "$efi_device_path" ]; then
+    if ! mount "$efi_device_path" /boot/efi >/dev/null 2>&1; then
+        echo "error: failed to mount EFI partition of device ${diskdev}" >&2
+        exit 1
+    fi
+
     if [ -d "$UKI_ROOT" ]; then
       is_uki_disk=1
     fi
