Attempt to be more consistent with error logging

diff --git a/parts/ltsp/puavo-install/lib/is-uki-install b/parts/ltsp/puavo-install/lib/is-uki-install
--- a/parts/ltsp/puavo-install/lib/is-uki-install
+++ b/parts/ltsp/puavo-install/lib/is-uki-install
@@ -21,7 +21,7 @@ mount_disk_efi_partition() {
 
   efi_devpath=$(find_efi_device_path "$diskdev")
   if [ -z "$efi_devpath" ]; then
-    echo "Failed to find EFI partition in ${diskdev}" >&2
+    echo "error: failed to find EFI partition in ${diskdev}" >&2
     return 1
   fi
 
@@ -38,14 +38,14 @@ trap cleanup EXIT
 images_dir=$1
 
 if ! mountpoint -q "$images_dir"; then
-  echo "'${images_dir}' is not mounted" >&2
+  echo "error: '${images_dir}' is not mounted" >&2
   exit 1
 fi
 
 boot_disks=$("$PUAVO_INSTALL_LIBDIR"/puavo-get-boot-disks "$images_dir")
 
 if [ -z "$boot_disks" ]; then
-  echo "Failed to find boot disks" >&2
+  echo "error: failed to find boot disks" >&2
   exit 1
 fi
 
@@ -67,7 +67,7 @@ for diskdev in $boot_disks; do
   if [ -z "$is_uki_install" ]; then
     is_uki_install="$is_uki_disk"
   elif [ "$is_uki_install" != "$is_uki_disk" ]; then
-    echo "Inconsistent UKI installation state detected on $diskdev" >&2
+    echo "error: inconsistent UKI installation state detected on $diskdev" >&2
     exit 1
   fi
 done
diff --git a/parts/ltsp/puavo-install/puavo-install-grub b/parts/ltsp/puavo-install/puavo-install-grub
--- a/parts/ltsp/puavo-install/puavo-install-grub
+++ b/parts/ltsp/puavo-install/puavo-install-grub
@@ -729,15 +729,15 @@ install_legacy_grub() {
 }
 
 copy_grub_environment() {
-    # Scripts such as "setup_grub_environment" write the
-    # environment variables into /images/boot/grub/grubenv.
-    # Here we sync this file to the boot directory (EFI partition most likely).
-    if [ ! -f /images/boot/grub/grubenv ]; then
-        # Grub will create the default environment in the EFI partition
-        return 0
-    fi
+  # Scripts such as "setup_grub_environment" write the
+  # environment variables into /images/boot/grub/grubenv.
+  # Here we sync this file to the boot directory (EFI partition most likely).
+  if [ ! -f /images/boot/grub/grubenv ]; then
+    # Grub will create the default environment in the EFI partition
+    return 0
+  fi
 
-    cp /images/boot/grub/grubenv "${boot_dir}/grub/grubenv" || return 1
+  cp /images/boot/grub/grubenv "${boot_dir}/grub/grubenv" || return 1
 }
 
 write_grub_version() {
@@ -784,7 +784,7 @@ install_efi_grub() {
     install_puavo_grub_files_to_efi_partition "$boot_dir" && \
     copy_grub_environment && \
     write_grub_version "${boot_dir}/grub/version" || {
-      echo "failed to install UKI files to EFI partition" >&2
+      log err "failed to install UKI files to EFI partition"
       umount /boot/efi || true
       return 1
     }
@@ -902,7 +902,7 @@ case "$diskdev" in
   /dev/md*)
     grub_target_devices=$(find_grub_target_devices_on_raid "$diskdev")
     if [ -z "$grub_target_devices" ]; then
-      log err 'could not find grub target devices on RAID configuration'
+      log err 'could not find Grub target devices on RAID configuration'
       exit 1
     fi
     ;;
@@ -974,7 +974,7 @@ install_puavo_grub_files_to_efi_partition() {
   boot_dir=$1
 
   cp -r /boot/grub "$boot_dir" || (
-    log err 'failed to copy grub files to boot directory $boot_dir'
+    log err "failed to copy Grub files to boot directory ${boot_dir}"
     return 1
   )
 }
@@ -1002,11 +1002,11 @@ else
   # because we'll install the GRUB boot files on EFI partition
   if [ "${UKI_MODE:-}" = "1" ]; then
     for grubdev in $grub_target_devices; do
-      log info "installing grub to ${grubdev}"
+      log info "installing Grub to ${grubdev}"
 
       efi_devpath=$(get_efi_devpath "$grubdev")
       if [ -z "$efi_devpath" ]; then
-        log err "failed to find EFI partition path for GRUB device"
+        log err "failed to find EFI partition path for Grub device"
         exit 1
       fi
 
@@ -1018,7 +1018,7 @@ else
     done
   else
     for grubdev in $grub_target_devices; do
-      log info "installing grub to ${grubdev}"
+      log info "installing Grub to ${grubdev}"
 
       grub_install_attempted=false
 
@@ -1113,7 +1113,7 @@ install_grub_configuration() {
     mv "$tmp_grub_cfg_path" "$grub_cfg_path"
     log notice 'new Grub configuration has been installed'
     if ! flush_caches; then
-      log warn 'error in flushing caches after updating grub configuration'
+      log warn 'error in flushing caches after updating Grub configuration'
     fi
   fi
 
@@ -1128,7 +1128,7 @@ if [ "${UKI_MODE:-}" = "1" ]; then
 
     efi_devpath=$(get_efi_devpath "$grubdev")
     if [ -z "$efi_devpath" ]; then
-      log err "failed to find EFI partition path for GRUB device"
+      log err "failed to find EFI partition path for Grub device"
       exit 1
     fi
 
diff --git a/parts/ltsp/puavo-install/puavo-install-uki b/parts/ltsp/puavo-install/puavo-install-uki
--- a/parts/ltsp/puavo-install/puavo-install-uki
+++ b/parts/ltsp/puavo-install/puavo-install-uki
@@ -12,12 +12,12 @@ image_mountpoint="$1"
 uki_root="$2"
 
 if [ ! -d "$image_mountpoint" ]; then
-  echo "Image mountpoint '$image_mountpoint' does not exist" >&2
+  echo "error: image mountpoint '$image_mountpoint' does not exist" >&2
   exit 1
 fi
 
 if [ ! -d "$uki_root" ]; then
-  echo "UKI root '$uki_root' does not exist" >&2
+  echo "error: UKI root '$uki_root' does not exist" >&2
   exit 1
 fi
 
@@ -25,13 +25,13 @@ cleanup_temporary_files() {
   find "$uki_root" -type f -name '*.tmp' -delete
 }
 
-cleanup_temporary_files || echo "Warning: Failed to remove temporary files" >&2
+cleanup_temporary_files || echo "warning: failed to remove temporary files" >&2
 trap 'cleanup_temporary_files' INT TERM EXIT
 
 boot_directory="${image_mountpoint}/boot"
 
 if [ ! -d "$boot_directory" ]; then
-  echo "Boot directory '$boot_directory' does not exist" >&2
+  echo "error: root directory '$boot_directory' does not exist" >&2
   exit 1
 fi
 
@@ -43,7 +43,7 @@ install_boot_entry_config() {
   local release_file="${image_mountpoint}/etc/puavo-image/release"
 
   if [ ! -r "$class_file" ] || [ ! -r "$release_file" ]; then
-    echo "Missing boot entry information in image mountpoint" >&2
+    echo "error: missing boot entry information in image mountpoint" >&2
     return 1
   fi
 
@@ -53,13 +53,13 @@ install_boot_entry_config() {
   label="PuavoOS (${release})" # Todo: Decide how we generate the labels
 
   [ -f "$environment_file" ] || grub-editenv "$environment_file" create || {
-    echo "Failed to create the GRUB environment of a boot entry" >&2
+    echo "error: failed to create the GRUB environment of a boot entry" >&2
     return 1
   }
 
   (grub-editenv "$environment_file" set "label=${label}" &&
     grub-editenv "$environment_file" set "class=${class}") || {
-    echo "Failed to write the GRUB environment of a boot entry" >&2
+    echo "error: failed to write the GRUB environment of a boot entry" >&2
     return 1
   }
 }
@@ -75,7 +75,7 @@ install_uki() {
     # from being used and it will be cleaned later
     if ! cp "$uki" "$uki_temporary_destination" || \
        ! mv "$uki_temporary_destination" "$uki_destination"; then
-      echo "Failed to copy UKI to EFI partition" >&2
+      echo "error: failed to copy UKI to EFI partition" >&2
       return 1
     fi
   else
@@ -84,7 +84,7 @@ install_uki() {
 
   local extra_directory="${uki_destination}.extra.d"
   if ! mkdir -p "$extra_directory"; then
-    echo "Failed to create the extra directory for UKI in EFI partition" >&2
+    echo "error: failed to create the extra directory for UKI in EFI partition" >&2
     return 1
   fi
 
diff --git a/parts/ltsp/puavo-install/puavo-uninstall-uki-image b/parts/ltsp/puavo-install/puavo-uninstall-uki-image
--- a/parts/ltsp/puavo-install/puavo-uninstall-uki-image
+++ b/parts/ltsp/puavo-install/puavo-uninstall-uki-image
@@ -12,7 +12,7 @@ install_image="$1"
 install_mountpoint="$2"
 
 if [ ! -f "$install_image" ]; then
-  echo "Install image '$install_image' does not exist" >&2
+  echo "error: install image '$install_image' does not exist" >&2
   exit 1
 fi
 
@@ -30,7 +30,7 @@ mount -o ro "$install_image" "$image_mountpoint"
 
 boot_directory="${image_mountpoint}/boot"
 if [ ! -d "$boot_directory" ]; then
-  echo "Boot directory '$boot_directory' does not exist in image" >&2
+  echo "error: boot directory '$boot_directory' does not exist in image" >&2
   exit 1
 fi
 
@@ -42,7 +42,8 @@ if [ -z "$uki_files" ]; then
 fi
 
 # Identify boot disks and remove UKI files from their EFI partitions
-boot_disks=$(/usr/lib/puavo-ltsp-install/puavo-get-boot-disks "$install_mountpoint")
+PUAVO_INSTALL_LIBDIR="/usr/lib/puavo-ltsp-install"
+boot_disks=$("$PUAVO_INSTALL_LIBDIR"/puavo-get-boot-disks "$install_mountpoint")
 
 for diskdev in $boot_disks; do
   efi_devpath=$(lsblk -n -l -o PATH,PARTTYPE "$diskdev" \
diff --git a/parts/ltsp/puavo-install/puavo-update-boot-disks b/parts/ltsp/puavo-install/puavo-update-boot-disks
--- a/parts/ltsp/puavo-install/puavo-update-boot-disks
+++ b/parts/ltsp/puavo-install/puavo-update-boot-disks
@@ -45,13 +45,13 @@ if [ -z "$image_path" ]; then
   image_path=$(find_default_image "$images_dir")
 
   if [ -z "$image_path" ]; then
-    echo "Failed to find the default image in ${images_dir}" >&2
+    echo "error: failed to find the default image in ${images_dir}" >&2
     exit 1
   fi
 fi
 
 if [ ! -f "$image_path" ]; then
-  echo "Image '$image_path' does not exist" >&2
+  echo "error: image '$image_path' does not exist" >&2
   exit 1
 fi
 
