Write reset_override in puavo-reset-laptop-to-factory-defaults, so we can send information on the latest reset to puavo even in the case it was manually triggered.

diff --git a/parts/ltsp/puavo-install/lib/puavo-reset b/parts/ltsp/puavo-install/lib/puavo-reset
--- a/parts/ltsp/puavo-install/lib/puavo-reset
+++ b/parts/ltsp/puavo-install/lib/puavo-reset
@@ -20,7 +20,6 @@ fi
 get_key() { printf "%s\n" "$reset_state" | jq -r --arg key "$1" '.[$key]'; }
 
 from=$(        get_key from)
-id=$(          get_key id)
 mode=$(        get_key mode)
 operation=$(   get_key operation)
 pin=$(         get_key pin)
@@ -38,10 +37,9 @@ User home directories will be wiped out
 and system will be returned to factory defaults.
 
 Detailed request information:
-  user account          $from
-  id                    $id
-  operation             $operation
-  request time          $request_time_for_tz
+  user account    $from
+  operation       $operation
+  request time    $request_time_for_tz
 
 EOF
 }
@@ -76,10 +74,10 @@ esac
 
 case "$operation" in
   fast-reset)
-    puavo-reset-laptop-to-factory-defaults --force --no-reboot
+    prltfd_args='--force'
     ;;
   reset)
-    puavo-reset-laptop-to-factory-defaults --force --no-reboot --secure-delete
+    prltfd_args='--force --secure-delete'
     ;;
   *)
     echo "Unknown operation: '${operation}'" >&2
@@ -87,22 +85,8 @@ case "$operation" in
     ;;
 esac
 
-current_time=$(date -Iseconds)
-printf "%s\n" "$reset_state" \
-  | jq --arg current_time "$current_time" '
-      .["request-fulfilled"] = $current_time
-    ' \
-  > "${reset_override_path}.tmp"
-mv "${reset_override_path}.tmp" "$reset_override_path"
-
-# puavo-reset-laptop-to-factory-defaults has duplicate code
-i=5
-echo -n "rebooting in $i seconds..."
-while [ "$i" -gt 0 ]; do
-  i=$(($i - 1))
-  sleep 1
-  echo -n " $i"
-done
-echo .
-
-reboot
+if ! puavo-reset-laptop-to-factory-defaults $prltfd_args; then
+  echo 'DEVICE RESET FAILED, press ENTER to reboot.' >&2
+  read answer
+  reboot
+fi
diff --git a/parts/ltsp/puavo-install/puavo-reset-laptop-to-factory-defaults b/parts/ltsp/puavo-install/puavo-reset-laptop-to-factory-defaults
--- a/parts/ltsp/puavo-install/puavo-reset-laptop-to-factory-defaults
+++ b/parts/ltsp/puavo-install/puavo-reset-laptop-to-factory-defaults
@@ -3,7 +3,6 @@
 set -eu
 
 request_confirmation=true
-do_reboot=true
 use_secure_delete=false
 
 destroy_in_dir() {
@@ -31,13 +30,40 @@ destroy_in_dir() {
 
 usage() {
   cat <<EOF
-$(basename $0) [--force] [--no-reboot] [--secure-delete]
+$(basename $0) [--force] [--secure-delete]
 
   --force               no questions asked
-  --no-reboot           no rebooting after operation is done
   --secure-delete       overwrite files before unlinking them (slow!)
 EOF
   exit 1
+}
+
+write_reset_override() {
+  local current_time operation reset_override_path user
+
+  operation=$1
+
+  reset_override_path='/state/etc/puavo/reset_override'
+
+  current_time=$(date -Iseconds) || return 1
+  user="${SUDO_USER:-}"
+  if [ -z "$user" ]; then user="${USER:-}"; fi
+  if [ -z "$user" ]; then user='?'        ; fi
+
+  jq -r --arg current_time "$current_time" \
+        --arg operation    "$operation"    \
+        --arg user         "$user" '
+    if (.|has("reset")) and (.reset|type == "object") then
+      .reset
+    else
+      {
+        "from":         $user,
+        "operation":    $operation,
+        "request-time": $current_time,
+      }
+    end | .["request-fulfilled"] = $current_time
+  ' /state/etc/puavo/device.json > "${reset_override_path}.tmp" || return 1
+  mv "${reset_override_path}.tmp" "$reset_override_path" || return 1
 }
 
 wrap_msg() {
@@ -68,7 +94,7 @@ if [ "$puavo_hosttype" != "laptop" ]; then
   exit 1
 fi
 
-if ! args=$(getopt -n "$0" -o + -l 'force,no-reboot,secure-delete' -- "$@"); then
+if ! args=$(getopt -n "$0" -o + -l 'force,secure-delete' -- "$@"); then
   usage
 fi
 
@@ -76,7 +102,6 @@ eval "set -- $args"
 while [ $# -ne 0 ]; do
   case "$1" in
     --force)         request_confirmation=false; shift ;;
-    --no-reboot)     do_reboot=false           ; shift ;;
     --secure-delete) use_secure_delete=true    ; shift ;;
     --) shift; break ;;
     *)  usage ;;
@@ -84,6 +109,12 @@ while [ $# -ne 0 ]; do
 done
 
 [ $# -eq 0 ] || usage
+
+if $use_secure_delete; then
+  operation='reset'
+else
+  operation='fast-reset'
+fi
 
 while $request_confirmation; do
   cat <<'EOF'
@@ -144,16 +175,18 @@ destroy_in_dir /imageoverlays/ 'Cleaning up /imageoverlays'
 destroy_in_dir /state/etc/NetworkManager/system-connections/ \
                'Removing network manager connections'
 
-if $do_reboot; then
-  # puavo-reset has duplicated code
-  i=5
-  echo -n "rebooting in $i seconds..."
-  while [ "$i" -gt 0 ]; do
-    i=$(($i - 1))
-    sleep 1
-    echo -n " $i"
-  done
-  echo .
-
-  reboot
+if ! write_reset_override "$operation"; then
+  echo 'error in writing reset override' >&2
+  exit 1
 fi
+
+i=5
+echo -n "rebooting in $i seconds..."
+while [ "$i" -gt 0 ]; do
+  i=$(($i - 1))
+  sleep 1
+  echo -n " $i"
+done
+echo .
+
+reboot
