Some further work in puavo-configure-chroot and puavo-configure-image.

diff --git a/parts/rules/rules/puavo-configure-image b/parts/rules/rules/puavo-configure-image
--- a/parts/rules/rules/puavo-configure-image
+++ b/parts/rules/rules/puavo-configure-image
@@ -16,9 +16,9 @@ apply_debseeds() {
 
 apply_puppet_rules() {
   error_on_change=$1
-  puppet_classes=$2
+  buildrule_args=$2
   
-  puppet_classes=$(get_and_cache_puppet_classes "$puppet_classes")
+  puppet_classes=$(get_and_cache_puppet_classes "$buildrule_args")
 
   if [ "$error_on_change" = "true" ]; then
     another_ok_puppetcode=0
@@ -38,19 +38,70 @@ apply_puppet_rules() {
 
 do_apply_buildrules() {
   error_on_change=$1
-  puppet_classes=$2
+  buildrule_args=$2
 
   apply_debseeds
-  apply_puppet_rules "$error_on_change" "$puppet_classes"
+  apply_puppet_rules "$error_on_change" "$buildrule_args"
+}
+
+do_apt_dist_upgrade() {
+  do_apt_update
+  apt-get -y -o Dpkg::Options::="--force-confold" dist-upgrade
+  apt-get -y clean # to preserve space
+}
+
+do_apt_update() {
+  apt-get -y update
 }
 
 do_bootstrap() {
-  imagetype=$1
+  apt_proxy=$1
+  distribution=$2
+  imagetype=$3
+  mirror=$4
 
   if [ -z "$imagetype" ]; then
     echo 'Imagetype is not set' >&2
     usage
   fi
+
+  if [ -n "$apt_proxy" ]; then
+    if [ -z "$distribution" ]; then
+      echo 'Distribution is not' >&2
+      usage
+    fi
+    if [ -z "$mirror" ]; then
+      echo 'Mirror is not set' >&2
+      usage
+    fi
+
+    cat <<EOF > /etc/apt/apt.conf.d/00imagebuild-proxy
+acquire::http::proxy "http://$apt_proxy";
+EOF
+    # url in sources.list may be with proxy-prefix, so now clean this up:
+    cat <<EOF > /etc/apt/sources.list
+deb http://${mirror}/ubuntu $distribution main restricted universe multiverse
+EOF
+  fi
+
+  cat <<'EOF' > /usr/sbin/policy-rc.d
+#!/bin/sh
+[ "$DISABLE_DAEMONS" != "" ] && exit 101
+EOF
+  chmod 755 /usr/sbin/policy-rc.d
+
+  apt-get update
+  apt-get -y install linux-image-generic
+
+  (
+    cd /boot
+    for vmlinuz in vmlinuz-*; do
+      test -e "$vmlinuz" || break
+      kernel_version=${vmlinuz##vmlinuz-}
+      ln -s "vmlinuz-$kernel_version"    vmlinuz
+      ln -s "initrd.img-$kernel_version" initrd.img
+    done
+  )
 
   mkdir -p /etc/ltsp /etc/puavo-image-build/rules
   apt-get -qq -y install language-pack-en puppet-common
@@ -62,6 +113,78 @@ do_cleanup_buildrules() {
   rm -rf /etc/puavo-image-build/rules/*
 }
 
+do_install_packages() {
+  # use gdebi instead of dpkg, dpkg is dumb with dependencies
+  apt-get -y install gdebi-core
+  gdebi -n /var/tmp/puavo-build-debs/*
+}
+
+do_prepare_image() {
+  image_release_name=$1
+
+  run_updatedb
+  set_image_release "$image_release_name"
+  make_release_logos
+}
+
+run_updatedb() {
+  if [ -x /usr/bin/updatedb ]; then
+    echo 'Running updatedb in chroot'
+    updatedb
+  fi
+}
+
+set_image_release() {
+  image_release_name=$1
+
+  distribution=$(lsb_release -cs)
+
+  if [ -z "$distribution" ]; then
+    echo 'Could not figure out target image distribution' >&2
+    return 1
+  fi
+
+  build_date=$(date +%Y-%m-%d-%H%M%S)
+  build_version="$(get_imagetype)-${build_date}"
+  image_filename="${build_version}-${arch}.img"
+
+  if [ -n "$image_release_name" ]; then
+    new_release_name=$image_release_name
+  else
+    old_release_name=$(
+      cat /etc/ltsp/this_ltspimage_release 2>/dev/null || true)
+
+    while true; do
+      read -p "Release name [${old_release_name}]: " new_release_name
+      new_release_name=${new_release_name:-${old_release_name}}
+      [ -n "$new_release_name" ] && break
+      echo 'Give a release name!' >&2
+    done
+  fi
+
+  echo "$image_filename"   > /etc/ltsp/this_ltspimage_name
+  echo "$new_release_name" > /etc/ltsp/this_ltspimage_release
+}
+
+make_release_logos() {
+  if [ -x usr/lib/puavo-ltsp-client/puavo-make-release-logos ]; then
+    echo "Making release logos..."
+    /usr/lib/puavo-ltsp-client/puavo-make-release-logos
+  fi
+}
+
+do_set_root_passwd() {
+  while true; do
+    read -p 'Set root password [y/N] ? ' do_set_rootpw
+    case "$do_set_rootpw" in
+       '')         break ;;
+      Y|y) passwd; break ;;
+      N|n)         break ;;
+        *) echo 'Simple question, simple answer please!' >&2 ;;
+    esac
+  done
+}
+
 do_update_buildrules_from_buildhost() {
   # read from stdin
   tar --no-same-owner --no-same-permissions \
@@ -70,14 +193,14 @@ do_update_buildrules_from_buildhost() {
 
 do_update_buildrules_from_packages() {
   packages=$1
-  buildrules_dirs=$2
+  buildrule_dirs=$2
 
   do_cleanup_buildrules
 
   apt-get -y update
   apt-get -y install $(strip_commas "$packages")
 
-  for dir in $(strip_commas "$buildrules_dirs"); do
+  for dir in $(strip_commas "$buildrule_dirs"); do
     for subdir in debseeds puppet; do
       if [ -d "${dir}/${subdir}" ]; then
         cp -nR "${dir}/${subdir}" /etc/puavo-image-build/rules/
@@ -101,6 +224,8 @@ get_and_cache_puppet_classes() {
   echo "$puppet_classes" | tee "$puppet_classes_cache_path"
 }
 
+get_imagename() { cat /etc/ltsp/this_ltspimage_name; }
+
 get_imagetype() {
   if [ -z "$imagetype" ]; then
     imagetype=$(cat /etc/puavo-image-build/imagetype 2>/dev/null || true)
@@ -119,60 +244,109 @@ strip_commas() { echo "$1" | tr , ' '; }
 usage() {
   cat <<'EOF'
 Usage:
-  puavo-configure-image --bootstrap --imagetype imagetype
-  puavo-configure-image --cleanup-buildrules
-  puavo-configure-image --update-buildrules-from-buildhost
   puavo-configure-image --apply-buildrules
+                        --buildrule-args buildrule-args
+  puavo-configure-image --apt-dist-upgrade
+  puavo-configure-image --apt-update
+  puavo-configure-image --bootstrap --imagetype imagetype
+                        --apt-proxy apt-proxy
+                        --distribution distribution
+                        --mirror mirror
+  puavo-configure-image --cleanup-buildrules
+  puavo-configure-image --get-imagename
+  puavo-configure-image --get-imagetype
+  puavo-configure-image --image-release
+  puavo-configure-image --install-packages
+  puavo-configure-image --prepare-image
+  puavo-configure-image --set-root-passwd
+  puavo-configure-image --update-buildrules-from-buildhost
                         --error-on-change
-                        --puppet-classes puppet-classes
   puavo-configure-image --update-buildrules-from-packages packages
-                        --buildrules-dirs buildrules-dirs
+                        --buildrule-dirs buildrule-dirs
+
 EOF
   exit 1
 }
 
-if ! args=$(getopt -n "$0" -o + -l 'apply-buildrules,bootstrap,cleanup-buildrules,error-on-change,imagetype:,puppet-classes:,update-buildrules-from-buildhost,update-buildrules-from-packages:' -- "$@"); then
+if ! args=$(getopt -n "$0" -o + -l 'apply-buildrules,apt-dist-upgrade,apt-update,bootstrap,buildrule-args:,cleanup-buildrules,error-on-change,get-imagename,get-imagetype,image-release:,imagetype:,install-packages,prepare-image,set-root-passwd,update-buildrules-from-buildhost,update-buildrules-from-packages:' -- "$@"); then
   usage
 fi
 
-buildrules_dirs=
-buildrules_packages=
+action=
+apt_proxy=
+distribution=
+buildrule_args=
+buildrule_dirs=
+buildrule_packages=
 error_on_change=false
+image_release=
 imagetype=
-mode=
-puppet_classes=
+mirror=
 
 eval "set -- $args"
 
 while [ $# -ne 0 ]; do
   case "$1" in
     --apply-buildrules)
-      mode=apply-buildrules; shift
+      action=apply-buildrules; shift
+      ;;
+    --apt-dist-upgrade)
+      action=apt-dist-upgrade; shift
+      ;;
+    --apt-proxy)
+      apt_proxy=$2; shift
+      ;;
+    --apt-update)
+      action=apt-update; shift
       ;;
     --bootstrap)
-      mode=bootstrap; shift
+      action=bootstrap; shift
       ;;
-    --buildrules-dirs)
-      buildrules_dirs=$2; shift; shift
+    --buildrule-args)
+      buildrule_args=$2; shift; shift
+      ;;
+    --buildrule-dirs)
+      buildrule_dirs=$2; shift; shift
       ;;
     --cleanup-buildrules)
-      mode=cleanup-buildrules; shift
+      action=cleanup-buildrules; shift
+      ;;
+    --distribution)
+      distribution=$2; shift
       ;;
     --error-on-change)
       error_on_change=true; shift
       ;;
+    --get-imagename)
+      action=get-imagename; shift
+      ;;
+    --get-imagetype)
+      action=get-imagetype; shift
+      ;;
+    --image-release)
+      image_release=$2; shift; shift
+      ;;
     --imagetype)
       imagetype=$2; shift; shift
       ;;
-    --puppet-classes)
-      puppet_classes=$2; shift; shift
+    --install-packages)
+      action=install-packages; shift
+      ;;
+    --mirror)
+      mirror=$2; shift
+      ;;
+    --prepare-image)
+      action=prepare-image; shift
+      ;;
+    --set-root-passwd)
+      action=set-root-passwd; shift
       ;;
     --update-buildrules-from-buildhost)
-      mode=update-buildrules-from-buildhost; shift
+      action=update-buildrules-from-buildhost; shift
       ;;
     --update-buildrules-from-packages)
-      buildrules_packages=$2; shift; shift
-      mode=update-buildrules-from-packages
+      buildrule_packages=$2; shift; shift
+      action=update-buildrules-from-packages
       ;;
     --)
       shift; break
@@ -183,24 +357,42 @@ while [ $# -ne 0 ]; do
   esac
 done
 
-case "$mode" in
+case "$action" in
   apply-buildrules)
-    do_apply_buildrules "$error_on_change" "$puppet_classes"
+    do_apply_buildrules "$error_on_change" "$buildrule_args"
+    ;;
+  apt-dist-upgrade)
+    do_apt_dist_upgrade
+    ;;
+  apt-update)
+    do_apt_update
     ;;
   bootstrap)
-    do_bootstrap "$imagetype"
+    do_bootstrap "$apt_proxy" "$distribution" "$imagetype" "$mirror"
     ;;
   cleanup-buildrules)
     do_cleanup_buildrules
+    ;;
+  get-imagename)
+    get_imagename
+    ;;
+  get-imagetype)
+    get_imagetype
+    ;;
+  install-packages)
+    do_install_packages
+    ;;
+  prepare-image)
+    do_prepare_image "$image_release_name"
     ;;
   update-buildrules-from-buildhost)
     do_update_buildrules_from_buildhost
     ;;
   update-buildrules-from-packages)
-    do_update_buildrules_from_packages "$packages" "$buildrules_dirs"
+    do_update_buildrules_from_packages "$packages" "$buildrule_dirs"
     ;;
   *)
-    echo "Unknown mode: '$mode'" >&2
+    echo "Unknown action: '$action'" >&2
     usage
     ;;
 esac
